### ISSUE TITLE
Witness plugin custom op for editting

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1017]
0.17.0 allowed comments to editable indefinitely but enforced the same lockout as pre 0.17.0.

#894 moves all soft fork logic into the witnesses plugin, included the soft reject of edits. This issue is to create a custom op belonging to the witness plugin that will unlock editing for a period of time by use of their active authority. This way a compromised posting key does not allow editing of content by an attacker while still giving users the ability to edit and update their content whenever they'd like.

**Comment by arhag** [comment]
It seems like this soft-fork approach of limiting editing (or most other actions) could be very confusing to users.

It doesn't allow us to make a promise to users like: "Even if your posting key is compromised, your old posts are still safe from defacement." Nor do I think it is fair for us to say "it is highly unlikely that your old posts could be defaced from just a posting key compromise." The reason I don't think the latter statement is fair to say is because it doesn't require a lot of stake to become a backup witness with high enough stake to get a chance to produce a block in a reasonable amount of time (like a couple times per day). So, the attacker could simply run a witness node with modified code that rejects the soft forks and include the defacement transaction in their generated block.

It would be a lot simpler (to the users) if we could either just make the first claim by making this mechanism a part of consensus, or if we don't want such a hardforking change to consensus, to simply say relax the protections and only claim "posting key compromises can lead to defacement of any of your posts, but don't worry too much because when you get back control of your account you can always easily recover the original state of your posts/comments thanks to the immutable edit history" (once we develop and enable that convenient feature of course).

If you do think this soft-fork mechanism is a worthwhile compromise to handling the defacement threat without needing to bloat the consensus mechanism with new operations (and without having less flexibility to quickly and easily change the mechanisms in the future), then I have some other suggestions for how we could more confidently make the second claim (the one about it being "... highly unlikely ...").

First, you could track the last time an account _edited_ a post/comment (not created a new one) and use that field to require only one edit per account per block. This limits the rate at which a low runner-up witness can deface a particular user's posts and comments to manageable levels (for each user).

Second, and this mechanism is more generally applicable to all soft forks not just for this case of editing posts, you can design the witness code to skip a block produced by a runner-up witness if it includes transactions which violates soft-forks that the node recognizes (or perhaps just a subset of the soft-forks on a whitelist). Since there is only one runner-up witness per block, this means there would only be up to only one intentionally missed block per round. This is a more significant technical change, and I am not sure what effect it may have on performance of block production, so perhaps it may not be worth it to implement. But if it was implemented, users could more comfortably rely on the soft-fork protections as long as they trusted all of the top 20 witnesses.

**Comment by mvandeberg** [comment]
The second mechanism is our plan for handling soft forks.

Eventually, we would like to change the forking logic so that a witness, if given the choice, will not produce on a block that violates their soft logic, but are willing to build on it if a majority of witnesses chose to build on it.

So long as the 20 elected witnesses are always running the release code, the forks caused by this logic will be minimal. It could be attacked if greater than 50% of the elected witnesses colluded, but that is true for all attacks.
