### ISSUE TITLE
declined payout rshares added to recent_claims?

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#1026]
Minor issue but could be good to double-check this logic.

**Comment by mvandeberg** [comment]
Currently, posts declining payout do have their rshares added to recent claims. However, the fix is not easy. Because all content's claims are added before payout, each addition changes the pending payout. But declining payout is implemented by setting the `max_accepted_payout` to 0 SBD. However, the actual amount of STEEM removed from the reward fund is determined after claims are added. The quick fix for this particular case is only add recent claims if `max_accepted_payout` > 0 SBD.

But what about the case when `max_accepted_payout` is set to 10 SBD and the post would have made 20 SBD? Are 50% of the claims returned? But that means we need to recalculate payouts for all posts in that block, which might make the post get 20.1 SBD now, so too few claims were added to recent claims.

We can fix this specific case when `max_accepted_payout` is 0 SBD, but the case when `max_accepted_payout` is 0.001 SBD will work as it does now.

**Comment by mvandeberg** [comment]
The case described above outlines why such a change to the existing logic would be problematic. Closing this.
