### ISSUE TITLE
Steemdsync should generate blockchainstate files on its own

### ISSUE THREAD

**Issue by jredbeard** [steemit/steem#1050]
Steemdsync should be able to generate blockchainstate files with a `block_log` file and a `--replay-blockchain`. In addition, it should pull the current version with a short version of the git commit hash from `/etc/steemdversion`.

**Comment by mvandeberg** [comment]
As a precaution we should launch steemdsync with `--force-validate`. Because we are saving and loading a blocklog doing a hash of the block log isn't feasible. Thankfully, the blockchain is a bunch of hashes, so we can use that. `--force-validate` will force validation of all signatures and hashes. On local machines this is usually not a problem and skipping such validation speeds up reindex times. But for the integrity of our production environment, we should be doing these checks on replay.
