### ISSUE TITLE
Unable to run full node under valgrind (with large mapped file)

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/steem#1071]
Attempt to run `steemd` configured as full node under valgrind:
`valgrind ./bin/steemd-v0.18.2-full -d fullnode`

results in:
```
2739649ms th_a       application.cpp:266           startup              ] Starting Steem node in write mode.
2739847ms th_a       database.cpp:143              open                 ] 13 N5boost12interprocess22interprocess_exceptionE: Invalid argumen
t
rethrow Invalid argument:
    {"data_dir":"/home/steem/fullnode/blockchain","shared_mem_dir":"/home/steem/fullnode/blockchain","shared_file_size":"51539607552","what":"Invalid argument"}
    th_a  database.cpp:143 open
2739851ms th_a       database.cpp:143              open                 ] data_dir: /home/steem/fullnode/blockchain shared_mem_dir: /home/steem/fullnode/blockchain shared_file_size: 51539607552 
2739857ms th_a       application.cpp:392           startup              ] 13 N5boost12interprocess22interprocess_exceptionE: Invalid argument
rethrow Invalid argument: 
    {"data_dir":"/home/steem/fullnode/blockchain","shared_mem_dir":"/home/steem/fullnode/blockchain","shared_file_size":"51539607552","what":"Invalid argument"}
    th_a  database.cpp:143 open
2739863ms th_a       application.cpp:976           startup              ] 13 N5boost12interprocess22interprocess_exceptionE: Invalid argument
rethrow Invalid argument: 
    {"data_dir":"/home/steem/fullnode/blockchain","shared_mem_dir":"/home/steem/fullnode/blockchain","shared_file_size":"51539607552","what":"Invalid argument"}
    th_a  database.cpp:143 open
rethrow
    {}
    th_a  application.cpp:392 startup
2739877ms th_a       main.cpp:213                  main                 ] Exiting with error:
13 N5boost12interprocess22interprocess_exceptionE: Invalid argument
rethrow Invalid argument: 
    {"data_dir":"/home/steem/fullnode/blockchain","shared_mem_dir":"/home/steem/fullnode/blockchain","shared_file_size":"51539607552","what":"Invalid argument"}
    th_a  database.cpp:143 open
rethrow
    {}
    th_a  application.cpp:392 startup
```

**Comment by Gandalf-the-Grey** [comment]
As a side effect to that, after such attempt, when I want to run it back again in a normal way, without `valgrind`, i.e.:
`./bin/steemd-v0.18.2-full -d fullnode`
it seems to stuck for unreasonable amount of time (20 minutes already, still counting) at:
```
1902673ms th_a       application.cpp:266           startup              ] Starting Steem node in write mode.
1902673ms th_a       block_log.cpp:118             open                 ] Log is nonempty
1902673ms th_a       block_log.cpp:127             open                 ] Index is nonempty
```
while negligible system load (cpu nor i/o)

**Comment by mvandeberg** [comment]
The behavior on restart looks to be because of what went wrong with valgrind. Depending on where the Boost Interprocess Exception was thrown, it is possible (and from the behavior of the subsequent runs, likely) that it exited mid setup of the shared memory file and left it in a completely inconsistent state. 

The stack trace appears at such (skipping the boost calls)

```
generic_index::undo()
generic_index::undo_all()
chainbase::undo_all()
database::open()
application_impl::startup()
application::startup()
```

However, generic_index::undo_all() is this:

``` c++
/**
 * Unwinds all undo states
 */
void undo_all()
{
   while( enabled() )
      undo();
}

bool enabled()const { return _stack.size(); }
```

Items are only allocated to the undo stack when undo states are created, which does not happen in `database::open` (The location of the exception when running valgrind)

It appears that the undo stack was corrupted as no undo states should have been created when the crash occurred, resulting in the strange behavior upon restarting the node.

This still does not solve why valgrind isn't working, but at least explains the strange behavior as an artifact of that problem.

**Comment by NateBrune** [comment]
By default, valgrind can only keep track of 32G of memory. The default configuration of steemd attempts to allocate a 32G file, but needs additional memory for the stack and heap of steemd itself. Due to this the required memory for steemd in the default configuration is slightly more than the 32G valgrind supports.
If you wish to run steemd with valgrind, you have two options

1. Change config.ini to use slightly less memory (`shared-file-size = 31G`)
2. Follow [this guide](http://stackoverflow.com/questions/8644234/why-is-valgrind-limited-to-32-gb-on-64-bit-architectures) to recompile valgrind to support >32G memory.
