### ISSUE TITLE
Assertion issues in `comment_options_evaluator`

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#108]
Possible issues with [this code](https://github.com/steemit/steem/blob/825c31af0c0d11a8d8d707306caaae540c9d885b/libraries/chain/steem_evaluator.cpp#L171-L176):
```
   FC_ASSERT( comment.abs_rshares == 0 );
   FC_ASSERT( comment.max_accepted_payout >= o.max_accepted_payout );
   FC_ASSERT( comment.percent_steem_dollars >= o.percent_steem_dollars );
   FC_ASSERT( comment.allow_replies >= o.allow_replies );
   FC_ASSERT( comment.allow_votes >= o.allow_votes );
   FC_ASSERT( comment.allow_curation_rewards >= o.allow_curation_rewards );
```

* if there is an auto-voting bot, the author will be hard if not unable to change options
* it doesn't make much sense if only allow disabling but not re-enabling replies and votes
* is it possible to disable replies on a post/comment which has some replies already? If yes, does it cascade (recursively apply to all children)?

**Comment by abitmore** [comment]
In [this code](https://github.com/steemit/steem/blob/825c31af0c0d11a8d8d707306caaae540c9d885b/libraries/chain/steem_evaluator.cpp#L178-L183), `allow_curation_rewards` hasn't been applied to the object.

**Comment by mvandeberg** [comment]
We will be adding these options in the UI so that these options can be applied atomically with the creation of the comment.

I have changed disabling replies to cascade and can be applied if comments exits. This is more of a way to self moderate your content and stop inappropriate discussion.

I have made the check for abs_rshares == 0 to only be required when disabling votes or curation rewards. Those options should only be changed at creation. Max accepted payout and percent steem dollars can be changed at any time so long as the accepted payout and the percent steem dollars are decreasing.
