### ISSUE TITLE
Delegate vesting shares

### ISSUE THREAD

**Issue by jcalfee** [steemit/steem#1089]
If you delegate all of your vesting shares to another account, it appears that your locked out of the original account.  This is what I see when I try to re-run delegate_vesting_shares with a slightly lower VESTS amount::
```
10 assert_exception: Assert Exception
has_bandwidth: Account exceeded maximum allowed bandwidth per vesting share.
```

**Comment by mvandeberg** [comment]
Delegations transfer bandwidth capacities as well. It is no different than if you withdraw all of your vesting shares. For now, power up a single STEEM into the account that made the delegation. We are working on a more elegant long term solution.

**Comment by 4Ykw** [comment]
Would it be simple to make the delegation to never withdraw all the SP?

Example:
You have 100 SP.
You try to delegate 100 SP to someone.
The result will be a 95 delegation. (A warning message saying how much you can delegate would be awesome).

For new users created, this is a problem because steem has to support their activity while they do not decide to have enough SP. But this could also be beneficial, since users that do not post or do not care for their keys anymore, can be successfully "disabled" to mess with the system until they buy some SP.

**Comment by sneak** [comment]
@4Ykw - there is a better solution in the works; stay tuned.  Closing this for now.
