### ISSUE TITLE
average_market_bandwidth 0

### ISSUE THREAD

**Issue by Hunternnm** [steemit/steem#1235]
Hi! I created a bot(@bot-helper), and after a few comments the average_market_bandwidth of the bot became 0 and I can not write comments. Tell me, how is this parameter calculated? And where can I read the description of the other parameters? API returns a large number, about which I can not even guess.

**Comment by theoreticalbts** [comment]
This behavior is by design.

Accounts are rate-limited based on the amount of Steem Power they have, and the level of activity on the network.  Getting more Steem Power will allow an account to transact more frequently.

The bandwidth computation is implemented by [this code](https://github.com/steemit/steem/blob/5c328905414477862bfdb7b600a8ecaa987af26b/libraries/plugins/witness/witness_plugin.cpp#L276-L329).

We're working on an API documentation site, but it's not quite ready.

**Comment by Hunternnm** [comment]
Thank you!
