### ISSUE TITLE
update first tag failed

### ISSUE THREAD

**Issue by slumber1122** [steemit/steem#1269]
when I update the tag list, modify the first tag, save. but it do not work.

**Comment by oflyhigh** [comment]
First tag is category，can not be changed.

**Comment by bdeely** [comment]
I feel like this should be considered an issue. For example:

- User publishes post with 'asia' as the first tag, which becomes the category
- User decides they actually want a more specific tag 'japan' to be the category

Current behavior is: steemit keeps the first tag you use as the category

Expected behavior is: if you update the first tag, that new tag becomes the new category

**Comment by mvandeberg** [comment]
On Steemit.com, the first tag doesn't mean anything. It will show up in all the tags. This is only an issue if users believe the first tag is the most important, which it is not.
