### ISSUE TITLE
Appbase static casts

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1308]
Appbase static casts of pointer types should be able to be removed as the method calls performed on them are virtual.

**Comment by vogel76** [comment]
I suppose you are talking about code placed inside appbase::plugin template class, for example:
`
static_cast< Impl* >( this )->plugin_requires( [&]( auto& plug ){} );
`
If so, here is a problem because plugin class or its base abstract_plugin does not know plugin_requires, plugin_initialize, plugin_startup, plugin_shutdown methods. 

As I see `plugin_requires` method is defined by a macro APPBASE_PLUGIN_REQUIRES, taking a list of plugins given one depends on (requires them). This could be achieved by passing them trough variadic template arg in plugin class and making `plugin_requires' a non-virtual method private of 'plugin' class. Then macro could be removed.

Another option (maybe better, because its fit into current design) is add pure declarations of plugin_* methods inside `plugin` class and mark them as overrided in derived classes. 

I also propose to mark methods currently implemented in plugin class as final, since they rather shall be not reimplemented.

**Comment by mvandeberg** [comment]
I don't see any reason why `pluign_*` should not be defined in `abstract_plugin`.

I think the reason the dependencies are not passed in this way is because of readability of the plugin parent class. Plugins already have themselves as a template argument and having a potentially long variadic template would hinder readability. I am fine with `APPBASE_PLUGIN_REQUIRES`.

Add the virtual `plugin_*` declarations in abstract plugin and make any methods not intended to be implemented by a plugin subclass final.
