### ISSUE TITLE
I can't remove a vote (only affects one post that I know of)

### ISSUE THREAD

**Issue by jcalfee** [steemit/steem#139]
I can't remove a vote on http://steemit.com/test/@jsc/test-tags-with-spaces

Just testing to not critical.  I was able to flag and unflag other posts..
```
broadcast Error: 10 assert_exception: Assert Exception
o.weight != 0: Vote weight cannot be 0
    {}
    th_a  steem_evaluator.cpp:692 do_apply
```

**Comment by mvandeberg** [comment]
That assertion only applies for new votes. Is it possible you are trying to remove a vote for a post that has already been paid out?

We are currently deleting votes lazily. After a comment is paid out all votes have num_changes set to -1, which signals they are no longer active on the comment. The UI is still displaying as thought the user has voted because they are still in the database. Clicking the vote to remove it is likely generating a vote change to a weight of 0, but because num_changes is -1, it is actually a new vote with a weight of 0; thus the error.

Easiest solution is probably to filter votes returned in the API so the UI does not think a vote exists that actually doesn't.

**Comment by jcalfee** [comment]
test-tags-with-spaces does not appear in my UI wallet transaction history.. I don't think it ever had a positive payout.  On some of these tests posts I do change my vote often.

**Comment by jcalfee** [comment]
I'll try filter the active_votes list where the active_vote.time > post.last_payout.  This will reset the Voting bar and see if that works..  I still need confirmation though before I checkin.

**Comment by jcalfee** [comment]
It was a UI bug .. it is working now.  I only count my vote was casted after the last_payout.
