### ISSUE TITLE
Liquidity Rewards are n^2 which makes it winner take all 

### ISSUE THREAD

**Issue by bytemaster** [steemit/steem#141]
We should change liquidity rewards to be min(SBD_VOLUME, STEEM_VOLUME)

**Comment by mvandeberg** [comment]
I am a little confused why being n^2 makes the rewards winner take all. The rewards are defined as winner take all on a per hour basis, but that can be achieve through any curve.

I plotted the curves and their difference to have an objective conversation about the differences. Because this is a monotonically increasing function (if x or y increases, f(x,y) increases) we can safely apply a monotonic transformation (squareroot) and still have a monotonic function. Therefore this function produces the same results as the implemented function with a desired range.

`f(x,y) = ( max(x,0) * max(y,0) )^1/2` "n^2"
![n2](https://cloud.githubusercontent.com/assets/15834128/16657003/d1766a48-442e-11e6-8519-79375ebdfe4b.gif)![n2_top](https://cloud.githubusercontent.com/assets/15834128/16657076/1a130360-442f-11e6-8ccf-a04483728cd0.gif)

I normalized this curve with the square root, so we can plot the difference between the curves along the same domain and range.

`g(x,y) = min(x,y)` Proposed solution
![min](https://cloud.githubusercontent.com/assets/15834128/16657136/5b62d7aa-442f-11e6-829b-c8e58cf23017.gif)![min_top](https://cloud.githubusercontent.com/assets/15834128/16657140/5e669e00-442f-11e6-8d73-b3424826a15e.gif)

`h(x,y) = f(x,y) - g(x,y)` Difference
![diff](https://cloud.githubusercontent.com/assets/15834128/16657182/8226baf0-442f-11e6-8e0d-90aae0fd9a2c.gif)![diff_top](https://cloud.githubusercontent.com/assets/15834128/16657183/8450a840-442f-11e6-9b65-ef7a85698c6d.gif)

On the diff, the higher peaks are those users that would be hurt by changing the curve. If all users were trying to equalize their volumes, there is no difference in payouts. However, I will argue that multiplying the volumes is a great tie breaker in situations where two users have the same, or close, highest volume.

**Comment by arhag** [comment]
The problem I have with the g(x,y) = min(x,y) rule is that x and y are in different units. I think they both need to be in the same unit, e.g. SBD.

I think the `liquidity_reward_balance_object` struct needs to be modified to instead track `sold_sbd_volume_in_sbd` and `sold_steem_volume_in_sbd`. In the [`match` function](https://github.com/steemit/steem/blob/2914eb67522f11449697216f4db394c2832545ec/libraries/chain/database.cpp#L2961-L2970), the code would add to and subtract from these variables as appropriate using the amount of SBD exchanged in the match. Then you could use the `std::min(sold_steem_volume_in_sbd, sold_sbd_volume_in_sbd) * is_positive()` formula the liquidity score.

**Comment by abitmore** [comment]
```
