### ISSUE TITLE
Ability to convert from STEEM Dollars to Steem Power after 1 week.

### ISSUE THREAD

**Issue by bytemaster** [steemit/steem#144]
After one week delay, the STEEM received should be powered up automatically if the user desires.

This is up for debate as to implementation.

**Comment by theoreticalbts** [comment]
This was implemented by vesting routes #78

**Comment by theoreticalbts** [comment]
Would it suffice to add a "dump-and-convert" option in the UI to sell SBD at market price using fill-or-kill order, then immediately convert in the same tx?

**Comment by willbanks** [comment]
@theoreticalbits No @bytemaster 's  idea is much better.  Doing as you propose, people will game the system.  The cooling period is the only thing providing an incentive to hold the SBD rate close to the actual dollar rate and not screw with the price too much in order to gain influence.  Now that liquidity provider incentives are gone.

I realize what you propose can be done already, but the number of steps involved and the fact that the internal market is driven by a principle of (what you ask is what you get), functions as a check against bad behavior that can be induced by market dumping.

**Comment by mvandeberg** [comment]
With the reduced inflation rate and the fact that holding STEEM is no longer as detrimental as it once was I think this is now feature bloat and does not bring anything meaningful to the blockchain.
