### ISSUE TITLE
Create step-by-step example of adding an operation to Steem

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1457]
We have some new backend devs who will be helping implement operations.  To help explain how to do this, I will add a new operation as an example, showing each step along the way.

**Comment by Kiwonik** [comment]
Questions regarding further implementation of `smt_elevate_account_operation`:
1. It seems to us that the `fee` member of `smt_elevate_account_operation` is redundant in terms of actual amount, that is established by evaluator on its own (obtained from db). However the member still carries important information about the asset_symbol_type the client wants to use. Thus the `asset fee` can be reduced to `asset_symbol_type fee_symbol`.
2. Is the actual fee transfer supposed to be a part of `smt_elevate_account_evaluator::do_apply` code? Or rather a prior separate transfer operation that must be only identified in the account history in said `do_apply`. Assuming the former, shall we use `transfer_operation` with its evaluator, or reuse (aka copy-paste) the code of `transfer_evaluator::do_apply` or rather put its body into separate function called from both transfer and elevate evaluator?

**Comment by theoreticalbts** [comment]
> the fee member of `smt_elevate_account_operation` is redundant in terms of actual amount, that is established by evaluator on its own (obtained from db)

Right now the fee is constant, but later we may create a process for changing the fee (based on witness votes).  If the fee isn't given in the operation, and let's say the fee is raised someday from $1000 to $5000, a user creating an account may have their UI show the fee will be $1000 -- which is accurate at the time -- and then be very upset when the transaction he authorized gets into the blockchain a few blocks later (after the change takes effect) and $5000 is deducted from his account.

What should happen in this case is the transaction signed by the user should say "I authorize paying a fee of $1000" and then if the blockchain requires a higher fee at the moment the transaction is processed, the transaction will be rejected and never happen.

The second issue is that the user's account history should show how much was paid when they elevated in the past.  If the fee is implicitly contained in the database, we would have to create a second, virtual operation to document how much was deducted.  This is possible but more complex, in our design of operations we sometimes deliberately include a few extra bytes of redundant information if it makes the operation a better fit for our architecture.

**Comment by theoreticalbts** [comment]
> Is the actual fee transfer supposed to be a part of smt_elevate_account_evaluator::do_apply code?

Yes, it's just not implemented yet.

> Assuming the former, shall we use transfer_operation with its evaluator, or reuse (aka copy-paste) the code of transfer_evaluator::do_apply or rather put its body into separate function called from both transfer and elevate evaluator?

Basically the logic will be copy-pasting the `transfer_evaluator` body.  (We need not worry about the `active_challenged` part, it is related to a feature that was never fully implemented and is now deprecated.)

It will basically be:

```
   FC_ASSERT( _db.get_balance( from_account, o.amount.symbol ) >= o.amount, "Account does not have sufficient funds for transfer." );
   _db.adjust_balance( from_account, -o.amount );
   _db.adjust_balance( to_account, o.amount );
```

**Comment by vogel76** [comment]
I think it could be better to implicitly instantiate (during `smt_elevate_account_operation` evaluation) transfer_operation (using stored and verified fee) and do its evaluation as usual. This will avoid potential problems on potential future changes related to asset transfers.

**Comment by Kiwonik** [comment]
I took the liberty of making my first contribution to smt development (below), while it's still in the branch. Do you mind @theoreticalbts if I commit this (and following) change? Not even sure if I got appropriate github permission...
```
--- a/libraries/chain/smt_evaluator.cpp
+++ b/libraries/chain/smt_evaluator.cpp
@@ -29,6 +29,11 @@ void smt_elevate_account_evaluator::do_apply( const smt_elevate_account_operatio
    }
 
    const account_object& acct = _db.get_account( o.account );
+   if( acct.is_smt == true )
+   {
+      FC_ASSERT( false, "The account has already been elevated." );
+   }
+   
    _db.modify( acct, [&]( account_object& a )
    {
       a.is_smt = true;
```

**Comment by theoreticalbts** [comment]
@vogel76 Yes, that's another possible approach.  I'm not sure it is in keeping with the Steem coding style.  @mvandeberg do you have any opinion?

@kiwonik Feel free to create your own branches, except for `stable`, `master`, `develop` anyone can create, commit, force-push, etc. to any branch.  Everyone on your team should have Github permissions to push branches on this repo.  If you don't, please message @sneak or @jredbeard

**Comment by mvandeberg** [comment]
What I would rather do is create a helper method for transfers that does both balance adjustments rather than create an op locally. Operations were never designed to be created and used internally as subroutines.

I am adamant that the fee be in the operation in the whole rather than a symbol. We want as many of our operations to be self describing as possible. Take a transfer operation, for example. While it does require knowledge of state (a sufficient balance), if the op is included in the chain irreversibly we can, with reasonable certainty, assume that the account had the necessary balance. The case when that assumption is false requires collusion and forking by witnesses. If there is a way we can reasonably design an operation such that the state transition itself does not depend on state, we should do so. The vote operation is an operation that does not follow this pattern because neither the account's voting power or Steem Power are included in the operation and both are required to define the state transition.

This branch contains one of my coding pet peeves. Code in the style of

``` c++
if( x )
   return true;
```

When it should be written as 
``` c++
return x;
```

``` c++
if( acct.is_smt == true )
{
   FC_ASSERT( false, "The account has already been elevated." );
}
```

Should be 

``` c++
FC_ASSERT( !acct.is_smt, "The account has already been elevated." );
```

**Comment by vogel76** [comment]
@mvandeberg I'd like to still opt for implicit operation/evaluator reuse approach. Creating a dedicated method (probably static one in the needed evaluator class) is artificial and pollutes the code. Moreover it requires changes in the evaluator which is about to use instead of focusing on the code being under development. Personally I think it would be very strange if local instantiation of  2 classes (operation and evaluator) could cause problems, so maybe let try it first and verify that works correctly.

**Comment by Kiwonik** [comment]
@theoreticalbts 
1. Until we agree otherwise I'll be creating subbranches to 1457-step-by-step and accompanying pull requests. Here are first one - https://github.com/steemit/steem/pull/1492

2. You seem to made an implicit assumption that dgpo.smt_creation_fee is always in SBDs (and adjust user provided fee accordingly), while the WP says "This field may contain a value in STEEM or SBD" with regard to dgpo.smt_creation_fee. Is this correct and the code needs to handle all four possibilities (user fee symbol x smt_creation_fee symbol) or the misleading description in WP needs rephrasing?

**Comment by vogel76** [comment]
I have still doubts related to smt_elevate_account composition. As I see, the database is able to send notifications related to the performed operation (`database::pre_apply_operation`, `database::post_apply_operation`). When `smt_elevate_operation` operation will be not inherited from transfer_operation (what makes sense I think since asset transfer is an obligatory part of elevate op), this operation performed on database will be automatically visible in all existing places as regular transfer, what will lead to correct account history supply, statistic collector etc. When these operations will be separated, all these places must be manually changed. Anyway there is still possible to add dedicated method to any existing visitor to especially handle elevate operation, if it is needed (I have created some small external example related to fc::static visitor and did check given case).

**Comment by mvandeberg** [comment]
With operation history we have the idea of virtual operations. These are operations that are purely descriptive of automated actions and are not allowed to be included in blocks. An example of a virtual operation is a payout from a comment. It automatically occurs but is important to log that it happened.

The use of the transfer operation in this case and the rationale for doing so (correct account history) looks more like a virtual operation with the exception that you still want to use the transfer operation evaluator. Personally, I think it would be more confusing to see a transfer to the null account for burning a fee than to not see it. Strictly speaking, transferring to the null account for burning a fee is an implementation detail and an optimization (allows us to only need to burn STEEM and update supplies once per block) rather than a strict design requirement.

**Comment by theoreticalbts** [comment]
Merged, closing.
