### ISSUE TITLE
Increase liquidity reward period to 1 hr

### ISSUE THREAD

**Issue by bytemaster** [steemit/steem#149]
The goal of this proposed change is to minimize the potential for self trading while the market is less active. Market makers can still make money placing orders further from the active trading window.  These "back stop" orders provide cover for liquidity providers trying to make money on the natural spread.

**Comment by abitmore** [comment]
Discussions in Slack:

gavvet [1:04 AM]  
on the liquidity issue, what about longer(tuned parameter)time frame (1 hour e.g.)  for order to be on books required.... but only counts if spread less than (tuned parameter) at time of filling....calculated at time of filling... therefore incentive to keep small spread for longer time frames. Rewards the patient in quiet markets. Much harder to game in moving markets. Will incentive depth of orders too. to catch the moving market.

complexring [4:29 AM]  
@gavvet, maybe.  the problem is precisely a moving market because then no one would get liquidity points ... i guess person who is still at the top of the list would get the next.  however, we really want liquidity during market movements ... either in some other sense of appropriate reacting to sudden changes in the market by monitoring price feeds and auto-changing orders

smooth [7:34 AM]  
complexring: there is always going to be some spread where it usually will take >1 hour to be hit, even if it is sometimes hit sooner. But none of this actually measures real liquidity it just shifts around the rules for gaming the reward

**Comment by abitmore** [comment]
Better make it configurable by witnesses?
