### ISSUE TITLE
Surround SMT Objects, Evaluators, and Fields in #ifdef IS_TEST_NET

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1510]
Adding new objects and fields to objects changes the footprint of the shared memory file. This can cause unnecessary reindexing for main net releases. While SMTs are in development, as much code as possible should be disabled via `#ifdef` so that it does not impact the main net release binary.

**Comment by theoreticalbts** [comment]
SMT's will involve changing the `asset` data structure, existing operations, and utility methods like balance and supply methods.  We want to be able to easily check that our changes still allow us to replay / sync to the main network.

If there's some bug that keeps us from syncing, I want to know about it sooner rather than later.

Maybe this should be a separate flag?

**Comment by Kiwonik** [comment]
Implemented with separate flag STEEM_ENABLE_SMT.
The flag is defined or not based on the value of ENABLE_SMT_SUPPORT new option of CMake analogous to BUILD_STEEM_TESTNET option.
