### ISSUE TITLE
steemd crashes with Assertion `std::current_exception() == std::exception_ptr()' failed

### ISSUE THREAD

**Issue by chriswhocodes** [steemit/steem#1524]
Every few days my steemd will crash with the following line at the end of the log file:

```steemd: /home/steem/s2/steem/libraries/fc/src/thread/thread_d.hpp:372: bool fc::thread_d::start_next_fiber(bool): Assertion `std::current_exception() == std::exception_ptr()' failed.```

Happens on multiple VPS servers running various plugins.

Systems are all Ubuntu 16.04:
```uname -a
Linux seed 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux```

libc:
ii  libc6:amd64                            2.23-0ubuntu9                              amd64        GNU C Library: Shared libraries
ii  libc6-dev:amd64                        2.23-0ubuntu9                              amd64        GNU C Library: Development Libraries and Header Files
```
Codebase was head of git cloned 30th Aug 2017.

Thanks.

**Comment by mvandeberg** [comment]
A few points:

- Are you using one of our Docker images? This is the first report I have seen of this assertion failing. It is possible a different version of a dependency is causing this behavior.

- We will be moving away from fc cooperative multitasking over the coming months, so I am hesitant to fix this unless I receive more similar bug reports.

- Because it is an assertion failing, steemd will not crash if you build a release. `-DCMAKE_BUILD_TYPE=Release`. However, if there is a bug here, you may encounter crashes from undefined behavior elsewhere.

**Comment by chriswhocodes** [comment]
Hi,
No, built from source, not a Docker image.
Looks like someone also reported this on the graphene project back in 2015: https://github.com/cryptonomex/graphene/issues/332

It's minor and I have a restart script for the witness, feel free to wontfix if you like :)

**Comment by mvandeberg** [comment]
We have chosen to move away from fc threading. Closing, won't fix.
