### ISSUE TITLE
API Testing

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1567]
We have no testing of our APIs. At the very least, we could use sanity checks that the API stack works properly and returns sane results.

**Comment by vogel76** [comment]
Maybe it is worth to create dedicated API (or use debug_plugin_api) to implement a helper API offering functionality to iterate over all registered APIs in the application.
Thus, there will be easily controlled:
- possibility to call any API method
- availability of all needed APIs being registered in the application.
In further steps, dedicated tests shall be done for specific APIs, what could be not so straightforward, since some of them can need proper data imported/generated from blockchain.
For such 2nd step, dedicated testing schedule must be defined, especially which APIs shall be tested first.

**Comment by mvandeberg** [comment]
One idea that @theoreticalbts and I had several months ago was to do all of the api testing in python. @theoreticalbts had been working on an approach to reproducing a base blockchain state using the debug node API interfacing through Python.

Whatever you want to do to test the APIs, I am fine with. Why don't you create some infrastructure and write a simple test for `database_api.get_dynamical_global_properties`. We can review the approach with a small example and if it looks good we can move forward with that approach for the rest of the APIs.

**Comment by vogel76** [comment]
Probably this python library can be helpful to make tool executing tests.
https://github.com/svanoort/pyresttest

**Comment by mkochanowicz** [comment]
I added some unit-tests using simple PyRestTest tool (https://github.com/svanoort/pyresttest).

- Tests can be defined in YAML/JSON config files.
- Request body could be templated (Python template string) or even loaded from file.
- Validators could extract tested parts of response body.
- Logic is simply extendable (extractors, comparators, validators).
- It works on Linux & Mac.
- Looks like easy adoptable as part of smoketest after build with Jenkins.

I added also simple extension: new validator comparing extracted result with pattern file. If comparison failed validator generates output file to decide what to do (create new pattern or change comparison method).

There are several tests for `database_api` - most of methods without args.

Tests are in `python_scripts/tests/api_tests`. To run them:
- Install PyRestTest.
- Launch steemd.
- Set `RPC_PORT` in `run_api_tests.sh` the same as in steemd's `config.ini`.
- Execute `run_api_tests.sh` in `python_scripts/tests/api_tests` dir.

Note: existing patterns (*.json.pat) are generated from steemd launched in TESTNET with `run_api_tests.sh` set to false.

**Comment by mkochanowicz** [comment]
Now single test in form:
```
- test:
  - name: "list_witnesses"
  - variable_binds:
    - method: "get_feed_history"
    - args: '{ "start": 0, "limit": 1, "order": "by_name" }'
  - <<: *base_test
```
