### ISSUE TITLE
Rationalizing Market Orders (was: Tick Pricing Rules)

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1573]
Currently `price` accepts any value for base / quote amounts.  The result is that you can have prices which don't have any decimal representation, like 3 STEEM / 7 SBD.

- Each 1 STEEM is worth `$2.33333333333...` in SBD
- Each 1 SBD is worth `0.42857142857142857...` in STEEM

Additionally you can express base / quote in either order, i.e. you can "flip" the prices at the blockchain level.

Expressing prices like this leads to various counterintuitive UI behaviors, for example, two apparently-overlapping orders do not execute.  This is because the user expectation is that (a) UI's will use decimal notation to express prices, and (b) the UI's decimal value is an exact representation of the effective price on the blockchain.

Let's introduce some rules which I'll call Tick Pricing Rules:

- For prices involving Steem Dollars (SBD), the base asset must be SBD.
- For prices involving SMT assets, the base asset must be STEEM.
- The quote must be a power of 10.
- The base value can have at most 4 nonzero decimal digits.

Basically these rules together mean that trading takes place on "ticks" of between 0.001% and 0.01%.  Let's say STEEM is trading at `$1.253`.  According to the TPR, an order to buy or sell STEEM at `$1.253` will trade at *exactly* that price.  The next larger price would be `$1.254`, and the next smaller price would be `$1.252`.  The "tick" is `$0.001`, which works out to 0.00079% of `$1.252`.  If someday STEEM starts trading at SBD at a larger value, say the `$10.00-99.99` range, then the "tick" will become `$0.01`.  Likewise, once STEEM breaks `$100` barrier, the "tick" will become `$0.10`.

Likewise, the "tick" can also become smaller if necessary, for example if STEEM is `$0.3281` could be expressed as a quote of `0.100 STEEM` and a quote of `3.281 SBD`.

In "flipped" terms, these prices do not have round values (i.e. short, terminating decimal representation), but approximately correspond to `0.79872`, `0.79808` and `0.79745`.

This ticket is to implement a hardfork with the following semantics:

- `feed_publish_operation` and `limit_order_create2_operation` must use prices that obey TPR.
- `limit_order_create_operation` is disabled

**Comment by theoreticalbts** [comment]
The `limit_order_create2_operation` requires that `amount_to_sell.symbol == exchange_rate.base.symbol`, and the matching engine expects this.  So to maintain backward compatibility with earlier version of `limit_order_create2_operation` and minimize the changes needed to the order matching code, the requirements for `limit_order_create2_operation` should be defined in more detail as follows:

- When `amount_to_sell` is SBD, then `exchange_rate` must be TPR.
- When `amount_to_sell` is SBD, then `~exchange_rate` must be TPR (the `~` operator flips the price).
- When `amount_to_sell` is an SMT asset, then `~exchange_rate` must be TPR.
- When `amount_to_sell` is STEEM and an SMT asset occurs in the price, then `exchange_rate` must be TPR.

**Comment by mkochanowicz** [comment]
@theoreticalbts These changes need STEEM_HARDFORK_0_20 or smt hf?

**Comment by mvandeberg** [comment]
This would be for SMTs.

I want @sneak's opinion as this is as much a UX decision as it is a technical one.

**Comment by goldibex** [comment]
After a discussion we've decided this work will be implemented at the UX level (i.e. in condenser), not in the blockchain itself. Related issue: steemit/condenser#1830

**Comment by iamsmooth** [comment]
Implementing this in UI instead of the blockchain is a terrible idea which displays a high level of ignorance about how markets operate, as well as the primary reasons for a tick size being a good idea. The vast majority of market making and frequent trading, including on Steem, is done by bots which do not use the UI and are not constrained by it. The primary disadvantages of not having a minimum tick size is not UI/UX (which is relatively easy to fix; see below) but that constant outbidding by insignificant amounts certainly results in addition spam on the blockchain and probably results in worse liquidity. 

In fact the far more effective solution is largely the opposite. The blockchain should impose hard constraints to limit spam and poor market dynamics (likely impairing liquidity) due to insignificant price changes whether they are being done by humans or bots (and the latter case by far is more common and more important). 

Finally there is a simpler way to solve this problem that doesn't require completely reworking how the rational-number based market works, nor a new operation: Reject creating an order where the new price is 'too close' to the price of any existing order ('too close' likely defined by a ratio such as 1/1000) without being equal. In the case where a new order matches the price of an existing order, the new order stacks behind the existing order (time priority). Since it is likely necessary to search the existing order book to determine where the new order should be placed, this check should be very inexpensive. The error message can include the required 'nearest' price. 

The UI can hide this by displaying round numbers at increments and rounding to the exact (rational number) price on orders invisibly to the user (the difference between the displayed price and the actual price can be deemed insignificant, or the rounding can always occur in favor of a better price for the user).

**Comment by sneak** [comment]
> Finally there is a simpler way to solve this problem that doesn't require completely reworking how the rational-number based market works, nor a new operation: Reject creating an order where the new price is 'too close' to the price of any existing order ('too close' likely defined by a ratio such as 1/1000) without being equal.

I like this solution a *lot*.

**Comment by mvandeberg** [comment]
One of the AC of this issue states, "For prices involving SMT assets, the base asset must be STEEM."

Limit orders for SMTs are not implemented until #2745, which means this issue is blocked on #2745.
