### ISSUE TITLE
Implement string pooling

### ISSUE THREAD

**Issue by vogel76** [steemit/steem#1595]
Memory allocation could be significantly reduced by introducing string pooling.
This problem has 3 aspects:
1. Token representation of comment contents. It could be much more efficient if each comment text will be tokenized and token numbers be stored as the contents, instead of copied string. This approach needs some dictionary to be established, effectively mapping token text to token object (or at least id) and vice versa. Of course application public APIs still shall return textual form.  
1. strings representing identifiers internally (ie account names). In this case probably simple implementation of string pool could be used (or reused dictionary from previous case)  
1. optional comment text compression in the blockchain operations to reduce size of blockchain. Compression shall be optional, to have backward compatibility to  old 'comment_operation' already present in blockchain.

**Comment by mvandeberg** [comment]
The largest gain I see from this is in permlinks. I am doubtful that we have a lot of json metadata or comment bodies that are duplicated throughout the blockchain.

I propose

```

**Comment by vogel76** [comment]
What is the purpose of the 'hash' member in `string_token_object` ?

**Comment by mvandeberg** [comment]
It makes enforcement of uniqueness easier. We would need a unique index on `(id, data)` for uniqueness and then we would do several string comparisons. We don't really care about sorting the strings, so a quick hash and integer comparisons should be faster. Like I said, because the data is immutable, the hash could be a constant member function (See escrow_object::is_approved) so long as we don't mind computing continually computing hashes of strings.

**Comment by mvandeberg** [comment]
There are currently 13,233,686 permlinks, 13,011,364 of which are unique. With an expected reference count of 1.017, this strategy would not save space.

**Comment by vogel76** [comment]
1. Permlinks are not good example for this usecase - redundancy is possible only when parent_permlink is specified, because (since they are identifiers - all are unique).
1. Most of savings is possible when string pooling/tokenizer will be implemented for comment title/body. Most of words are redundant probably.
1. `string_token_object` is still too complex. String pool needs to hold just strings and offer random access via index, like this:
```
struct RAIndex;
struct UniqueIndex;

typedef multi_index_container<
  std::string,
  indexed_by<
    random_access<tag<RAIndex>>,
    hashed_unique<tag<UniqueIndex>, identity<std::string> >
  >
> string_pool;
```
Even extending this storage to hold also requested `count` (what does not increase the size significantly)  it could be worth.  Of course to be sure whole data shall be examined to build such pool and calculate word redundancy.

**Comment by sneak** [comment]
Wouldn't simply installing the zram module and letting the OS handle memory dedupe (compression) in this fashion be a much simpler solution?

**Comment by vogel76** [comment]
Probably compression of data stored in the steemd memory is not good solution - it could be useful just for subset of informations stored in the objects.
Having tokenized text, what is not complex solution,at word level (trivial) or even sentence level opens new possibilities like full text search on the forum. Reduction of memory usage is just a benefit. 
There are free toolkits responsible for such tokenization also in multilanguage form, ie polyglot project or ICU.
For sure first shall be done simple statistics by using currently collected data, to how much words are redundant,.

**Comment by vogel76** [comment]
Lets gather statistic of word redundancy to check if it is worth.

**Comment by mariusztrela** [comment]
A:   Used memory( input content )           :7 679 469 624 B

 B:   Nr of elements in dict                 :29 552 575 
 C:   Nr of elements in dict * sizeof( key ) :118 210 300 
 D:   Size of elements in dict               :632 620 320 B
 E:   Used memory( C + D )                   :750 830 620 B
 F:   Ratio( A / E  )                        :10.228 
	 

Implementation in `1595-string-pooling' branch.

A - whole data from `comment_content_object::shared_string body`.
B - almost 30 millions words/phrases detected
C - every word is switched to index in dictionary( index has 4 bytes )
D - total size of whole dictionary
E - sum indexes and whole dictionary
F - our gain(!!!)

I suppose, that is worth to introduce tokenizer, because we need 10 less memory than currently.

It is the simplest version of tokenizer, so we don't store chars( , .\\/!?\"()#'$&%+-{} ), which split words.

Further works:

We can detect whole phrases, for example:
" a "
" the "
" is "
". "
and so on.

**Comment by theoreticalbts** [comment]
There are a couple different things here:

- (a) Compression of post bodies in transactions
- (b) Compression of post bodies in memory
- (c) Compression of permlinks

For (a), if we remove the consensus requirement that post bodies are UTF-8, we can simply allow posts to be compressed with a general-purpose compression algorithm like zlib, lzma or [Google Brotli](https://opensource.googleblog.com/2015/09/introducing-brotli-new-compression.html).  This is probably less work, more secure and has a better speed/compression ratio tradeoff than trying to roll our own compression algorithm (which is what the above tokenization scheme amounts to).

For (b), we eventually want to entirely move away from tracking post content in steemd entirely.  Then compression of post bodies is entirely an implementation detail of whatever out-of-process database we implement to store posts.  It's not code that needs to exist in steemd.  Again, I'd advise the folks in charge of this project that if they want to compress posts to reduce memory usage, simply use a general-purpose algorithm.

For (c), permlinks are short enough that general-purpose compression doesn't necessarily get good results.  One possible solution is to simply have consensus nodes track `H(author, permlink)` for some hash function `H()`, instead of `permlink`.  When `(author, permlink)` is used to reference a post, lookup can proceed on `H(author, permlink)`.  `H()` need not be cryptographically strong, and clearly non-cryptographic-grade hash functions have much better performance, but we'd have to address the scenario where a hash collision gets in the chain before the hardfork.

I think it might almost be better to have two hardforks:  The first hardfork to start enforcing uniqueness of `H()`, the second hardfork to apply once we know no duplicates of `H()` got into the chain.

**Comment by mvandeberg** [comment]
Closing, this is not a change we plan to implement any time soon.
