### ISSUE TITLE
Feature Request: The option to make a post or comment anonymous

### ISSUE THREAD

**Issue by febinkk** [steemit/steem#1632]
These anonymous posts/comments can either be ignored while calculating the rewards or all rewards going to these comments/posts may added to the total pool. (I don't know if there will be any difference between the effects of these two implementations on the total rewards)

I know there are methods to create anonymous accounts, but this feature might be necessary in future, when the social/political messages made are against powerful groups. Also it can bring in many advantages to Steemit which the anonymity provides to Reddit.

**Comment by mvandeberg** [comment]
The blockchain already supports this. The blockchain does not require any personally identifiable information to use. Numerous individuals have set up accounts that anyone can use for anonymous use. I don't believe we need a special type of account specifically for this.

**Comment by febinkk** [comment]
The proposal is __not__  for a special kind of account but for special kinds of posts/comments for which there would be no record of the author. The accounts created by the current methods are not anonymous but __pseudonymous__.

The problems with pseudonymous accounts are,

- The moment you identify the person, you can identify all his posts/comments.
- Any hint from one post/comment can exposes the real identity.
- Even a transaction of Steem can be traced back.

The anonymous posts/comments would not have any record of the author. And there wouldn't be any rewards connected to them. Thus the author cannot be identified.

**Comment by mvandeberg** [comment]
If an account has a null authority (no keys, or threshold 0), then it can post without a signature. Yes, there is a name associated with it, but anyone can use it. So it is anonymous. Several users have set up accounts like this in the past. If you are asking for comments that are not even traced on the blockchain, then this is not the repository you are looking for because this is only for things on the blockchain.

The problem with no author being listed on a comment is that we have no way of rate limiting via Steem Power (no account means no Steem Power). It opens up an attack vector against the blockchain.

If there is a reason why the null authority scheme does not work, I would be interested to hear it, but I believe all of the tools yo implement what you want already exist.

**Comment by febinkk** [comment]
Null authority account, works fine.
Still it is just a work around at user level. A much user friendly solution can be created at front-end level. But still the best solution, in my opinion, would be to implement it at the API level. (This API can internally use one, null authority account with high bandwidth or a pool of null authority accounts with normal bandwidths)
