### ISSUE TITLE
Define and implement testing scenarios related to smt_create_operation

### ISSUE THREAD

**Issue by vogel76** [steemit/steem#1653]
Testing scenarios mostly depend on issue and related questions in the comment inside :
https://github.com/steemit/steem/issues/1554

**Comment by vogel76** [comment]
BLOCKED by  issue https://github.com/steemit/steem/issues/1554

**Comment by Kiwonik** [comment]
1. (Positive) Create multiple SMT with the same control account.
   * Use same or different precision (including 0)
2. (Negative) Create SMT with precision too big.
3. (Negative) Create conflicting tokens with
  a) Same NAI and precision.
  b) Same NAI but different precision.
3. (Negative) Hijacked NAI - used to create SMT by different users with
  a) Same precision
  b) Different precision
4. (Positive) Re-launch - after failed ICO the creator tries to reuse previously acquired NAI
   * This scenario is allowed currently by whitepaper "The symbol will remain reserved to the specified control_account. However, in order to launch the token, an smt_create_operation must be issued and the smt_creation_fee must be paid again."
   * Implementing requires that `smt_create_operation` evaluation recognizes the re-launch and reuses existing smt_token_object.
   * What to do with not refunded contributions left over from failed launch?

**Comment by Kiwonik** [comment]
Implemented cases 1 to 5. Number 6 (SMT relaunch) has to wait until launch phase operations are implemented.

**Comment by Kiwonik** [comment]
Additional operations tests (e.g. `set_setup_parameters_apply`) should be modified to use `smt_database_fixture::create_invalid_smt` and `smt_database_fixture::create_smt_3` similarily to `setup_emissions_apply`. This however is blocked by #1738
