### ISSUE TITLE
SMT NAI Questions

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1654]
While looking at the asset serialization, I noticed that the string serialization for the `asset_symbol_type` does not include precision. This means that an asset symbol cannot be serialized on its own without a numeric value.

The decision to use NAIs meant that accounts could now create multiple SMTs assuming they pay a fee for each one, which now requires that all ops related to an SMT include the symbol (NAI). However, the symbol cannot be serialized on its own.

There are several solutions to this problem that we can consider:

1. Only allow one SMT per account. This is a bit of a step backwards, but solves the problem because it removes the need for symbols in ops.

2. Use the asset number as the NAI. The asset number is numerically tied to the NAI via checksum but has the precision embedded. However, this means that `get_next_smt_identifier` only contains part of the information required to calculate the symbol and the result is modifiable by the control account's desired precision. I don't think it is inherently bad, but I think the creation interface should be redesigned so that the user is assigned a deterministically pseudo-random identifier after creation.

3. Require the precision in stand alone serializations. IMO, it would look pretty ugly to see `@@A74BC2 3`, but it works.

**Comment by vogel76** [comment]
1) is bad choice because it blocks potential growth of application because of small implementation detail
2) NAI could be some class having its identifier arbitrary chosen BY BACKEND. Why there is a need to put it into [user] interface at SMT creation if this value cannot be defined by user. User shall see only assigned NAI after smt_create_operation successfully evaluates, and then blockchain smt_create_operation object (in block produced by witness) will have filled by assigned NAI. This also will enable in UI/API further steps to define SMT properties.
Embedding NAI and precision in the asset_symbol_type is good idea since allows fast general ops on assets, without any need to check if symbol points to valid SMT or not until some conversion to other assets will occur.

**Comment by mvandeberg** [comment]
`asset_symbol_type` already has the NAI and precision embedded in the struct. This is the asset num representation.

From a user prospective, they aren't going to choose an NAI. An API will either get the next valid NAI without them knowing, or create an SMT and then retrieve the NAI. It is a black box to them. I think the interface is simpler if the NAI is assigned internally and then retrieved.

Another reason to use the asset num as the NAI is that when an asset is deserialized from a string, a database lookup is needed to determine if the precision matches the asset. If the NAI contains the precision, then this is a stateless validation.

**Comment by mvandeberg** [comment]
The solution we decided upon it twofold:

1. Appended to the NAI serialization will be a hex bit corresponding to the precision of symbol. This will allow symmetric string serialization/deserialization of an asset symbol.

2. To facilitate ease of use of this serialization, `get_next_smt_identifier` will take an integer parameter representing the precision of the SMT and return the NAI with the precision character. That NAI portion of the symbol will still be unique, but it canonizes a specific precision.

Additionally, when deserializing an asset, the precision of the asset should be checked against the precision of the symbol.
