### ISSUE TITLE
_pending_tx inconsistencies

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1657]
I have constructed a scenario that could cause missing transactions with our existing mem pool implementation.

The mem pool is just a vector of transactions in local state. After a block is pushed this vector is cleared and each transaction that was in the vector is pushed to the local state. Those that are successful (i.e. not duplicates and still valid) are placed back in vector and those that are not are discarded either because they are included or invalid based on the current chain state.

This naive approach works for the basic forking scenario. There is latency between block producer A and block producer B. They create the same block num and effectively create the same block. Perhaps the order of transactions is different, but they have the same mem pool, so no matter which block you receive first, you mem pool matches everyone else.

Now, consider the scenario when mem pools are not the same. Let us assume it is caused by network latency. Block producer A produces a block with transaction X. Block producer B has a poor connection with the progenitor of tx X and block producer A and produces a conflicting block without transaction X. Block producer C receives both blocks, but because of how they arrived chooses to build on block producer B's block. However, because C had received A's block, tx X was removed from their mem pool and so block producer producer C does not include tx X. We can assume that by this point A's block has propagated, removing tx X from everybody's mem pool, but because B's block is part of the longest chain, the majority fork does not contain tx X even though it is a legal transaction.

The solution is simple, make the mem pool fork aware.

Almost all of the existing mem pool logic can stay, but when a fork occurs, the mem pool needs to be reset to the pre-fork state. Thankfully, that is trivially done by making the mem pool exist within a multi index container.

**Comment by abitmore** [comment]
Perhaps another scenario (without forking, perhaps off-topic here, if it's the case feel free to move it):
* Assume there is a node N and a client C connected to this node via RPC
* C send a transaction T to N, for example with a `comment_operation` with ID X
* N then broadcast T to the network
* before N got a new block, if C calls `get_comment X` via RPC, the comment object will be returned as if it's included in a block, but actually it's not. **The API doesn't distinguish pending chain state from confirmed chain state. This behavior is wrong.**
* after N got a new block B, if T is not in it, local state of node N will be refreshed,
  * if we get rid of T from local state, when C calls `get_comment X`, `null` will be returned as if the comment has got lost, but probably it's too early to say that, since T can be included in a later block.
  * if we keep T in local state, when C calls `get_comment X`, the comment object will be returned as if it's already included in a block, but actually it's too early to say that, since T can expire eventually for whatever reason.

**Comment by mvandeberg** [comment]
This scenario only applies to `broadcast_transaction_asynchronously`.

Most tooling we use broadcasts synchronously which means the RPC only returns after the transaction has been seen in a block. Either there is a bug in this logic and the transaction has not been seen in a block. As you stated, there is still a chance for the transaction to be included later.

The later is more interesting and is the scenario this issue proposes.

**Comment by abitmore** [comment]
IIRC current implementation of mem pool won't cause transaction loss. When switching to a new fork, all transactions in the old/shorter fork will be popped to mem pool, thus will be tried to be included later.

**Comment by mvandeberg** [comment]
Maybe it is a bug in Steem. All of the transaction are pushed to `_popped_tx` but nothing is ever done with `_popped_tx`.

**Comment by mvandeberg** [comment]
Sorry, that is incorrect. They are handled in the pending transaction restorer.

**Comment by abitmore** [comment]
> Most tooling we use broadcasts synchronously which means the RPC only returns after the transaction has been seen in a block.

As I said in Slack, synchronous doesn't make sense with GUI/web page. After submitted a transaction, when the mouse/UI is spinning, the user may navigate to another page or even another app (block explorer for example) to see whether the transaction has gone through, thus break the synchronous mechanism. If all UI's are showing pending state, the user may incorrectly assume the transaction has been included in a block.

**Comment by abitmore** [comment]
I think it will help if we enable [this logging](https://github.com/steemit/steem/blob/v0.19.2/libraries/chain/database.cpp#L777-L778). If a transaction was in the mem pool but has not been included eventually, there might be something wrong, which will be logged here. Currently only block size issues are [logged](https://github.com/steemit/steem/blob/v0.19.2/libraries/chain/database.cpp#L783).

After the logging is enabled, if still nothing is logged, it means the transaction didn't get into the mem pool, then perhaps there is a p2p propagation issue.

**Comment by abitmore** [comment]
A side note, we need a tool to monitor the mem pool. An API which returns current transactions in the mem pool would help.

**Comment by mvandeberg** [comment]
We log when transactions expire from the mem pool.

**Comment by mvandeberg** [comment]
This API is a quick and dirty method to query the status of a recent transaction so that an app can make intelligent decisions regarding its transactions.

**Comment by theoreticalbts** [comment]
Related:  #486

**Comment by theoreticalbts** [comment]
> The API doesn't distinguish pending chain state from confirmed chain state. This behavior is wrong.

This behavior is not wrong, it follows inevitably from how a blockchain is designed, including Steem / Graphene.  You suggest that `steemd` should maintain two distinct chain states, "pending" and "confirmed," and queries should always occur against the confirmed state.

This is not how `steemd` works.  It only maintains a single state, which under normal circumstances is "pending" so transactions can be immediately checked against state created by other non-included transactions.  So for example if `T_AB` is a transaction where Alice transfers to Bob, and `T_BC` is a transaction where Bob transfers to Charlie, if `T_AB` is submitted to the network and then `T_BC` is submitted to the network before `T_AB` is included in a block, both transactions will propagate.  Likewise if some transaction blocks another transaction, for example `T_AC` is Alice sending to Charlie (and Alice's balance is insufficient to execute both `T_AB` and `T_AC`), then a node which has broadcast one of `{T_AB, T_AC}` should not allow the other transaction in the set to propagate.

**Comment by theoreticalbts** [comment]
> But with that log we still don't know why it's expired.

There's basically only one "why" a transaction can expire -- because the transaction hasn't appeared in any block yet, and the local node's accepted a block after the transaction's expiration time.

Why it wasn't included is only a question that each witness that produced a block after the transaction was submitted can answer.  Possible causes are:

- The witness didn't receive the transaction
- The witness received the transaction and was unable to push it because some other transactions the witness received made it invalid (think about `T_AB, T_AC` double spend example above)
- The block was full

**Comment by abitmore** [comment]
> So for example if T_AB is a transaction where Alice transfers to Bob, and T_BC is a transaction where Bob transfers to Charlie, if T_AB is submitted to the network and then T_BC is submitted to the network before T_AB is included in a block, both transactions will propagate. 

This is true but is not guaranteed. Due to network conditions, T_BC may or may not propagate.

In case when T_AB can fail, propagation of T_BC is not always a good thing.

Returning pending state by default does more harm than good for UX.

> Likewise if some transaction blocks another transaction, for example T_AC is Alice sending to Charlie (and Alice's balance is insufficient to execute both T_AB and T_AC), then a node which has broadcast one of {T_AB, T_AC} should not allow the other transaction in the set to propagate.

It makes sense if A wants to replace a pending `T_AB` with `T_AC`. Steem and BitShares lack of a priority setting for pending transactions which exists in other blockchain systems like fees.

IMHO a node should allow both `T_AB` and `T_AC` for all valid possibilities. It should also allow `T_BC` if there is a `T_AB`, no matter if there is a `T_AC`. But perhaps this is a bit hard to implement with current design.

**Comment by theoreticalbts** [comment]
> Returning pending state by default does more harm than good for UX

This may be true, but the architecture of Steem would need to be substantially redesigned in order to permit a given instance of steemd to have more than one state instance.

>  if A wants to replace a pending T_AB with T_AC

Transaction replacement has never been a goal of Steem.  It's subject to all kinds of abuse.

> a node should allow both T_AB and T_AC for all valid possibilities

Huh?  This makes no sense.  If Alice has 1000 Steem in her balance and sends 1000 Steem to Bob, under no circumstances should she *also* be allowed to send 1000 Steem to Charlie.  `T_AB` and `T_AC` *cannot* both be applied to the same state, or you have just allowed Alice to print 1000 Steem by sending the same 1000 Steem to two of her friends.

**Comment by abitmore** [comment]
It makes sense that keeping a pending state is better for transaction propagation and block producing. But some UI better to be served from confirmed state. How about running two nodes/services at same time?
