### ISSUE TITLE
Implement SMT transfers

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1682]
The existing `transfer_operation` must be extended to support SMT's.

- [x] Allow SMT usage to `void transfer_operation::validate() const`

- [x] Extend `database::get_balance` to read balance from correct place (see #1642)

- [x] Extend `database::adjust_balance`

**Comment by vogel76** [comment]
@youkaicountry Does `escrow_transfer_operation` shall also support SMT transfers ?

**Comment by youkaicountry** [comment]
@vogel76 We currently have no plans to extend SMT support to `escrow_transfer_operation`. It's pretty much unused, without even UI support.

**Comment by vogel76** [comment]
@youkaicountry Does SMT assets shall be also stored for given account on:
- savings_balance,
- reward_steem_balance
?

**Comment by youkaicountry** [comment]
@vogel76 There will be no `savings_balance` for SMTs.
`reward_steem_balance` will have an SMT equivalent, there will be an issue created for it in the future.
This issue is only related to extending `transfer_operation` to support SMTs.
With the minimum amount of infrastructure possible, the operaton should be able to accept SMTs for transfer, and then transfer the balance."

**Comment by vogel76** [comment]
@youkaicountry This is very important information that `reward_steem_balance` will hold SMTs too, since it will impact #1642 - we need to be able to choose correct index to store/retrieve assets for given account or appropriately define index key to distinguish use context (regular-balance, rewards-balance). Any proposal for such solution ?

**Comment by theoreticalbts** [comment]
An account has two fields called `balance` and `reward_steem_balance`.  They both represent STEEM owned by the account, but they are different "balance types".

We have two basic options:

# Option 1: Balance types in separate objects

- The two types go in different objects, for example `account_balance_object` and `reward_balance_object`.
- Each object type is indexed by `(account, symbol)`.

# Option 2: Balance types distinguished by enum

- Both balance types are represented by `balance_object`
- Add a new integer (or `enum`) field to `balance_object` identifying which balance type it is
- The `balance_object` is indexed by `(account, symbol, balance_type)`

There are competing long-term concerns here.  Option 1 is a better fit for modular blockchain, but Option 2 allows code to be deduplicated and allows generic API's for working with balances.

I suggest going with Option 2.  My reasoning:  Option 2 gives more immediate benefits, and if we ever decide to implement Option 1 in the future, it will be a fairly straightforward refactoring from code that uses Option 2.  But I think Option 2 code would be harder to retrofit onto Option 1 code.

**Comment by Kiwonik** [comment]
@youkaicountry Would methods like `database::validate_invariants` or `database::clear_null_account_balance` also need upgrading with SMT support? I mean not in the scope of this issue, but eventually.

**Comment by Kiwonik** [comment]
@youkaicountry I can see now that at least `database::validate_invariants` has already been addressed in #1648
