### ISSUE TITLE
Incorrect authority type for update_account_auth_key CLI command treated as owner

### ISSUE THREAD

**Issue by arhag** [steemit/steem#172]
Apparently, if someone uses a string other than `owner`, `active`, or `posting` for the authority type argument of the ` update_account_auth_key` CLI command, it will silently treat the authority type as if it was `owner`.

**Comment by mvandeberg** [comment]
Hmm... Can definitely change the implementation to prevent this, but it seems like a bad decision on how FC serializes enums. If the string isn't in the enum, it should fail deserialization, imo.

**Comment by arhag** [comment]
> If the string isn't in the enum, it should fail deserialization, imo.

That is the behavior I would expect for all commands in cli_wallet.

**Comment by jcalfee** [comment]
While investigating, you might want to block this case and tell the user to use `update_account_memo_key` instead.

**Comment by theoreticalbts** [comment]
Fixed, merged.

**Comment by theoreticalbts** [comment]
The problem was that FC was using `atoi()` which has undefined behavior if the input doesn't parse as a number. I changed FC to use `boost::lexical_cast` instead and change the exception. Now enums know how to deserialize from integer values in the enum, string names in the enum, and decimal string values in the enum.  Deserializing a value which does not exist in the enum now always throws.
