### ISSUE TITLE
The problem of atomic SMT creation

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1795]
It is my understanding that, while an old version of the spec only allowed a single SMT per control account, the current intent is to allow multiple SMT's with the same control account.

If we have a single SMT per control account, this issue is *irrelevant*.

The basic problem here is that, since we will implement a stateful check that only allows a small set of "random-looking" NAI's to be usable at a time, it may be likely for two accounts to attempt to create an SMT with the same NAI at the same time.

The semantics of this are perfectly well-defined:  The first transaction to be included by a witness wins.  Where the difficulty comes in is if the chain forks.

Here's an example:

- Block `100` occurs.
- `T1`:  Alice creates asset `a1` with ID `x`
- `T2`:  Bob creates asset `a2` with ID `x`
- Block `101a` includes `T2`.
- Alice sees that ID `x` was consumed by someone else, so Alice creates
- `T3`:  Alice creates asset `a3` with ID `y`
- As it turns out, block `101a` is on a dead fork.
- A different block `101b` (or its descendants) include both `T1` and `T3`
- Now Alice has paid the asset creation fee twice and created two assets -- not what she intended!

The problem here is that transactions `T1` and `T3` must be made *mutually exclusive*, i.e. they both cannot occur.

**Comment by theoreticalbts** [comment]
So there are several possible solutions to this problem:

- Add a field to the `smt_create_operation` requiring the first transaction #1797
- Implement a generic mutual exclusion primitive #1798
- Split up the claiming of an NAI and the creation of an SMT into separate operations #1777
- Use a comment to provide mutual exclusion (already supported, discussed in #1798)
- Use TaPoS to provide atomicity (already supported, dicussed in #1796)

Let's discuss the best approach.

**Comment by mvandeberg** [comment]
Keep in mind that this scenario is extremely rare.

We created a pool of valid NAIs. Because NAIs are all created equally (or at least designed to all be equal) Alice and Bob should both choose random NAIs. If there is a pool of 128 NAIs to choose from, then the chances of Alice and Bob both choosing the same NAI in the same block is 1/128. If and only if this occurs is the above scenario even a possibility.

These solutions break into two categories. Those that can be used to prevent the above scenario and those that must be used and prevent the scenario.

The intent behind the SMT creation fee is that it is enough to disincentive spam creation of SMTs but low enough that any legitimate creator is not under significant financial burden to create an SMT. With that in mind, the worst case scenario of spending twice as much to create an SMT should not be anywhere close to the end of the world for an SMT creator. The worst part of this is the unintentional memory use of the accidental SMT.

This being said, I am favor of using TaPoS to provide atomicity because it already exists on chain. The downside to the solution is that it requires external tooling to enforce. There are many useful tools already a part of Steem that few users/applications are using. Either because they don't know it exists or the tooling doesn't exist. While it is tempting to design a system for this problem that prevents this scenario, we lose a layer of abstraction that should be used. Long term, I prefer education around these primitives and tooling to make their use easier over many solutions to specific problems.

**Comment by youkaicountry** [comment]
- Add a field to the `smt_create_operation` requiring the first transaction #1797
 We should avoid this solution, adding new fields that we will have to support should be done very carefully.

- Implement a generic mutual exclusion primitive #1798
 This would be the most 'elegant' solution, and would be nice to have, but it's hard to justify spending the developer resources on it at the moment when there are other valid solutions.

- Split up the claiming of an NAI and the creation of an SMT into separate operations #1777
  Since there are solutions that don't break up the creation process, we should consider those first.

- Use TaPoS to provide atomicity (already supported, dicussed in #1796)
  I agree that this is the solution to the problem we should pursue, since we already have the infrastructure in place.

**Comment by youkaicountry** [comment]
The decision was to use TaPoS to provide atomicity as discussed in #1796
