### ISSUE TITLE
Add allowed_vote_assets to comment options extensions.

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#1843]
In order to determine which assets can be used in voting for a comment, `allowed_vote_assets` struct should be added as a `comment_options_extension`.

As outlined in the whitepaper, `votable_asset_info_v1` will also need to be defined.

**Comment by vogel76** [comment]
@youkaicountry My questions:

1. Who and when can define such votable assets per comment ?
1. Non-existing `allowed_vote_assets` means that all tokens can be used by voters ?
1. How assets are identified in `allowed_vote_assets` - votable_assets map associates acount_name to votable_asset_info_v1, but given account can have defined mutiple SMT tokens

**Comment by youkaicountry** [comment]
@vogel76 
Right now we simply want the structures in place.

1. The user selects which of the assets they are holding can be used for voting.

2. Non-existing allowed_vote_assets should mean that only STEEM can be used for voting. There will be a maximum of three tokens allowed per comment, one of which must always be STEEM. There is an ongoing discussion to decide whether it should actually be listed as one of the vote assets, or assumed to be there #1844. For this ticket, it shouldn't matter, as validation and unit tests will be in seperate tickets. This is only for defining the structures.

3. I see the confusion, this may be a holdover from when there was only one SMT per account. I will consult with @theoreticalbts to clarify this.

**Comment by theoreticalbts** [comment]
Yeah, that's a holdover.  It should be `map< asset_symbol_type, votable_asset_info >`.

**Comment by vogel76** [comment]
@youkaicountry SMT spec says that there can be at most 2 tokens specified in `votable_assets`. Because of that, maybe it is better to rethink `allowed_vote_assets` definition and replace map with pure array. Undefined array entry could be recognized by empty asset_symbol_type object and whole definition could look as follows:
```
struct votable_asset_info
{
  asset_symbol_type asset_symbol; 
  share_type max_accepted_payout    = 0;
   bool allow_curation_rewards = false;
};
struct allowed_vote_assets
{
   std::array<votable_asset_info, 2>  votable_assets;
};
``` 
Such definition could reduce memory usage.

**Comment by mvandeberg** [comment]
I am strongly against a fixed sized data structure in this operation.

We have made many changes to Steem since launch. If the data structure is fixed size, then in order to increase the number of votable assets, we would need to create a different `allowed_vote_assets` struct to go in the static_variant that supported a different number of votable assets. Not only is it tedious from an implementation perspective, it makes very little sense for a third party developer. I think it is worth having a dynamically sized data structure to have the option of changing how many votable assets are allowed in the future.

**Comment by theoreticalbts** [comment]
Yeah, we want to use a variable-sized data structure for the reasons outlined above -- if we ever want to change it in the future, changing it is harder if we use a hardcoded fixed-size structure.  It's even harder to change if the size is an implicit value that's never transmitted on the wire.

**Comment by vogel76** [comment]
Sure I understand benefits of dynamic container and drawbacks of static one. I didn't have in mind to harcode the size (just have it preconfigured by constant). Anyway my intention was to limit mem. usage especially that map element is small. Having dyn. container with so limited number of items just leads to allocating more memory for the container structs than for held data itself. 
Of course it was just some thought and it will be coded as originally planned.

**Comment by vogel76** [comment]
Issue done in PR:
https://github.com/steemit/steem/pull/1858
