### ISSUE TITLE
Modify vote_operation evaluator to use votable assets

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#1856]
Voting will use every votable token the voter holds, instead of just STEEM as it is now. 

The voting user's tokens should be compared to `allowed_vote_assets`, and any asset the voting user has that is in `allowed_vote_assets` will be used for the vote.

**Comment by vogel76** [comment]
1. What should happen if user does not have any token specified in `allowed_vote_assets`:

- STEEM shall be used to reward comment - what if user has insufficient balance of STEEM ?

- Exception shall be thrown to disallow voting

1. Does it is correct that user will implicitly pay 2 times (assuming the comment has defined 2 votable tokens). Maybe there shall be possible choice to allow user to decide which token use for voting.

**Comment by mvandeberg** [comment]
Voting does not consume tokens. It consumes an automatically regenerating resource called voting power. Please refer to the Steem white paper on how voting works and read the existing vote_evaluator. That should answer your questions with regards to SMTs.

**Comment by vogel76** [comment]
@mvandeberg Thanks for pointing docs. I got to know general rule of voting, but still have one question - if voter does not have any of votable tokens, its vote shall be evaluated as regular vote associated to STEEM ?

**Comment by youkaicountry** [comment]
@vogel76 That is correct, STEEM will always be implicitly assumed to be one of the votable tokens, even though it won't be included in `allowed_vote_assets`

**Comment by Kiwonik** [comment]
@mvandeberg @youkaicountry At an early point in `vote_evaluator::do_apply` voter's vesting balance is acquired using a call to `account_object::effective_vesting_shares`. This vesting balance is then processed in following huge chunk of `vote_evaluator::do_apply` body. My understanding is that:
1. What is being done with (STEEM) vesting balance there should be repeated for every SMT vesting balance that a) can be found in comment's `allowed_vote_assets` **and** b) can be found among voter's balances.
2. These should be all treated separately and not mixed.

If this is correct, that huge chunk of `vote_evaluator::do_apply` should be separated and refactored the way that allows processing of any asset's vesting balance so that it can be used as many times as there are appropriate SMTs plus default processing of STEEM as explained in earlier comments of this issue. This should be the first stage of this issue implementation. Please confirm or correct my assumptions.

**Comment by Kiwonik** [comment]
@mvandeberg @youkaicountry Another thing is that if SMT vesting balances are required to implement this issue (as I described in previous comment) then they should be implemented in the first place, e.g. issue https://github.com/steemit/steem/issues/2021 is a prerequisite for this one.

**Comment by youkaicountry** [comment]
@Kiwonik Your assumptions seem correct, and SMT vesting will definitely have to be done as a prerequisite. I'm adding it to the current sprint since it is directly required / related.

**Comment by Kiwonik** [comment]
@youkaicountry After some digging in steem vesting code I believe that `database::create_vesting` should be modified to support SMT vesting so that SMT vesting balance could be properly created before it can be used in this issue implementation. 
However I'm not sure that `create_vesting` should be used in unit tests of this issue (so far it's not been called in unit tests). Maybe it'd be better if `transfer_to_vesting_operation` is modified to support SMT vesting first, as it's evaluator uses `create_vesting`. Then the unit tests of this voting operation issue could start with issuing a `transfer_to_vesting_operation` that creates user SMT vesting balance properly, so that it can be used to test voting with it in following steps of the test.

Therefore I propose that another new issue is created as a prerequisite to this one - **Modify transfer_to_vesting_operation to support SMT vesting** in which scope `database::create_vesting` is modified to support SMT vesting. That new issue would replace this one in current sprint to avoid the sprint bloat. I'd guess that neither @mvandeberg nor @goldibex would mind.

**Comment by youkaicountry** [comment]
Okay, I will create a new issue for this.

**Comment by mvandeberg** [comment]
#2021 is done. Is this still blocked?

**Comment by Kiwonik** [comment]
Yes it is.  Per my last comment above this issue should be preceded by other tasks if only to allow to write correct unit test.

**Comment by youkaicountry** [comment]
This has been replaced by #2160 in the sprint, to allow work to continue.

**Comment by Kiwonik** [comment]
@theoreticalbts
Now that we have separate `STEEM_MIN_VOTE_INTERVAL_SEC` and `SMT_MIN_VOTE_INTERVAL_SEC` and allow several votable assets in one vote it must be clarified how different intervals should be treated.
1. Should `account_object::last_vote_time` be changed into a map holding separate last voting time for every token ever used in voting? So that we can check that each votable asset's interval expired.
2. Should `SMT_MIN_VOTE_INTERVAL_SEC` be removed and steem interval be used for both steem and SMTs?
3. Any other solution.

I prefer 2, because 1 introduces complexity and performance burden for purpose I can't clearly see.

**Comment by Kiwonik** [comment]
@theoreticalbts @mvandeberg @youkaicountry 

Due to SMT voting process using separate S(TEEM/MT) Power for every votable token, several fields of `comment_object` and `comment_vote_object` have to be multiplied by number of votable tokens. These are `net_rshares`, `abs_rshares`, `vote_rshares` & `rshares`, `weight` respectively.

I believe this change, touching the data structure objects is outside the scope of this issue, but can be done after this issue is completed, fortunately. So I'm going to develop this issue up to the point where the new one can be started, and then make a PR after which the structural changes can be made.

**Comment by Kiwonik** [comment]
@youkaicountry 
I've found one more SMT related thing completely missing in code or even whitepaper - the SMT equivalent of database::get_reward_fund. This will be another separate issue to be implemented after this one is complete, before voting with SMT can be actually tested.
