### ISSUE TITLE
Market order matching doesn't always start at top of book

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#1885]
While writing a comment for #1683, I looked carefully at `apply_order()` and I think there may be a bug in it.  If Alice has an existing order and Bob is creating a new order, there's a finite price that's the worst price Bob will accept, and an infinite price that represents the direction of "more favorable to Bob."  The code *starts* at the finite price, then iterates *toward* the infinite price.  Consequence is, if Alice, Amy and Anna all have existing orders that overlap with Bob's new order, then Bob should choose the one that's giving the *best price* (where best/worst price are defined from Bob's point of view).  The code actually gives Bob the *worst price orders* of the matching orders.

What *should actually happen* is starting at the infinite price and moving toward the finite price.

This is a hardforking change that needs to be confirmed by a unit test.

**Comment by mvandeberg** [comment]
My reading of the code indicates that what you are describing _should_ happen _is_ what happens.

``` c++
auto max_price = ~new_order_object.sell_price;
auto limit_itr = limit_price_idx.lower_bound(max_price.max());
auto limit_end = limit_price_idx.upper_bound(max_price);
```

`limit_itr` starts at the infinite price. `limit_end` points to the end of the list, or the first order with a worse price than Bob is willing to accept. This iteration starts at the infinite price and moves towards the finite price.

I find it unlikely that this is wrong because it is the same limit order matching algorithm that Bitshares uses.

https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/db_market.cpp#L260-L262

There are already some extensive limit order tests, but with a quick reading of the tests, I am not sure if any of them test this scenario exactly. It has been almost two years since I looked at the tests.

**Comment by theoreticalbts** [comment]
I'm a bit confused.

I think the code's actually right, and I made a couple mistakes when I decided this might be an issue, first of all I didn't notice [this comparator specification](https://github.com/steemit/steem/blob/da8f6210f4143a79cec7829811cccf42125cb074/libraries/chain/include/steem/chain/steem_objects.hpp#L289) which says the container should be sorted in *reverse order* of `price`.

Second, I wrote some debugging code to help try to understand how this code works, the debugging code prints out `max_price` followed by `max_price.max()`, then prints out `limit_itr` followed by `limit_end`.  So it is very easy to assume, looking at the debugging code output, that `limit_itr` is initialized from `max_price`, and `limit_end` is initialized from `max_price.max()`, but in the actual code they are in reverse order.
