### ISSUE TITLE
Automatically Scale Shared Memory File

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#1891]
We should add parameters to define the behavior for automatically scaling the shared memory file.

I propose the following:

We define two config variables, 

`shared-file-fill-threshold`: A uint16_t percentage (0-10000) that defines how full the file can get before scaling it.
`shared-file-scale-rate`: A uint16_t percentage (0-10000) that define how quickly the file can scale up when the fill threshold is met.

We should add a method to chainbase called, `resize( uint64_t new_file_size )` that will close the database, resize it, and open it, restoring internal references in the process.

The tricky part here is that all undo states have pointers to mapped pages which can potentially become invalidated after the file is resized. Because of this, no undo sessions can exist. Undo states, that live in the shared memory file can exist and will persist because they live within the mapped segment. Chainbase will need to track active undo sessions and fast fail resizing if an undo session exists. It is responsibility of Steem to ensure it has no active undo sessions when resizing.

The end of `_push_block` is a safe place to perform this check. Pending transactions are not a part of state and the `_pending_tx_session` is invalid because `_push_block` is within a `without_pending_transactions` block. Resizing here should be safe and will still restore pending transactions successfully on return from `push_block`.

We also need to check for resizing while reindexing. This can be performed after each `apply_block`. 

While should move `check_free_memory` to these locations as well and combine it with the threshold check. The result of the function is resizing, or displaying a log message.

Boost Reference:

http://www.boost.org/doc/libs/1_63_0/doc/html/interprocess/managed_memory_segments.html#interprocess.managed_memory_segments.managed_memory_segment_advanced_features.growing_managed_memory

**Comment by theoreticalbts** [comment]
It is not sufficient to just pop transactions.  We need to pop non-irreversible blocks as well.  Basically it needs to go through the same process that's used on clean shutdown.

If you just pop transactions, and then shut down, and then it starts up and discovers it's on a minority fork and needs to pop some blocks, it can't because when you switched files, you threw away the undo state that would let it rewind.

So the proper solution here is to pop non-irreversible blocks, copy the data to the new file, switch over, then re-apply the blocks.  If you do it this way, you'll re-create an undo state that allows the blocks to be popped, and the node will behave properly if it wakes up and finds it's on a minority fork.

Also, copying the file will not be a quick process, if a witness does it, he/she will probably miss blocks.  So maybe the witness plugin should suppress scaling if it's recently produced a block.  If you're a witness, you could still take advantage of the functionality if you just run two nodes with different block production keys, and update your current block production key to switch between them once a week.

**Comment by mvandeberg** [comment]
References to irreversible blocks are stored entirely within the memory segment. We do not pop reversible blocks on shutdown, but start up. The mapped segment is fully capable of starting directly where it left off. If we could guarantee clean shutdown, then we would not pop those blocks. We only do that because we do not know why the node shut down and assume it was due to a problem. We can guarantee a clean shut down.

Growing the file happens entirely in a boost function. Steemd will not shut down during this process. There is no copying of the file.

**Comment by mvandeberg** [comment]
> maybe the witness plugin should suppress scaling

I did not mention this, but setting either of the config options to 0 will disable automatic resizing.

**Comment by mvandeberg** [comment]
These commits have the related chainbase changes.

**Comment by mvandeberg** [comment]
On initial testing, resizing during a sync works.
