### ISSUE TITLE
Decide SMT serialization specification

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#1892]
Current SMT asset serialization is broken, and needs to be fixed / rewritten. A decision should be reached on the specification of the new asset serialization.

Previous discussion in #1888

**Comment by youkaicountry** [comment]
@theoreticalbts proposed the following in #1888:

- The number will consist of 8 decimal digits that specify the `asset_num`, followed by a single hex digit that specifies the precision, followed by a check digit.
- The check digit will be computed by converting the 8-digit integer to a 9-digit integer by expanding the hex digit to two decimal digits (0-9 -> 00-09, a -> 10, b -> 11, c -> 12).
- Some of the check digit code may need to be changed to handle 9 digits.
- Keep in mind that a 10-digit integer will not fit in `uint32_t`.

The current code's intended to implement this regular expression in [Python syntax](https://docs.python.org/3/library/re.html#regular-expression-syntax):

```
\s*@@[0-9]{9}\s*\0
```

According to the discussion from #1654 this regular expression is modified to be:

```
\s*@@([0-9]{8})([0-9a-f])([0-9])\s*\0
```

The three groups are the asset_num, precision and check digit.

**Comment by mvandeberg** [comment]
#1937 simplifies this somewhat.

It is going to return the asset as a tuple or a struct rather than a string with satoshi value, precision, and nai explicitly stated.

The only real decision that needs to be made here is if the NAI representation is sufficient. I am fairly certain it is because the addition of a vesting bit or not would likely happen in the assent_num, not the nai.

The serialization code I am writing will be agnostic of the implementation of the nar. So long as converting and asset symbol to and and from a precision nai pair, then we're good.
