### ISSUE TITLE
Create claim_reward_balance2_operation

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#1896]
The original `claim_reward_balance_operation` had no extensions field, and does not fit our specification, so we will create a new operation. Discussion in #1859

`claim_reward_balance2_operation` should contain an extensions field, and it should accept a vector of tokens that will be rewarded to an account.

- It should be able to store STEEM/SBDs/VESTS as well as SMTs.
- Multiple assets of the same symbol should be disallowed

**Comment by vogel76** [comment]
1. Does the new operation shall store only SMT related assets or also STEEM and SBDs ?
1. Does it is allowed to store multiple assets of the same symbol ?

**Comment by youkaicountry** [comment]
(1) It should be able to store STEEM and SBDs as well. 
(2) I don't see any reason it should be able to store assets of the same symbol, so that is something we should disallow

**Comment by mvandeberg** [comment]
(1) And VESTS

Duplicate assets would not make sense in the operation, so it should be disallowed.

**Comment by mvandeberg** [comment]
I would suggest using a flat_set to sort assets, but comparing assets with different symbols is not allowed. This is generally a good thing because we do not want to succeed transferring 10 CATCOINS from Alice's 5 DOGCOIN balance because the CATCOIN symbol ends up being greater than 5 DOGCOINS.

We could create a `comparable_asset` class with different operators and an explicit conversion to and from asset to be careful how we use it.

This way assets will be ordered by asset symbol and can be guaranteed unique.
