### ISSUE TITLE
Decision on how we can avoid SMT vesting

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#1909]
It would be good if we could avoid the complexity of having SMT/vesting token pairs. A decision on if it's possible, and if so, how best to handle voting power needs to be reached.

**Comment by mvandeberg** [comment]
One of the big benefits of vesting balances with respect to Steem's reward structure is that it prevents sharing of stake between accounts. We go to great lengths with vesting delegations to prevent double voting on content. However, with a vesting balance for each SMT, withdrawals, and routes, the whole system gets quite complex.

The idea was proposed to me that instead of using stake under control of the user at the time of the vote, we use stake of the user one week ago. That avoids double voting with stake, is relatively simple to understand, but is very expensive to implement. Because we need instant lookup of the balance exactly 7 days ago, we would need to keep balance history in consensus for 7 days, on each account, for every SMT. That is trivially attacked via 1 satoshi transfers and transfer of tokens should be one of our cheapest ops for bandwidth. With this system in place we would need to make transfers costly in terms of bandwidth which is a non-starter from a UX perspective. The system in theory is good, but in practice is bad.

I propose we have a moving average of stake. The implementation is quite simple and should capture identical mathematics over the long term.

For every balance, we have a `moving_balance` field which represents their effective stake and a time point for the last update of the moving balance.

Immediately before the balance is updated, we update the moving balance linearly toward the current balance over a 7 day period.

Whenever we need to calculate effective stake for voting, we can linearly interpolate the effective balance as `(effective_balance + (current_balance - effective_balance)/(head_block_time - last_effective_balance_update)`.

The draw back of this system is that when there are frequent but small changes to balance, the accuracy degrades due to the linear update. However, if the updates are small, then the percent inaccuracy of a vote when calculating stake are also small.

It is worth noting that this is easily exploited by sending 1 satoshi transfers to a user you do not wish to have their full effective stake.

**Comment by mvandeberg** [comment]
We could delay updating the moving balance unless the change to the actual balance is greater than a certain percentage of the moving balance. I think there would exist some simple heuristic we can use to at least protect against such balance harassment.

**Comment by roadscape** [comment]
What if each vote locks up a fraction of the balance until payout? i.e. each vote effectively forces a 7-day lockup. The voting power for an account's SMT balance is the % not locked up. Vote power regenerates as payouts occur.

**Comment by theoreticalbts** [comment]
Vesting serves some important economic functions:

- Prevents early backers of the coin from dumping as soon as it starts to gain traction.
- If the token devs get some tokens in the ICO to use for development, having those tokens vesting incentivizes the devs to support the ecosystem, at least for a while.  Vesting makes it harder for an ethically challenged dev to line their pockets by immediately selling the tokens they were issued in the ICO, then abandoning the project.
- It literally pays a portion of the userbase to think of themselves as long-term backers of an ecosystem, rather than short-term price speculators.

Basically vesting solves a collective action / prisoner's dilemma problem.  If there's a bunch of new demand, it's better (more total gains) and fairer (gains more equally distributed) for all holders if they all sell into it slowly.  But any single holder can sell quickly, taking more than their "fair share" of the new demand and lowering the price for everyone else.

**Comment by sneak** [comment]
All of those concepts are good; however we are building a product for the mass market. Doubling the balances shown, the elements on screen, every token actually being two tokens: this is all complexity that will hinder adoption.

If we can solve the double voting problem, we should avoid the complexity of every SMT that can earn post rewards requiring a second token. Even the best UI in the world can’t present that as simply as a single token balance.

**Comment by theoreticalbts** [comment]
### Who are our users?

There are three classes of users:

- (1) Ordinary users who just want to post and vote.
- (2) Developers or other backers who get a portion of the ICO or are given tokens by the token's sponsor.
- (3) Users who decide to lock up their tokens for the long term in order to earn a return on their vesting balance. 

The additional requirements I outlined in my last post are important for the economic functioning of the coin, and will involve a separate vesting balance.  However, this analysis shows that *the vesting functionality is only needed by user types (2) and (3)*.

If we can solve the needs of user class (1) without a separate vesting balance, there is a good UI solution:  provide a simplified view with the vesting related functions hidden, 95% of our userbase are class (1) users and can do all their activities with that default.  We still have to support class (2) and (3) users, because while few in number, they will probably have a lot of the stake for many SMT's and are important to the economic functioning of the SMT.  So to support those users, simply have an option somewhere to turn on an advanced view that provides access to vesting related functions.  (Or perhaps make it appear automatically if the user has vesting tokens.)

**Comment by theoreticalbts** [comment]
OK, so the next question is, how do we solve the voting problem?

Let's imagine the following "micro-physics:"  A lump of tokens "charges" with "votes" over time. 
 So 1000 tokens contains 1000 votes when fully charged.  When upvoting a post, some number of votes "discharges" (are turned into rshares), let's say 50 rshares, 1000 tokens and 950 votes.

When Steem moves by any means -- being transferred, being placed into a market order, etc. -- the amount of votes it contains is conserved.

Now some implementation details:

- Charge is tracked as a `share_type` with the same unit as tokens, not a percentage level
- To optimize implementation, charging of votes is computed lazily only when balance changes (similar to SBD interest)
- To simplify implementation, only user balances and vesting balances can charge / discharge, everything else maintains a constant charge level.
- Newly created tokens are fully charged.
- Calculation of vesting balance's charge depends on both inflow of newly created, fully charged tokens and recharging of discharged tokens
- When tokens leave an account, fully charged tokens leave first.
- When tokens leave an account, they are discharged.

So for example suppose Alice and Bob each have 1000 tokens with 500 votes.  Then Alice transfers Bob 600 tokens.  After the transfer, Alice has 400 tokens and 0 votes; Bob has 1600 tokens and 500 votes.

These rules are designed to enforce another requirement, namely that users may be restricted to only use a fraction of their tokens to upvote a single post.  Say users are only allowed to use 5% of their votes to upvote a single post.  Alice (normal user) makes a post, Bob (normal user) upvotes Alice, and Eve (attacker) makes a post and upvotes her own post (possibly using a sock puppet account).  Bob and Eve each have 1000 tokens.

Bob can legitimately use 50 votes on Alice's post.  Eve can create a large number of sock puppet accounts, then have each sock puppet vote and transfer all 1000 tokens to the next puppet.  If the tokens maintained their charge when transferred, Eve would be able to immediately use all 1000 of her votes on Alice's post, while Bob would be forced to spread out 1000 votes over 20 different posts.

But tokens lose charge when transferred.  Eve can still attempt the sock puppet cycling attack.  If the time it takes to charge from 0% to 100% is `k` payout cycles in length, then Eve can only amplify her votes by a factor of `1/k` as many votes as Alice.  If `k >= 1` the optimal strategy for Eve is to cycle through a single sock puppet, meaning Eve will upvote, transfer her tokens to a sock puppet, wait until the end of the payout cycle, and then upvote with the sock puppet, giving her 2x as many votes as Alice if it regenerated 100% (`k = 1`).  But Eve pays a steep cost:  In order to vote twice for herself with the sock cycling attack, Eve gave up the ability to vote for 19 other posts.

**Comment by nedsteem** [comment]
I’m strongly towards keeping Power/Vesting/Locked Periods — for its time delay security if not it’s gamification. That said the concept of "Vests" as a % of a coins locked coins is something I’d do away with. Simply locked and unlocked is much better. @theoreticalbts does this fit with your proposal?

**Comment by theoreticalbts** [comment]
Yes.

In spirit, my proposal simply says that tokens which come into your account from any source will be vote-locked for a time (i.e. they temporarily don't count toward your votes, but you can still use them for other actions like transfers, market orders, etc.).

In practice, there are some implementation details.  If we had to track particular lumps of tokens that become unlocked with particular dates, there would be a lot of resource usage, code and UI / conceptual complexity.  So instead, we can just treat each user's vote-locked tokens as a single "mass" that converts to vote-unlocked tokens at a rate proportional to total balance.

**Comment by theoreticalbts** [comment]
I should add that in my proposal, we would also continue to provide STEEM-style vesting as well as vote-locking.  90% of users ("ordinary users") don't need to worry about STEEM-style vesting, allowing us to hide the UI for it and greatly simplify the user experience.  But coin developers can still make their own tokens initially non-transferrable, and gradually unlock over a months- or years-long timescale.  Which gives the developers an incentive to help grow the ecosystem they've created, at least in the short term.  (And since the time release is enforced by the blockchain, ICO contributers will have confidence that it will be followed.)

**Comment by nedsteem** [comment]
To clarify, there’s no “time-delay protection” in this system to protect users who get hacked?

**Comment by theoreticalbts** [comment]
> “time-delay protection” in this system to protect users who get hacked

Providing time-delay protection to hacked users is not the purpose of either of the functions being discussed in this ticket.  That kind of "time-delay protection" is the function of the savings balance.  AFAIK the plan is not to implement savings balances for SMT's before launch, and perhaps not at all.  The main reason is because we built that functionality for STEEM, but few people use it.

Maybe we should revisit that decision; I'll make a separate ticket for it.

**Comment by nedsteem** [comment]
This is wrong. Power/Vesting is a key part of *time delays for protection*. And it’s key for the UX of that.

**Comment by sneak** [comment]
@theoreticalbts The plan is to build the most attractive product for the customer segments that SMTs target. The various resulting featuresets of the entire stack are what we are discussing here. Savings balances are a way of doing that. Vesting tokens are another. Work backwards from the use cases to all possible blockchain implementations.

**Comment by sneak** [comment]
Complexity makes the product less attractive; security features moreso. We will strike an appropriate balance, ideally without adding a lot of complexity (such as savings balances or additional token types).

**Comment by nedsteem** [comment]
Here are my thoughts/strong leanings:

Forget we have Savings on STEEM. (3 days is a pittance in context of recoveries).

Power/Vesitng is the key for* time delay protection* and should be utilized/available in SMTs.  

If there is Savings on SMTs it should be 30 days (to match recovery window) or we should not code it in at all.  (Arguably don’t code Savings into SMTs at all if Power/Vesting is utilizable for *time-delay protection*)

**Comment by theoreticalbts** [comment]
> Vesting is the key for *time delay protection*

With my proposal, we will still have STEEM-style vesting for SMT's, the UI will just be hidden by default.  Users who care about having a time-lock to protect their funds are free to turn on the hidden UI and vest their SMT.

> Complexity makes the product less attractive; security features moreso. We will strike an appropriate balance

Yeah.

> ideally without adding a lot of complexity (such as savings balances or additional token types).

We shouldn't be afraid of complexity if it buys us important objectives.  Instead, let's design blockchain features to achieve our objectives in such a way that the feature is available to the 10% of users for whom it creates a lot of value, while the UI hides the complexity from the 90% of users who don't (and shouldn't need to) care about it.

**Comment by sneak** [comment]
Agreed, but the UI for 100% of the users must be built. A UI that has an “advanced” pane that still must educate those users on the mental model (whether it’s the UI’s or the blockchain’s) is more complex (and expensive) than a simple UI over a simple model that provides the same benefits.

I would love to figure out a way to provide the security benefits of time-locked savings, the anti-double-vote benefits of vesting, and the implementation and UI simplicity of a single balance. Perhaps it’s impossible, but there are some ideas in this thread that suggest to me that we’re getting warmer.

**Comment by sneak** [comment]
And I further agree that we shouldn’t (and won’t) be afraid of necessary complexity to achieve our ends. Let’s just see how small of a set of “necessary” we can make for those goals.

**Comment by clayop** [comment]
Small inputs from an average user.

I tend to agree with sneak. Simplicity is the key. And for average users, time-lock has double edges. It can protect users fund when get hacked, but it also restrict liquidity when they need to withdraw for some reasons (e.g. car accident or urgent surgery). I would prefer to have another security tool, such as 2FA or hardware wallet support, and move towards more simplicity.

**Comment by nedsteem** [comment]
If there is Savings and Power we have done it wrong. Two bad UX creations.  We need to pick one.

Power makes more sense than Savings. It has gamification and security rather than only one. And the security is implicit and incentivized rather than based only in the advanatage of security.

@theoretical. I will make this call to move us forward. We will kill Savings in SMTs. Implement mandatory Power in SMTs to have voting rights over a pool.

**Comment by youkaicountry** [comment]
The decision then is to implement STEEM style vesting for SMTs, called power. The UI will hide much of the complexity unless a user opts to expose advanced features.

**Comment by nedsteem** [comment]
This still needs clarification. Will address on next SMT call

**Comment by youkaicountry** [comment]
Okay. We won't make a final decision until we've had a call discussing the matter.

**Comment by theoreticalbts** [comment]
So to review, I will summarize my proposal:

### Overview

- (a) UX for most users:  Just post, vote, and buy tokens.
- (b) Token balance counts toward voting strength even if it's not vested.
- (c) You can still vest tokens and get benefits similar to STEEM.
- (d) No savings accounts for SMT's.

### Why not remove STEEM style vesting?

- Advanced users can vest tokens and earn a return.
- Literally pays people to think of themselves as long term holders rather than short term speculators.
- Since returns get big when no one vests, those big returns can jump-start demand for a currently unpopular token
- Token founders may vest tokens to provide a blockchain enforced limit on how fast their tokens become available (to re-assure token buyers and other founders you won't immediately dump your tokens and leave).

### Implementation details of (b)

- Time-locking for tokens in regular balances is implemented by tokens becoming "vote-locked" when they vote
- Tokens entering a user's balance (from transfers, cancelled/filled market orders, etc.) are also vote-locked
- Vote-locked tokens become vote-unlocked at a rate proportional to the token balance of the account
- Lazy updates:  Calculations only need to be done when balance actually changes
- Votes limited to a percentage of vote-unlocked tokens
- When tokens go out of an account balance, the blockchain prefers to move vote-unlocked tokens

**Comment by youkaicountry** [comment]
We had a call today on this issue, and a decision reached. @theoreticalbts is going to make a writeup of the results and post them here.

**Comment by theoreticalbts** [comment]
So basically we decided to stick to what's written (or implied) in the whitepaper:

- SMT's will have Steem-style vesting.
- Whether inflation goes to vesting SMT holders is (of course) specifiable in the ICO.
- No savings balances for SMT's.

Reasons:

- Time-lock functionality is one of the requirements of the system.  This is the main reason, any system redesign which provides similar time-lock properties to VESTS will have similar UX issues.
- It was how SMT's were originally planned, deviations from spec require fairly compelling reasons at this point.

There are some interesting suggestions in this ticket, and the call provided a few as well.  I will try to make sure they get filed to the proper place so they aren't forgotten.  Once I take care of that, I'll edit this post.

- Unlocked SMT's can vote
- SMT creation UI
- UI only displays SMT's
- Better document exactly how vesting works
