### ISSUE TITLE
Create smt_market_maker_state_object

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#2010]
Market maker state `smt_market_maker_state_object` will be an object in the database that represents the current state of an SMT's market.

Create this object with the following conditions:
- It should be associated with one and only one SMT.
- Each SMT should have one and only one market.
- Additionally, it should contain the following member fields to track its state:
  - `asset steem_balance;` - s in the paper
  - `asset token_balance;` - t in the paper
  - `asset token_supply;` - T in the paper
  - `uint32_t reserve_ratio = 0;` - r in the paper

**Comment by vogel76** [comment]
1. If market_maker_state_object is so tightly associated to smt_token_object (in 1-1 relation), let's embed it inside smt_token_object as member variable. Then 'smt_token_object::current_supply' could be removed to store actual supply on market_maker_state_object::total_supply member.
1. If this type is SMT only specific, maybe its name should start from 'smt_' prefix.

**Comment by youkaicountry** [comment]
1. I'm definitely fine with this, it would make sense to embed it.
    @mvandeberg @theoreticalbts Are there any pros / cons from a performance standpoint with the approach outlined here vs. embedding a struct in the `smt_token_object`?

2. Good idea, I'll change the name once we have a final decision on 1.

**Comment by theoreticalbts** [comment]
> maybe its name should start from 'smt_' prefix

I agree.

>  Are there any pros / cons from a performance standpoint with the approach outlined here vs. embedding a struct in the `smt_token_object`?

My immediate response is that this is basically this is an implementation detail that may change over time; it's not too important.

But after thinking about it for a while, that's not 100% true.  First, keep in mind that most of Steem's API's:

- Start out with initial implementations that just copy objects from the state
- Are then locked-in to conform to that initial implementation by backward compatibility concerns

So whatever we choose now will have a tendency to get locked into the API design.

Should the API design (a) minimize round trips, or (b) hide irrelevant information?  In the interests of modularity, I would lean toward (b), which suggests putting it in a separate object.

> Are there any pros / cons from a performance standpoint

Recall that `chainbase` works only on entire objects.  Putting this information in the same object increases performance of code that needs to read both `market_maker_state` and some other fields from the `smt_token_object`, as such code will only need to do one object lookup.

However, there is no free lunch -- performance of code that writes to either `market_maker_state` or `smt_token_object` will suffer, as calling `modify()` on any object causes *all* of the object's fields to be copied to the undo state.  (Performance of code that writes to both will see a modest gain since the bookkeeping only needs to be done once.)

Also, from our potential future plans for modular blockchain, it should be in a separate object where possible.

By my count, this is two concerns (API modularity and blockchain modularity) that point weakly in the direction of separate objects, and one concern (performance) that points weakly in an uncertain direction (it could go either way depending on the usage pattern, but it is probably pretty small compared to the rest of the blockchain load in any case).

**Comment by youkaicountry** [comment]
In the interest of potential modularity we will keep it as planned, and I am changing the name to contain `smt_` prefix.

**Comment by vogel76** [comment]
@youkaicountry @theoreticalbts 
1. Public API has separate data structures which are filled basing on different internal object model (that's fine and utilizes facade C++ design pattern). So the argument to hide irrevalant information is not good here.
1. I don't see any benefits in scenario where these 2 objects are stored in 2 separate indices, only drawbacks.
    1. Memory consumption will be higher, because to store `smt_marker_state_object` you have to extend it for some member variable identifying SMT token (NAI?). Also memory used for building tree data structures (in the boost::multi_index holding the `smt_marker_state_object`) is needed.
    1. Data access is slower - to retrieve `smt_marker_state_object` object lookup must be done.
    1. There is no benefit related to smaller object size being saved during `modify` call because according to issue #2015 you always have to update token supply in both objects. So if they will be separated, you will have to call `modify` 2 times: once per `smt_token_object`, second for `smt_marker_state_object`, what actually will lead to copying more data than in embedded case (`smt_marker_state_object` must be enhanced by NAI field, smt_token_object still need to hold token supply).
    1. Blockchain and state object models are completely different things. Modularity impact on state object model could be significant for objects loosely coupled (i.e. comment and comment-contents which in some specific cases can lead to association 1->0) not so tightly associated as here, because as stays in above spec these objects must always coexits. Also both are integral part of SMT implementation.
    1. Having these object tightly coupled as single one, we can store `steem_balance`, `token_balance` and `token_supply` just as `share_type` instead of `asset` (because all asset-types are semantically defined by name of member variable or smt_token_object holding the market-state) and again save memory.

Having in mind my above remarks, I still propose to:
* define separate data structure for `smt_marker_state_object`
* eliminate `current_supply` field from `smt_token_object`
* embed its market-state object inside `smt_token_object`

**Comment by theoreticalbts** [comment]
> 1. Public API has separate data structures

Agree in principle, but this means we have to put API design on the list of things that needs to be explicitly done.

> 2i. Memory consumption will be higher

Agree, but the effect is small because only one instance of each data structure exists per SMT.

> 2ii. Data access is slower

Agree, if we're talking about accessing both objects.

> 2iii. you always have to update token supply in both objects

True, if supply is kept in both objects, and the most frequent update to `smt_token_object` is supply.

> 2iv.  Blockchain and state object models are completely different things

I don't understand what is meant by "blockchain object model" and "state object model."

> 2v. Having these object tightly coupled as single one, we can store `steem_balance`, `token_balance` and `token_supply` just as `share_type` instead of `asset`

This is a micro-optimization, there are many places in existing objects where `asset` should really be `share_type` if we're being cautious about every last byte of memory.

**Comment by theoreticalbts** [comment]
So to summarize my feelings, if it was up to me, I'd choose separate objects based on two factors:

- (1) If we do modular blockchain in the future, we will need to do a little more refactoring if it's in one object.
- (2) Steemd as a whole is kind of a mess because we haven't always been 100% disciplined about keeping things tightly modular and isolating distinct concepts, I want to do better in new code.

Overall, this is a minor issue, you've done a great job outlining the case for a single object.  I'd be okay with a decision either way.

**Comment by youkaicountry** [comment]
After considering both approaches, I am making the final decision to embed the market data as a struct, I will close these issues an open a new one.

**Comment by youkaicountry** [comment]
Replaced by #2029
