### ISSUE TITLE
Create vesting SMT

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#2021]
Whenever an SMT is created, an associated vesting SMT should also be created. 

This vesting token will have the same NAI except for one bit, which will be reserved for the purpose of identifying the vesting version of a token.

**Comment by vogel76** [comment]
@youkaicountry `smt_token_object` has property which allows vesting (as also defined in SMT whitepaper there is dedicated operation which allows to change this property value). Does creation of this vesting-token should depend on this value ?

**Comment by youkaicountry** [comment]
The `allow_vesting` property is outdated, and all SMTs will have vesting included. This should probably be removed in another issue.

**Comment by Kiwonik** [comment]
@youkaicountry @theoreticalbts @mvandeberg The way I see creation of vesting SMT is that where the 'regular' SMT is created now (`smt_create_evaluator::do_apply`) an additional call to `_db.create< smt_token_object >` will be placed with vesting version of `asset_symbol_type` (containing vesting version of nai). So there will be two `smt_token_object`s for every SMT, allowing to search and find appropriate object using given nai.
However for the purpose of this implementation and other places where distinction between regular/vesting versions of given SMT is required I propose that following methods are added to `asset_symbol_type`:
```
/** Returns true when symbol represents vesting variant of the token,
    false for regular one. */
bool is_vesting() const;
/** Returns vesting symbol when called from regular one
    and regular symbol when called from vesting one.*/
asset_symbol_type get_paired_symbol() const;
```
Although implementation of these methods seems obvious for SMTs and STEEM/VESTS pair, I'm not sure how SBD should be treated.

**Comment by youkaicountry** [comment]
I like the `get_paired_symbol` and `is_vesting` functions.
For SBD, I imagine we'll always have to special case it given its nature. 
Some possibilities:
1) Prevent `get_paired_symbol()` from ever being called with SBD, and have an assert inside of the function to enforce this.
2) Return the the SBD back.
3) Return null

Option 2 & 3 are pretty similar, option 1 requires maybe slightly more work outside of the function, but all options require special casing to check if it's an SBD.

**Comment by Kiwonik** [comment]
@youkaicountry  Let's go with option 2, as it requires least-to-no work outside functions.
I assume you will be creating a separate issue for these functions as I'm not even sure whether the bit-differentiation has been ultimately agreed on - couldn't find the conclusion among numerous issues related to asset serialization changes and the like.

**Comment by mvandeberg** [comment]
#2065 contains my proposal, but I have not received feedback from @youkaicountry or @theoreticalbts

**Comment by youkaicountry** [comment]
The proposal in 2065 identifies which bit we use and thus how to distinguish between SMT vest and token, I'll file an issue for the creation of the above outlined functions.

**Comment by Kiwonik** [comment]
Blocked until #2085 is implemented.

**Comment by Kiwonik** [comment]
@youkaicountry @mvandeberg @theoreticalbts After digging in steem vesting code I decided that a common single `smt_token_object` represents both liquid and vesting variant of SMT, because such solution has many advantages over two separate object for each variant.
1. Right now there are 20+ fields in `smt_token_object` and all of them (except 2, mentioned below) are common to both liquid & vesting variant of SMT. If there were separate l/v (liquid/vesting) objects, all of these fields would be duplicated. Not only memory would be wasted, but also every time one of the fields is modified, the other object would have to be found to modify the field there too to maintain consistency. Otherwise it would be only a matter of time that some developer reads obsolete value from one object, being convinced that up-to-date value is read from the other object. Thus a double object solution is both memory expensive and error prone.
2. Regarding the fields that are not common to both variants, like `current_supply`, they make similar problems when separate `smt_token_object`s are used. `current_supply` is needed only in liquid object, while `current_vesting_smt` + `current_vesting_shares` are needed in vesting object. However in 2 objects solution both of them are the same type so the liquid one would have 2 unneeded fields and the other way round. Again memory is wasted and the solution is prone to the same errors as described in 1.
3. The only field that has the same meaning and name but different value for both l/v variants of SMT is `symbol`. However since acquiring the other symbol now is as easy as calling `asset_symbol_type::get_paired_symbol()` I just renamed the field to `liquid_symbol` so there be no doubt what value is stored there.

**Comment by Kiwonik** [comment]
As part of this issue implementation I had to add `database_fixture::get_new_smt_symbol` as a replacement to `database_fixture::name_to_asset_symbol` as the latter one, once created as stopgap solution (until `get_smt_next_identifier` is ready) is now obsolete and returns invalid symbols.
