### ISSUE TITLE
Developer request - Increase the tag limit

### ISSUE THREAD

**Issue by Zappl** [steemit/steem#2024]
From what we read it was very spammy at the start when you guys had around 20 tags. Zappl and a few other app developers are requesting that the tag limit be raised. 

Surely sites can Include a tag limit their self. So if they don't like more than 5 it won't show more than 5 in their post. I know some people are concerned about how it might make their themes look ugly but it has an easy fix. Just don't allow the loading of more than your limit on your site.

The Steem blockchain will have more than just long-form sites to think about once smt's launch.

This would be a nice addition to v.20

**Comment by mvandeberg** [comment]
The tags use the parent permlink field for posts. That field has a maximum length of 255. The tags plugin, which parses the field limits the indexed tags to 5. As this point, with how much memory the tags plugin uses, I would not want to increase that limit. However, Hivemind will be taking over those duties shortly. Tagging @roadscape so he is aware of the suggestion.

I think this is a Steemit.com product decision rather than a blockchain decision, so I am closing for now.
