### ISSUE TITLE
SMT emissions resource consumption

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#2052]
So there are some design questions to go with SMT emissions.  An SMT emission operation creates an ongoing `O(n)` cost while only consuming `O(1)` space.  Therefore, it will make an excellent denial-of-service vector unless its cost is properly accounted and placed into the operation.

More generally, consider a long-lived blockchain construct (such as an `smt_setup_emissions_operation` that says "send 10 tokens to Bob every hour, forever").  In general such a construct changes the blockchain state, then "wakes up" on a repeatable time-based or event-based signal to cause further state changes.

Clearly such a construct could impose an arbitrarily large resource load on the blockchain over its lifetime, so we must be careful not to create a denial of service vector.

In order to solve this problem, let's introduce the concept of a *ping operation*.  Rather than waking up automatically when an event occurs, the construct only wakes up on a ping operation.  It then checks to see whether the relevant amount of time has passed, or the relevant event has occurred, and processes it accordingly.

Now we have solved the problem; the construct's resource consumption only occurs when the ping transaction executes.  The ping operation can be issued by *any user*, not necessarily the one that created the SMT.  So as long as the value of the processing to any of the affected parties is greater than the cost of the transaction, then that party can execute the ping.

Text explaining this should be added to the whitepaper, and implementation added to the blockchain.

**Comment by theoreticalbts** [comment]
Other places in SMT's where this could be an issue:

- Market maker
- Issuing refunds when launch fails
- Issuing tokens when launch succeeds

**Comment by Kiwonik** [comment]
@theoreticalbts @youkaicountry @mvandeberg 
3. **There will be no automatic vote payout for SMT** configured similarly to Steem **if ping operation scheme is implemented**. No 'Redeem awards' button appears in SMT users interfaces when payout time expires, because no automatic payout happens. The reason is that automatic payout needs updated emissions info (if only to calculate total award pool) and up-to-date emissions numbers can't be guaranteed if emissions are user-driven by means of ping operation.
4. **Everytime a UI is to show someone's SMT balances** (e.g. showing wallet on steemit.com) **it has to issue emission ping operation first or print "balance may be outdated" message**. This is because the account may be a direct benficiary of some SMT's emissions as set in `smt_inflation_unit` hence with pinged emissions the balance may be outdated due to emission events waiting to be pinged. Issuing ping operation to read someone's balance can use much more resources than one automatic operation, since UI client can refresh the account properties many times. **It also introduces the concept of using bandwidth for read-only accesses**, greatly amplifying confusion regarding bandwidth and possibly blocking any account activity after displaying its few properties only.

**Comment by youkaicountry** [comment]
Outdated due to automated actions.
