### ISSUE TITLE
smt_contribute_operation, smt_claim_operation

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#2054]
The `smt_contribute_operation` simply specifies an SMT, amount:

```
struct smt_contribute_operation
{
   account_name_type     contributor;
   asset_symbol_type     smt;
   contribution_id_type  contribution_id;
   asset                 amount_steem;
   extensions_type       extensions;
};
```

The `contribution_id` is a 32-bit integer namespaced to the `from` account.  `(contributor, smt, contribution_id)` should uniquely specify a `contribution_object`.  The `amount_steem` must be STEEM.  As specified in the whitepaper, it remains locked until `announced_launch_time` occurs.  Then `smt_refund_operation` must be issued to reclaim the STEEM if the launch does not occur.  Or `smt_claim_operation` can be issued to claim the SMT if the launch does occur.  The whitepaper implies that tokens will be automatically issued if the launch occurs, but this is untenable for resource usage reasons #2052.

```
struct smt_claim_operation
{
   account_name_type     executor;
   account_name_type     contributor;
   contribution_id       contribution_id;
   asset                 amount;
   extensions_type       extensions;
};
```

The `(contributor, amount.symbol, contribution_id)` tuple must match a prior `smt_contribute_operation`.

**Comment by theoreticalbts** [comment]
Also, some of this is new from the whitepaper, so we need to update the WP to match.

**Comment by theoreticalbts** [comment]
I should also note that `smt_claim_operation` has an `executor` which means anyone can cause an account which participated in an ICO to receive the SMT to which they are entitled.  Meaning that claiming can be provided by the ICO creator.  Which is an important use case when ICO recipients are newly created accounts with not enough SP to claim themselves.

**Comment by Kiwonik** [comment]
@theoreticalbts @youkaicountry Before this issue may be implemented we need answer for the questions asked in https://github.com/steemit/steem/issues/1694 (see last comment there).

**Comment by Kiwonik** [comment]
@theoreticalbts @youkaicountry @mvandeberg The Velocity HF 20.0 proposes "_crediting the account with permanent minimum bandwidth instead of providing Steem Power to the new account_". It means that `executor` fields are unnecessary and should be removed from both `smt_claim_operation` and `smt_refund_operation`, because the situation they were added to help in, namely "_ICO recipients are newly created accounts with not enough SP to claim themselves_" can not happen.

**Comment by Kiwonik** [comment]
@theoreticalbts @youkaicountry What exactly is the purpose of user-provided contribution id that was added to `smt_contribute_operation`, `smt_claim_operation` & `smt_refund_operation`? When implementation of contribution was discussed in https://github.com/steemit/steem/issues/1694 the id was proposed as contribution object's attribute (i.e. part of the state) which allowed that "_contributions can be iterated on in FIFO order_". Now the id became a part of blockchain, being arbitrary values provided by contributor, but what for? Why would anyone want to claim or refund only specific one of her contributions and why shall we enable it?

**Comment by vogel76** [comment]
@theoreticalbts @youkaicountry  Probably better (and simplier) solution is to make `smt_claim_operation`/`smt_refund_operation` operating on set of contributors, previously defined by executed `smt_contribute_operation`. There will be only 1 `smt_claim_operation`/`smt_refund_operation` per given SMT, which during its evaluation makes proper transfers to contributor's accounts. This way number of operations to be executed is significantly reduced, there is also no need to especially identify associated contribute <=> claim/refund operations.
Also mentioned above `contribution_id` has a drawback, because the client which establishes such operation must known its actual value (which can be verified at validation stage). This is a way to pollute blockchain by broken operations and also complicates process of operation build.
This is is not needed at all at operation definition - the uniqueness in contribute ops set can be enforced by triple (contributor, smt, amount_steem).

**Comment by theoreticalbts** [comment]
> It means that executor fields are unnecessary and should be removed from both smt_claim_operation and smt_refund_operation

This field allows new desirable functionality.  Basically it allows the ICO creator (or anyone really) to force distribution of the funds.  So it helps by allowing funds to be distributed without requiring the recipients to log in and sign a transaction.

We could distribute ICO's automatically in per-block processing, but per-block processing should only require `O(1)` database lookups; if a large ICO occurs, the huge amount of state that needs to be updated could effectively DOS the network (especially considering with 3-second block times, you expect blocks to propagate across the p2p network in less than 3 seconds, which means being processed several times [1] including signature verification).

Also, as @mvandeberg points out in #1694, we may [2] need to process contributions in FIFO order.  If this is the case, an earlier contributor who chooses not to claim their tokens will prevent all later users from claiming their tokens.

The `executor` field allows anyone to cause the tokens to be claimed.  So absent users will not be able to block the distribution of tokens, even if the token creator is also absent.

> Why would anyone want to claim or refund only specific one of her contributions

Each operation should only require `O(1)` database lookups.  If you have an operation that says "claim all my contributions," then that requires `O(n)` where `n` is how many contributions you made.

Think about malicious user Eve, who creates a dummy ICO and contributes to it millions of times over the course of months, $100-$1000 worth of Steem Power and she has plenty of bandwidth to do it.  Then she claims them all in a single block, now she's stopped the network with a transaction that takes a long time to process and modifies a lot of state.

> being arbitrary values provided by contributor

Since we can't have an operation that says "claim all my contributions," you need a way to identify a specific contribution that you're claiming.

This is how market order ID's work, and it's a good system.  It allows you to know at the time of transaction creation what ID will be assigned to the contribution object.

> Probably better (and simplier) solution is to make `smt_claim_operation` / `smt_refund_operation`operating on set of contributors, previously defined by executed `smt_contribute_operation`

Yes, this would be simpler, but it violates the design principle that each operation should only do `O(1)` database lookups, and therefore opens a denial of service vector (re-read above discussion).

[1] A block needs to be processed several times to get across the p2p network because not all p2p nodes are directly connected, i.e. a new block will have to travel over some paths consisting of several hops to get to every node on the network.

[2] I created a [separate issue](https://github.com/steemit/steem/issues/2138) to discuss whether this is actually true.

**Comment by vogel76** [comment]
@youkaicountry @goldibex We are waiting for the answers ~2 workweeks

**Comment by theoreticalbts** [comment]
> Let us make smt_claim_operation & (automatic) smt_refund_operation virtual operations that divide total number of contributions to be processed into tranches.

I don't like this for two reasons.  First, I've learned that *explicit is better than implicit*.  What happens on the blockchain now depends on the tranche size.  Which will need to be a parameter that can be tuned by the witnesses, or a config constant that we manually tune through hardforks, or something.  It leads to smaller chain size, yes, but it also requires us to keep code for the past logic.  And it makes it harder to describe what the blockchain is doing since it happens automatically.

I'm also not sure that the tranche approach is DoS resistant.  If malicious Eve has `m` sock puppet accounts, and creates `n` SMT's, then Eve over the long-term must do `O(m*n)` operations.  But she would then be able to force a refund (or distribution) of all the SMT's simultaneously, which causes `O(mn)` processing to occur, with only `O(n)` operations.

Basically when the `n` contributions to an SMT occur, it creates an "overhang" which allows `O(1)` operations to "buy" `O(n)` computation.

> `withdraw_vesting_operation`. Just as evaluation of vesting withdrawal sets several points in time when some virtual operations shall be triggered...

Interesting you bring this up.  I admit, some of our existing operations don't stick tightly to this principle.  But there is a saying:  "When you find yourself in a hole, stop digging."  We should be more careful when designing new operations than when designing old operations.

FWIW, `withdraw_vesting_operation` sets up operations at many points in time.  Making `smt_claim_operation` and `smt_refund_operation` virtual ops means operations will occur at a single point in time.

I personally recommend letting the specification stand.  @mvandeberg @youkaicountry Any opinions?

**Comment by mvandeberg** [comment]
I am in agreement with @theoreticalbts 

Yes, `withdraw_vesting_operation` does create future behavior, it only creates 13. We have an `O(1)` operation creating `O(1)` future automated ops.

You can consider votes as well. There is automation at payout that grows with the number of votes. In this case `O(n)` ops create `O(n)` future automated ops.

I think there is a good principle here that has been implied, but never explicitly stated. In order for an op to be DoS resistant, it needs to generate future automated ops at an order less than or equal to the generating op.

**Comment by Kiwonik** [comment]
@theoreticalbts @youkaicountry

**The tranche approach is DoS resistant**, because it fullfils definition provided by @mvandeberg 

> In order for an op to be DoS resistant, it needs to generate future automated ops at an order less than or equal to the generating op.

Explanation: In automated claim/refund approach every contribution generates exactly one of (claim, refund) automated operation, thus at an order equal to the generating (contribution) op. All of those generated ops are processed at the same point of time, exactly as during voting payout. In tranche approach only a part (tranche) of generated ops is processed at the same point of time.

Conclusion: **Tranche automated claim/refund approach is even safer than voting payout.**

Example:
> If malicious Eve has m sock puppet accounts, and creates n SMT's, then Eve over the long-term must do O(m*n) operations. But she would then be able to force a refund (or distribution) of all the SMT's simultaneously, which causes O(mn) processing to occur, with only O(n) operations.

In first sentence you admit that Eve has to do `m*n` operations, this is consistent with the number of `m*n` processing to occur, but at the end you mistakenly claim that only `n` operations were the cause. No, it was `m*n` contribution ops that caused `m*n` processing.

BTW **Eve Malicious can mount your attack today using voting payout.** Creates `n` posts, then upvotes each with `m` of her sock puppet accounts, finally all of `m*n` voting payouts have to be processed simultaneously. No tranche system to help.

**Comment by theoreticalbts** [comment]
> Eve Malicious can mount your attack today using voting payout

This is true.  There are two different arguments we can make based on this fact:

- (a) The systems already implemented in STEEM do not suffer from any problems.  Since the design issue I explained affects an existing part of STEEM, it cannot be a problem, and therefore it is okay to use a similar design for new code.
- (b) The design issue I explained is a problem.  Therefore, new code should be written to avoid the issue, and old code affected by the issue should be re-written.

I like argument (b), but we have too many other tasks on our plate to attempt to redesign the posting / voting code right now.

**Comment by Kiwonik** [comment]
Actually, there's a third argument, that describes best the tranche system.
- (c) The system already implemented in STEEM **did not suffer from any problems so far**.
   - **We are extra careful** guys, so we design new code with an additional flexible solution that can help us in case of problems. 
   - We will modify legacy system when time allows.
   - We believe in "**If it works don't break it**" rule therefore we chose this evolutionary approach, and not a complete revolution.

The last point is very important, as we already see several problems caused by `executor` revolution:
1. **It already opened a new attack possibility** forcing me to reopen an implemented issue, see this https://github.com/steemit/steem/issues/2056#issuecomment-366723365
2. It severely affects contributors UX. Anybody subscribing her money for new shares is expecting to automatically get either the shares or the money. Most of contributors won't know that manual interaction is needed to get their shares or steems. This will result in lots of upset people and lots of unneeded support issues. But the worst case could happen when experienced Steemit users try to execute their claim operations at roughly same time - when ICO finishes and system gets blocked.

**Comment by youkaicountry** [comment]
I am generally in agreement with @theoreticalbts, we should continue to use the existing system which has proven to work very well.

@sneak @goldibex However I think this is an important discussion, do you have any thoughts to add?

**Comment by mvandeberg** [comment]
Claiming rewards to user accounts requires manual intervention and has worked quite well. A UI can notify the user of the pending claim. We can support suboptimal UX in the blockchain **if** it can be eased by a UI and it provides benefit to the blockchain implementation.

**Comment by youkaicountry** [comment]
Given that the user-intervention system is already implemented and battle-tested, we should proceed forward with it. It's not worth allocating the resources and taking the risks to explore a new system.

**Comment by Kiwonik** [comment]
Moved claim to separate issue #2390 due to its transformation to automatic action.

**Comment by Kiwonik** [comment]
@theoreticalbts The `contribution_id` field of `smt_contribute_operation`, `smt_refund_operation` and claim action seems to be completely redundant now. The presence of `amount` field of `smt_refund_operation` supports this impression - we're declaring amount to be refunded, not specific contribution. The id is even less useful in claim action - there's no point to claim user's contributions separately, on the contrary, for performance reasons there should be a single claim per user, of total claimed amount of SMT (as calculated during contribution processing on successful launch).
@youkaicountry Pending the confirmation of `contribution_id` field removal (see above) this issue has been implemented as far as validation goes.

**Comment by vogel76** [comment]
@youkaicountry As said above probably new issue(s) specific to automatic action framework must be created.
Initial issues have been created:
https://github.com/steemit/steem/issues/2396
https://github.com/steemit/steem/issues/2390
We also need tasks related to further stages of contribute phase (ie contribute-op evaluation, data structures to hold contribution data in state).

**Comment by youkaicountry** [comment]
Outdated.
