### ISSUE TITLE
Recommended section?

### ISSUE THREAD

**Issue by fmiboy** [steemit/steem#206]
Why was recommended posts section and code part was removed?
Is there plan to add this again, as without it "follow" doesn't make much sense?

**Comment by theoreticalbts** [comment]
I'm not sure why that code specifically was removed, but in general, code dealing specifically with the website doesn't really belong in the core.  Closing this ticket because the issue raised here is too broad and open-ended to be addressed in a Github ticket.

Following is being developed as a plugin, see #58 #192
