### ISSUE TITLE
Complete SMT NAI generation

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#2063]
Currently, NAI generation for new SMTs is a basic stub implementation.

The specification needs to be finalized and implemented.

**Comment by youkaicountry** [comment]
Note from issue #2028:
- NAI strings starting with 0 are reserved for future assets and will not be assigned

**Comment by vogel76** [comment]
As discussed to @youkaicountry already existing code in `database::get_smt_next_identifier()` shall be enhanced by forcing production of Vesting SMT NAI.

**Comment by Kiwonik** [comment]
I think that `database::get_smt_next_identifier()` (whether it be current stub or final implementation), shall produce only liquid variant of NAI, because according to SMT creation flow, the symbol produced by this method is put into `smt_create_operation` that has and needs only one member for desired NAI. That's because the operation's validator can easily get vesting version of NAI based on provided liquid one, using methods described in issue https://github.com/steemit/steem/issues/2085
However what is described in OP above (making `database::get_smt_next_identifier()` set/clear appropriate bits in produced NAIs) is still important thing to be done ASAP even in current stub implementation, as it blocks issues #2085 #2021  & #1856

**Comment by youkaicountry** [comment]
Since the vesting NAI is able to be calculated from the liquid NAI, it should be fine to return only the liquid with this method. Inside the method any work to setup the vesting NAI can be done.
