### ISSUE TITLE
NAI vesting discussion

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#2065]
A decision still has not been fully made on how to represent the VESTS of an SMT. 

A couple of potential solutions:
1) Create a totally new asset type for it
2) Reserve a bit of NAI to represent the vesting version of a token

**Comment by youkaicountry** [comment]
I would just as soon discard 1, and go with 2 or something similar. Managing yet another asset type seems unreasonable to me.

**Comment by mvandeberg** [comment]
To go from asset_num to NAI, we do 

```c++
nai_data_digits = (asset_num >> 5); 
uint32_t nai_check_digit = damm_checksum_8digit(nai_data_digits);
return nai_data_digits * 10 + nai_check_digit;
```

If the vesting bit is bit 5 of the asset_num, then it will go in the 10s place of the NAI.

If we assume that bit 5 == 1 is vesting, then `@@xxxxxxx5n` and `@@xxxxxx6n` become the liquid/vesting pair. If we want, for vesting assets, we can calculate the checksum of the liquid version.

To be clear, what I am suggesting is:

```c++
bool is_vesting = asset_num & 0x00000010;

uint32_t nai_check_digit = damm_checksum_8digit( nai_data_digits & 0x00000001);
```

**Comment by mvandeberg** [comment]
The benefit of this solution is:

1. Vesting and Liquid SMT assets are quickly distinguished based on the asset num.
2. Vesting and Liquid SMT assets are quickly distinguished based on the NAI string.
3. Knowing either the vesting or liquid SMT NAI string or asset num allows you to quickly generate the other.

**Comment by Kiwonik** [comment]
@mvandeberg There seems to be something missing in the code snippets you presented in earlier comments, or perhaps I don't quite understand your proposal.
Let me concatenate the snippets first to get a clear picture:
```
   FC_ASSERT( space() == smt_nai_space );
   bool is_vesting = asset_num & 0x00000010;
   uint32_t nai_data_digits = (asset_num >> 5);
   uint32_t nai_check_digit = damm_checksum_8digit( nai_data_digits & 0x00000001);
   return nai_data_digits * 10 + nai_check_digit;
```
1. As far as I can see `is_vesting` variable is not used here to alter returned NAI, but judging by your comments I assume the last line of code should rather look like this:
```   return (nai_data_digits + is_vesting) * 10 + nai_check_digit;```
That would put vesting bit "in the 10s place of the NAI" as you proposed, but in would also result in strangely looking liquid/vesting NAIs if last digit of `nai_data_digits` is 9, e.g. SMT liquid NAI  `@@01999999n` would result in its vesting NAI `@@02000000n`. Is this your intent?
1. Another unclear issue for me is the purpose of reducing the checksum generation to a single bit input or at least that's what I see in one of your code snippets:
```   uint32_t nai_check_digit = damm_checksum_8digit( nai_data_digits & 0x00000001);```

@youkaicountry I'm not sure whether to reopen this issue, I'm not challenging the choice made here, only asking for clarification.

**Comment by mvandeberg** [comment]
The code snippets were not meant to be a reference implementation for this issue. Which is good because I made some mistakes.

What is important is that in the the 5th bit of the asset num (least significant bit of nai data digits) determines if it is vesting or not.

`bool is_vesting = asset_num & 0x00000010;` This code does need to actually exist in the implementation. It exists as an example. 

If setting the bit means vesting, then the even number should be liquid and the odd number vesting. In your earlier example `@@01999999n` and `@@02000000n` cannot be paired. `@@01999999n` is the vesting symbol for `@@01999998n` and `@@02000000n` is the liquid symbol for `@@02000001n`.

`uint32_t nai_check_digit = damm_checksum_8digit( nai_data_digits & 0x00000001);` 
This is the most egregious error. It should be `nai_data_digits & 0xFFFFFFFE`. The checksum digit for a liquid/vesting pair uses the liquid asset_num for the checksum.

`return nai_data_digits * 10 + nai_check_digit;`
This line does not need changing because the nai_data_digits are derived from the asset num. `uint32_t nai_data_digits = (asset_num >> 5);` The vesting bit is preserved through that conversion. The only change that needs to be made here is how the checksum digit is calculated.

**Comment by Kiwonik** [comment]
@mvandeberg I'm quite sure that vesting bit, being 5th bit of `asset_num` is not preserved through `uint32_t nai_data_digits = (asset_num >> 5);` conversion, because it sheds exactly 5 bits.

**Comment by mvandeberg** [comment]
I'm off by one. It should be the least significant bit _after_ (asset_num >> 5).

**Comment by mvandeberg** [comment]
Adjust bitmasks accordingly if they are wrong as well.
