### ISSUE TITLE
claim_reward_balance2_operation reward_tokens member needs changed

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#2067]
This ticket is about PR #1997.

The `claim_reward_balance2_operation` has a field `flat_map< asset_symbol_type, asset > reward_tokens;`

The code assumes for any `item` in `reward_tokens`, `item.first == item.second.symbol`, but this is not enforced anywhere.

Additionally, the binary serialization is inefficient, since each element's symbol must be serialized twice.  A couple ways to fix this:

- Use `flat_map< asset_symbol_type, share_type >` instead
- Use `vector< asset >` instead, and have `validate()` enforce `reward_tokens[i].symbol > reward_tokens[i-1].symbol` for all `i > 0`

**Comment by mvandeberg** [comment]
Let's use a `flat_set` with a custom comparator that only sorts by asset symbol type.

Put the comparator in `asset.hpp` so we can use it elsewhere.

**Comment by vogel76** [comment]
We did try to use `flat_set` with custom comparison op, what is natural solution for this, but it is impossible because of bad implementation of `pack`/`unpack` methods operating on flat_set in fc. The problem is, that they can match only containers (**this problem is specific to all containers having implemented serialization there**) when other args than held type(s) are default ones. If we will specify flat_set<asset, asset_symbol_less> it won't match, because template functions `pack`/`unpack` have missing other template arguments.
To avoid such big change in fc, we chosen less complicated way and used a map.

**Comment by mvandeberg** [comment]
These challenges should have been discussed before choosing a suboptimal implementation. We have our own fork of `fc`. We can make whatever changes we need to support `steemd`. `steemd` should never suffer because don't want to modify `fc`.

**Comment by theoreticalbts** [comment]
> Let's use a flat_set with a custom comparator that only sorts by asset symbol type

No, no, please no.

> flat_set with custom comparison op, what is natural solution for this

Maybe in C++, but this construction will make porting to other languages more difficult.

Essentially you're saying "This is a container of `asset` where each asset's symbol is unique."  Which breaks the abstraction layer between the container and the contained object.  In other words, you want to have a special container that "knows" how to dig into the `asset` data structure and extract the `symbol`.  You're implementing business logic constraints in the container type.

The conceptually simpler way is to simply use a `vector` and *in the validator* enforce that the container elements are sorted and distinct.

The code to enforce uniqueness belongs in the validator.  It feels very wrong architecturally to put it in a comparator.

**Comment by youkaicountry** [comment]
After studying the issue, I agree with @theoreticalbts that using a `vector` and validating it is the way we should proceed, instead of modifying fc.

**Comment by mvandeberg** [comment]
We should be very clear in defining the sort order. The overloaded operators for `asset_symbol` compare asset nums, which are an implementation detail. This needs to be sorted by NAI. Chosen arbitrarily by my preference, they will be sorted in ascending order because system assets have leading 0s and will place them at the beginning of the ops.

I believe this is the only place such validation currently occurs, but I can see it becoming a repeated pattern of validation for handling multiple types. Preemptively, the validation should be in a helper method called `void verify_asset_uniqueness( vector< asset >& )` throws if the sorted/uniqueness constraint is violated. Rather than returning true/false and asserting the return, throwing in the function allows us to return a more detailed error as to where the constrain was violated. See `comment_payout_beneficiaires::validate()` as an example.

**Comment by mvandeberg** [comment]
I don't think this issue should be closed. The OP is about fixing the problem. As best I can tell, it is not fixed.

**Comment by youkaicountry** [comment]
I'm going to add this to the current sprint, since it is directly related to a sprint issue.
