### ISSUE TITLE
It is super confusing for users to see the total post payout drop 25% when it is paid out !!!!

### ISSUE THREAD

**Issue by liondani** [steemit/steem#212]
https://steemit.com/steemit/@jholdsworthy/why-does-the-payout-of-a-post-go-down-directly-when-it-s-paid-out

https://steemit.com/steemit/@anduweb/is-there-something-wrong-with-the-payout-amount-calculation-before-the-payout-moment-big-difference-between-the-two

Show us independently what exactly the poster will get and what the curators before the pay out's happen... 
For example: 
When mouse over : show what curators get, when not, show what only the poster gets in real time!

**Comment by oldambtster** [comment]
That would be more transparant and a good addition for a better understanding of the Steem engine by the Community members.

**Comment by abitmore** [comment]
This is a GUI issue. Submit to https://github.com/steemit/steemit.com/issues

**Comment by kentfrost** [comment]
I had a similar issue that I made a new issue thread for which dropped my payout from around $1250 to $143 right at the very second of payout. I watched the payout occur because I wanted to prepare to transfer it to my coinbase account. This was WAY more than 25%, instead it was a whopping 88.5% drop within 2 seconds.

**Comment by liondani** [comment]
I opened a new issue on the right place as of abitmore suggestion
