### ISSUE TITLE
Implement smt_revealed_cap validate

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#2152]
Implementation of smt_revealed_cap::validate should be implemented, as it is blocking issue #1511

**Comment by Kiwonik** [comment]
@theoreticalbts Please advise on following issues found during implementation:
1. SMT whitepaper in **hidden caps** section says _"A nonce is also included in the hash to prevent (...)"_. What method of inclusion did you have in mind? I assumed following procedure:
```
smt_revealed_cap amount_with_nonce;
amount_with_nonce.amount = 1000000;
amount_with_nonce.nonce = 1234;

smt_cap_commitment commitment;
commitment.hash = fc::sha256::hash( amount_with_nonce );
```
This is consistent with the way I imagine `validate` method implementation:
```
void smt_revealed_cap::validate( const smt_cap_commitment& commitment )const
{
   ...
   fc::sha256 reveal_hash( fc::sha256::hash(*this) );
   FC_ASSERT( reveal_hash == commitment.hash );
}
```
Please confirm/correct/elaborate.

2. Why is `fillin_nonhidden_value_hash` used in `smt_cap_commitment::validate()`. It allows only the commitment of nonhidded cap, isn't it?

**Comment by theoreticalbts** [comment]
- 1. Yes, this is what I meant.

- 2. The code you ask about is inside `if( lower_bound == upper_bound )`.  The point of having `lower_bound` and `upper_bound` is that we will require `lower_bound <= amount <= upper_bound`.  In case `lower_bound == upper_bound`, the value of `amount` is known:  The value of `amount` must be the common value of `lower_bound` and `upper_bound`.  Since the user's intent is clearly to have a non-hidden cap in this case, using a nonce has no purpose.  So I force the nonce to be zero in this case.  If you know the nonce is zero, you can check the hash right away, so I do that too.

**Comment by Kiwonik** [comment]
@youkaicountry @theoreticalbts Here's the additional explanation of cap _nonce_ that in my opinion should be included in SMT whitepaper (as I reported on Thursday meeting):

> It is important that UI generates the hash (including _nonce_) during commitment the same way it is generated during later validation of reveal operation by node. Otherwise the two hashes (user provided at commitment and node generated at reveal) don't match which results in rejection of reveal operation. Therefore UI needs to generate commitment hash as follows:
> ```
> smt_revealed_cap amount_with_nonce;
> amount_with_nonce.amount = 1000000; // <- sample value of cap
> amount_with_nonce.nonce = 1234; // <- sample value of nonce
> 
> smt_cap_commitment commitment;
> commitment.hash = fc::sha256::hash( amount_with_nonce );
>  ```
