### ISSUE TITLE
Modify transfer_to_vesting_operation to support SMT vesting

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#2160]
The `transfer_to_vesting_operation` should be modified to support vesting SMTs. This will include modification of `database::create_vesting` to support vesting SMTs.

**Comment by vogel76** [comment]
@youkaicountry @theoreticalbts Given questions appeared to `database::create_vesting`:
1) does  the same algorithm shall be used to calculate new_vesting for SMTs ? If where is specified actual one.
2) if in 1) the same algorithm shall be used, how vesting share prices shall be retrieved ? Does smt_token_object shall have additionally defined such parameters ?
Does the SMT whitepaper specify such rules ?

**Comment by theoreticalbts** [comment]
So here's some information on how Steem vesting works.  This information should probably go in the wiki, but I can't find the wiki, so I will put it here.

# Steem, vesting, and Steem Power

The core idea of vesting is that *holding STEEM creates value for everyone*.  So the blockchain should have an operation allowing users to say "This lump of STEEM, I won't transfer it for a while."  And the blockchain enforces that commitment.

Such Steem is called "Steem Power."  New commitments to holding are called "Powering Up."  Changing held Steem to liquid Steem is called "Powering Down."

Originally, the terminology used was "vesting."  But at some point, it was deemed that "Powering Up/Down" is better terminology.

People won't voluntarily choose to hold their STEEM unless there is some incentive.  The incentives are as follows:

- Only vesting STEEM counts for voting
- Vesting STEEM is paid a portion of STEEM emissions

So then the implementation problem becomes, how do you implement the idea of "OK, a bunch of users all have powered-up Steem.  Every block, we get a little lump of STEEM from emissions, and we want to divide that new STEEM among all users with powered-up Steem according to their balances.  How do
we distribute that little lump without having to iterate over everyone's balance every block?"

The answer is, you combine all the powered-up Steem in a single "pot," and then give everyone claims against that pot.  With this data structure, the rest of the implementation becomes simple and efficient:

- If you want to "pay everyone Steem proportionally to their powered up balance," you just add Steem to the pot without printing any new claims.
- If I have `K` claims, and in total `N` claims exist, how much are my `K` claims worth?  Well, the value of all `N` claims is the pot, and since claims should be "fungible" or "homogenous", the value of `K` claims should be the Steem in the pot, times `K/N`.
- If someone wants to "power up" some Steem, then you put their Steem in the pot, and print them some new claims.  How many claims do you print?  Just enough claims so that their new claims have the same value as the Steem they're contributing.
- If someone wants to "power down" some Steem, then you give them the Steem value of their claims from the pot, and burn their claims.

The actual terminology is as follows:

- The things I have been calling "claims" are called `VESTS`.
- The thing I have been calling "the value of claims" is called "Steem Power."

## Implementation note:  How many claims (algebra)

If we're contributing `s` STEEM and printing `x` claims, the value of the `x` claims will be `(pot + s) * x / (N + x)`, where `N` is the number of claims that already exist (before printing).  Since we said the value should be `s`, we can get a numerical answer for how many claims to print by setting the above expression equal to `s` and solving for `x`:

```
(pot + s) * x / (N+x) = s
(pot + s) * x = s*N + s*x
(pot + s - s) * x = s*N
x = s*N / pot
```

## Implementation note:  How do you round?

How do you round?  Always against the user's favor [1].  So when powering up and giving the user claims, round the claims down to the nearest claim-satoshi.  When powering down and giving the user Steem, round the Steem down to the nearest Steem-satoshi.

[1]  If you allow the possibility that rounding in the user's favor can occur, a malicious user might be able to repeatedly issue carefully constructed operations that all round in their favor, slowly draining the pot into their wallet over time.

**Comment by theoreticalbts** [comment]
# Steem, vesting, and Steem Power

The core idea of vesting is that *holding STEEM creates value for everyone*.  So the blockchain should have an operation allowing users to say "This lump of STEEM, I won't transfer it for a while."  And the blockchain enforces that commitment.

Such Steem is called "Steem Power."  New commitments to holding are called "Powering Up."  Changing held Steem to liquid Steem is called "Powering Down."

Originally, the terminology used was "vesting."  But at some point, it was deemed that "Powering Up/Down" is better terminology.

People won't voluntarily choose to hold their STEEM unless there is some incentive.  The incentives are as follows:

- Only vesting STEEM counts for voting
- Vesting STEEM is paid a portion of STEEM emissions

So then the implementation problem becomes, how do you implement the idea of "OK, a bunch of users all have powered-up Steem.  Every block, we get a little lump of STEEM from emissions, and we want to divide that new STEEM among all users with powered-up Steem according to their balances.  How do
we distribute that little lump without having to iterate over everyone's balance every block?"

The answer is, you combine all the powered-up Steem in a single "pot," and then give everyone claims against that pot.  With this data structure, the rest of the implementation becomes simple and efficient:

- If you want to "pay everyone Steem proportionally to their powered up balance," you just add Steem to the pot without printing any new claims.
- If I have `K` claims, and in total `N` claims exist, how much are my `K` claims worth?  Well, the value of all `N` claims is the pot, and since claims should be "fungible" or "homogenous", the value of `K` claims should be the Steem in the pot, times `K/N`.
- If someone wants to "power up" some Steem, then you put their Steem in the pot, and print them some new claims.  How many claims do you print?  Just enough claims so that their new claims have the same value as the Steem they're contributing.
- If someone wants to "power down" some Steem, then you give them the Steem value of their claims from the pot, and burn their claims.

The actual terminology is as follows:

- The things I have been calling "claims" are called `VESTS`.
- The thing I have been calling "the value of claims" is called "Steem Power."

## Implementation note:  How many claims (algebra)

If we're contributing `s` STEEM and printing `x` claims, the value of the `x` claims will be `(pot + s) * x / (N + x)`, where `N` is the number of claims that already exist (before printing).  Since we said the value should be `s`, we can get a numerical answer for how many claims to print by setting the above expression equal to `s` and solving for `x`:

```
(pot + s) * x / (N+x) = s
(pot + s) * x = s*N + s*x
(pot + s - s) * x = s*N
x = s*N / pot
```

## Implementation note:  How do you round?

How do you round?  Always against the user's favor [1].  So when powering up and giving the user claims, round the claims down to the nearest claim-satoshi.  When powering down and giving the user Steem, round the Steem down to the nearest Steem-satoshi.

[1]  If you allow the possibility that rounding in the user's favor can occur, a malicious user might be able to repeatedly issue carefully constructed operations that all round in their favor, slowly draining the pot into their wallet over time.

**Comment by Kiwonik** [comment]
@theoreticalbts You've just repeated the huge comment already placed here over three weeks ago. Also note that the issue has been closed ten days ago.
