### ISSUE TITLE
Registration doesn't work!

### ISSUE THREAD

**Issue by Facepalmchain** [steemit/steem#2181]
Srsly guys, why so? I can't register, it keeps sending me the same confirmation code 26346! Tried about 5 different phone numbers (thanks to my colleagues). Tried from different networks (at home, office, from my phone). NOTHING works. 
Look into this pls

**Comment by sciborg** [comment]
Please goto https://steem.chat and use Help channel there.

**Comment by alexyangfox** [comment]
@Facepalmchain  if you have some ethers or other cryptocurrency, you may try to pay the registration fees yourself: check [this](https://steemit.com/faq.html#What_are_other_ways_to_create_an_account_on_the_blockchain_besides_using_Steemit_com).  

FYI:  

1. No fees are needed to make a transaction on Steemit, this is nice for most of us.  
2. But some guys (say, promoters) may post a lot of promotion articles or comments to spam steemit.  
3. There is a concept called "bandwidth" in Steemit, it means how much of the network transaction resources you can use.  Your "Bandwidth" is proportional to the "Steam Power" you  have.  That means if you want to start with Steemit, you have to at least have some little "Steam Power" for the use of "bandwidth" of the network to make transactions.  

That's why it costs you some fees to register a usable account.

**Comment by mvandeberg** [comment]
This repository is not the place for this discussion. The Steemit signup process is unrelated to the Steem blockchain code repository.

Steemit chat does not require you to have a blockchain account. You should be able to signup there and get support from the help channel.
