### ISSUE TITLE
Filtering user feed by app or parent category

### ISSUE THREAD

**Issue by singhpratyush** [steemit/steem#2189]
We can request user feed by using `get_discussions_by_feed`. Is it possible to only fetch the posts created under some specific parent category or app name?

**Comment by mvandeberg** [comment]
The data storing user feeds is independent of the data that tracks tags. If we were to implement such an API call (which we won't because we are trying to reduce the number of specific API calls in favor of generic calls) we would simply filter the feed as we returned it. I suggest doing the same thing when your process the results.
