### ISSUE TITLE
New account set up problem

### ISSUE THREAD

**Issue by oneeve8** [steemit/steem#2192]
I tried to set up a new account
Followed the procedures, got to the screen waiting for verification
Got a code on my phone
Went back to Steemit but there’s nowhere to put the code
Tried login- that didn’t work it says my user name doesn’t exist 
Tried starting over with set-up- that also didn’t work- says the phone # is already being used!
Yes, of course it is being used- BY ME!
Long story short- where do I put my code?

**Comment by TimCliff** [comment]
This is the wrong repository for signup issues. Can you open this in the faucet repository (with screen shots), or ask for help in the #help channel of steemit chat?

**Comment by asdgfd** [comment]
TimCliff, Everything interacting with Steem for help requires an account which you can not get if you have signup issues. My issue is I have a disabled, so I don't have a mobile phone, so I can't get an account because there is no process to sign up without mobile (a violation of US law, BTW), and you can't get assistance, because assistance requires an account. So, unfortunately for oneeve8, above, and anyone else with signup issues (such as numbers already being used from previous holders, or from DOS-signups), they are pretty much screwed.

**Comment by TimCliff** [comment]
You do not need to have an account in order to use steem chat. All it requires is email.

There are alternate signup methods listed in the steemit.com FAQ that do not require a phone.

**Comment by oneeve8** [comment]
From your FAQ:
“The only way to have an account created via steemit.com is to supply your email and phone number. Because Steem is an open and permissionless network, there are other ways to create an account. Any Steem blockchain account can be used on steemit.com.”

That was copied from your FAQ
Not sure what it means to say in the first place it is “the only way” and then in the second sentence say there are “other ways” I don’t see anything that explains what that other way is if there is one. I can only guess that the first sentence is the correct one and the second one is just referring to other types of accounts that you can set up that are related to the main umbrella of steemit- since the last sentence seems to imply that. Otherwise, would you mind explaining it?

Its nice that you don’t require an account for chat but there is no help here. It’s just full of people needing help and nobody answering questions. I understand that it is done through volunteers.

In any case I was able to find a ticket in your github faucet for the exact same problem and it was labelled as a bug after I placed a second comment there. I hope this bug is fixed soon. I’m guessing that there were updates done to your sign in procedures and something got messed up in the process. The person who posted their comment posted it fairly recently. Thanks for your time.

**Comment by TimCliff** [comment]
https://steemit.com/faq.html#What_are_other_ways_to_create_an_account_on_the_blockchain_besides_using_Steemit_com

**Comment by oneeve8** [comment]
Hmmm I see, so now I have to pay for something. I hope that is not on purpose. I’m dealing with another tech company that made me sign up for automatic billing without me knowing about it and then made it virtually impossible to cancel without cancelling my credit card completely. People get pretty frustrated with that sort of thing, I hope Steemit is not going in that direction. Customers are getting pretty much fed up with such kinds of deceit. I know sometimes things are programmed that way on purpose. Companies are also making it practically impossible to get any help. Not saying that is the case here, but I’m just wondering. I’d rather not sign up at all than to have to continually jump through impossible hoops. It’s better to be up front and honest than to purposely program something to be complicated that backs you into a wall so you have to pay for something. I hope you understand my suspicions if that is not the case. It would seem ridiculous if it was. But that seems to be the direction tech is moving. I understand the dilemma- Customers want everything free, so then you guys have to trick people into buying things. Why not just give the price of signing up right up front? Or isn’t your philosophy to make this a block chain supported product? So why pay for something then? I had high hopes that are quickly being dashed. Thanks for replying.

**Comment by TimCliff** [comment]
The Steem blockchain charges an account creation fee for each account that is created. This fee is transferred into the new account, so that the account has some initial Steem Power. This is required, so that the account has bandwidth to interact with the blockchain. More information on bandwidth can be found here: https://steem.io/steem-bluepaper.pdf

Steemit, through signup.steemit.com offers to pay this account creation fee for users who apply, provided they give sufficient information to prove they are an individual, and have not created an account before. (Right now, that is based off of a user’s email and phone number.)

Users are not required to use this service to obtain an account, but it is the only option if you want Steemit to fund the account with the initial SP required to transact. Other options (listed in the link above) will let users pay the fee to create their own account - without needing Steemit to verify their info. Most services that offer this do also charge a small fee on top of the blockchain account creation fee, as a charge for using their service.

The fee is a one-time charge, and can be paid using cryptocurrency - which ensures they don’t even have the option to charge you again.
