### ISSUE TITLE
Undelegated Vests do not return

### ISSUE THREAD

**Issue by eletom** [steemit/steem#2201]
So I delegated some Vests with Vessel and I undelegated it more than 7 days ago, but they are missing. What could be the problem? 

https://steemd.com/tx/49ec45205c9f16849f41cbe010237e40aa2487d3

https://steemd.com/tx/cfbf7142b7080c3a67b92d1c58b159dcfffa861d

https://steemd.com/tx/6a37cd3f228d1d8385169b141c46065c7102d2c7

I really dont know what could be the problem. I hope they will return some day

**Comment by TimCliff** [comment]
Since the delegations were made as part of account creation, it has a different cool down period. It is the greater of “7 days from the time the undelegation request is made” and “30 days from when the account was created”.

**Comment by eletom** [comment]
Wow thanks. Thats a relief. Is it somewhere written altogether? (I guess in the whitepaper) (Okay, I will google it.) Thanks, have a nice day. :)

**Comment by acostaeladio** [comment]
I need to know more details about the delegations used to create new accounts, in March I try to recover a delegation that I used to create a new account and even Steem Power has not returned to my wallet.

**Comment by TimCliff** [comment]
@acostaeladio please read the history of comments in the issue. It will take 30 days to return a delegation to your account if it was from a new account creation.

**Comment by acostaeladio** [comment]
Thank you for answering me @TimCliff , for April 18, 30 days have passed since the delegation of the new account was canceled, 46 days have passed without knowing what has happened
https://steemit-production-imageproxy-upload.s3.amazonaws.com/DQmZTqBndnUbB99ErgQpoXNswLbnnBdbhkGrvHDZWfrHDmx
![image](https://user-images.githubusercontent.com/36697190/39606524-e2692688-4f03-11e8-8f00-9f697d58ef0d.png)

**Comment by mvandeberg** [comment]
I am not sure what interface you are using to view delegations, but your account does not currently have any outbound delegations.

https://steemit.com/@acostaeladio/transfers

Under the SP value there would be a parenthetical if there was incoming or outgoing Steem Power due to delegation.

https://steemd.com/@acostaeladio

`Delegated vesting shares` is 0.

**Comment by acostaeladio** [comment]
![delegacion_steem-power_eladio](https://user-images.githubusercontent.com/36697190/39608348-d9e82c24-4f0e-11e8-87d8-9c6c8c4047cf.jpg)
https://steemd.com/@acostaeladio?page=12

**Comment by mvandeberg** [comment]
https://steemd.com/@acostaeladio?page=9

![screen shot 2018-05-03 at 17 21 34](https://user-images.githubusercontent.com/15834128/39608458-7cdae23c-4ef6-11e8-965f-38c171fd48a6.png)

I think there is some confusion regarding how delegations are notated.

`vesting_shares`: Your Steem Power (This number does not change when you delegate)
`delegated_vesting_shares`: How much you are delegating to others
`received_vesting_shares`: How much you are receiving in delegations from others.

Let's say you have 60 SP, the values would be:
```
vesting_shares = 60
delegated_vesting_shares = 0
received_vesting_shares = 0
```

Then you delegate 20 SP
```
vesting_shares = 60
delegated_vesting_shares = 20
received_vesting_shares = 0
```

You remove the delegation, and a week later it goes back to
```
vesting_shares = 60
delegated_vesting_shares = 0
received_vesting_shares = 0
```

I am wondering if you thought that it should go to
```
vesting_shares = 80
delegated_vesting_shares = 0
received_vesting_shares = 0
```

Which would be wrong because you never had 80 SP.

**Comment by steemchiller** [comment]
@mvandeberg That would make sense. I think it is really a bit confusing for the users and maybe we should have an extra op in the account history that appears once when the cool down period has ended (op 'return_delegated_vests' or so).  

> I am not sure what interface you are using to view delegations, but your account does not currently have any outbound delegations.

He used the 'Delegation History' on SteemWorld (ORDER BY date DESC) and the first row shows 0 SP, which means that a full undelegate was the last action for the account. There is an extra section for current outgoing delegations in the tool.

Another thing I would love to see on Steemit is something like this:

<img src="https://user-images.githubusercontent.com/30645598/39630380-71ace040-4faf-11e8-8fe1-6f108faa7bb3.png">

<img src="https://user-images.githubusercontent.com/30645598/39630560-f375454a-4faf-11e8-8349-c6f8ee24462d.png">

It currently shows:

<img src="https://user-images.githubusercontent.com/30645598/39630441-9d041092-4faf-11e8-93c0-4439e2b9a55e.png">

Which is a bit confusing too, since the delegated vests are being subtracted and only the sum is being displayed. Not super important, but would be a nice thing to have...

**Comment by mvandeberg** [comment]
> I think it is really a bit confusing for the users and maybe we should have an extra op in the account history that appears once when the cool down period has ended (op 'return_delegated_vests' or so).

There already is. Please see the attached image in my last comment. If it does not show on SteemWorld, that is their decision.

If you have any suggestions on how to improve the Steem Power UX, please make them in the Condenser repo. https://github.com/steemit/condenser

**Comment by steemchiller** [comment]
You're right, my mistake. The operation 'return_vesting_delegation' is already being shown on SteemWorld. I was confused and obviously didn't know my own code as I should. It have been some busy months for me. So my first answer I wrote a few weeks ago was correct and now it's clear to me that the vests returned and all is fine ;)

Thanks for you help!

**Comment by luzcypher** [comment]
I have read this whole thread before adding my comment here.
Over 7 days ago I undelegated 1000 Steem Power.
My account was not new when I made the delegation.
I have not received my Steem Power back.

This is when I initiated the un-delegation 7 days ago:

https://steemd.com/tx/007978602cc83a23a2c6939e5f7411abdcc7b8f2

https://steemd.com/b/22493255#007978602cc83a23a2c6939e5f7411abdcc7b8f2

This is saying it is returned:

![returning delegation from steendb](https://user-images.githubusercontent.com/28201472/40468303-9d6dfaf0-5ef2-11e8-94d5-76171c8ad0d0.png)

but I don't see it in the block:

https://steemd.com/b/22694807#007978602cc83a23a2c6939e5f7411abdcc7b8f2

It has not returned to my account.

Can you please help? Thank you.

**Comment by mvandeberg** [comment]
`return_vesting_delegation` is a virtual op. It is stored in account history to represent something has happened, but is not stored in a block like a user created action is.

**Comment by luzcypher** [comment]
The 'helpie" is not the delegation I'm referring to.

I undelegated 1000 SP to openmic and it has not returned to my account

**Comment by luzcypher** [comment]
https://steemd.com/b/22493255#007978602cc83a23a2c6939e5f7411abdcc7b8f2

https://steemd.com/tx/007978602cc83a23a2c6939e5f7411abdcc7b8f2

**Comment by TimCliff** [comment]
@luzcypher what do you see that indicates it has not been returned to your account?

I see at https://steemd.com/@luzcypher that you have `15,488,461.421650` VESTS, and `515,000.000000` of them are delegated.

It shows here that you have `515000.000000` VESTS delegated to `helpie`:
https://api.steemjs.com/getVestingDelegations?account=luzcypher&from=-1&limit=100

**Comment by luzcypher** [comment]
Yes, I have a delegation to @helpie. I'm not talking about that.

I also delegated 1000 steem to @openmic months ago and 
undelegated that 1000 Steem from @openmic.

The 1000 Steem that I undelegated to @openmic has not been returned to my account.

These are the links showing the undelegation to @openmic, not @helpie.

https://steemd.com/b/22493255#007978602cc83a23a2c6939e5f7411abdcc7b8f2

luzcypher undelegate to openmic

https://steemd.com/tx/007978602cc83a23a2c6939e5f7411abdcc7b8f2

What I see that indicates it has not been returned to my account is my Steem Power did not increase by the 1000 Steem after I undelegated it.

I can't be any more clear than that. What is it you do not understand?

I delegated 100 steem to the @openmic account and when I recently undelegated it 11 days ago
it has not returned to my account. It is unaccounted for and I want it back.

**Comment by TimCliff** [comment]
> What I see that indicates it has not been returned to my account is my Steem Power did not increase by the 1000 Steem after I undelegated it.

This is not how it works though. When you delegate SP, your amount of SP does not change. Your _Delegated SP_ amount does. Similarly, when you undelegate - your base SP amount does not change. After the cooldown period, your delegated SP amount will go down.

This is what happened in this case where you delegated SP to openmic and the cancelled it. Your delegated SP amount had already had the delegated SP removed.

You can verify this by delegating 1 SP to an account that you are currently not delegating to. You will see that your SP amount does not go down when you do this, but your delegated SP does go up by 1.
