### ISSUE TITLE
implementation of strcmp_equal looks wrong

### ISSUE THREAD

**Issue by emfrias** [steemit/steem#2203]
I think the `||` should be changed to `&&`

https://github.com/steemit/steem/blob/42e2d95ec09d1695ec1b392d47a2e44612815cf0/libraries/chain/steem_evaluator.cpp#L69

**Comment by theoreticalbts** [comment]
AFAICT this comparator is only used to check, when editing a post, that `parent_author` and `parent_permlink` specified in the op match what's in the database.  But it doesn't actually do anything with the fields from the op afterwards.

So imagine hypothetically at one point in time that the op was locked down to enforce this properly.  And then it was unlocked to allow an expanded set of values in the `parent_author` and `parent_permlink` fields when editing.  What would be the consequences?  There would be none, since `parent_author` and `parent_permlink` are just discarded by the editing code.

**Comment by mvandeberg** [comment]
I am in agreement with @theoreticalbts's assessment of the triviality of the bug but that it does need to be in a hardfork as well.
