### ISSUE TITLE
FC is not vendored in develop

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#2209]
PR #2145 was against `master`, how are we going to vendor FC in `develop`?

**Comment by mvandeberg** [comment]
`develop` was going to be reset to `master` and force pushed. We now need to merge `develop` back into `master` before this happens. I made the decision to merge against `master` because an appbase release is close and, at the time, did not want to disrupt development efforts by other members of the team. However, because this did not happen as fast as expected, it is now becoming a burden. I suggest following the same plan now, regardless of the appbase release to get the fc vendor into `develop`.

**Comment by mvandeberg** [comment]
Done
