### ISSUE TITLE
Automatic actions framework

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#2241]
In this ticket, let's discuss a framework for automated actions.

The problem is that we want some actions to occur "automatically" over time.  However, we want to be sure that it is impossible for normal or malicious use to require an unbounded number of such automatic actions during replay.

Many existing blockchain functions could be described as automatic actions.  However, in this ticket I will limit myself to consideration of not-yet-implemented, SMT-related automatic actions:

- Claiming SMT tokens
- Market maker ping transactions
- SMT emissions

The design I propose is as follows:

- Place automatic actions in a new block extension type, `automatic_actions`
- The block extension should have a maximum serialized size equal to a fraction of the block size (perhaps 20%).
- Witnesses are free to determine the set of block actions from the set of available actions using any algorithm.
- Each action is completely determined by a corresponding *action key*.  The rest of the action's fields must be a deterministic function of the action type, action key, and the blockchain state.
- For now, the witness plugin will implement a simple FIFO ordering of actions.  A single SMT's market maker and inflation actions will be included at most once per hour.
- In the future, if actions start to queue because the block extension is consistently full, the witnesses (or any subset of them) can implement and switch to a different ordering algorithm at any time.  For example, we may use the Steem in the SMT's market maker to determine how often the SMT's actions can occur.

Related tickets:

- #2052 SMT emissions resource consumption
- #2054 `smt_contribute_operation`, `smt_claim_operation` (proposes tranche system)
- #1724 Implement timed event scheduler
- #2060 Ping transaction for market maker

Specific implementation notes about different operation types:

### Claiming SMT tokens

Within a given SMT, claims MUST be processed in FIFO order.  The code should be written to allow processing of multiple claims for a single SMT within a single block.

The action key for SMT claims is the SMT's asset ID.

### Refunding SMT contributions

Refunds should not be automatic actions.  Refunds should be operations; a user must explicitly issue a transaction in order to receive a refund for an SMT launch that did not occur.  If the total contribution of users who *do not* choose to be refunded is greater than the minimum, a delayed launch can occur.

### Market maker ping transactions

The action key for a market maker ping transaction is the SMT's asset ID.

### SMT emissions

SMT emission should have its own clock which advances one "tick" every time an action occurs.  So if an SMT is programmed to emit every hour, and it has been 20 hours since the last action, the next action will only do a single hour's worth of emission.  For an SMT whose emission has become backlogged, multiple emission actions could potentially be included in a single block.

The action key for SMT emissions is the SMT's asset ID.

**Comment by theoreticalbts** [comment]
@youkaicountry @mvandeberg I would appreciate your input here, thanks.

**Comment by mvandeberg** [comment]
There are a few concerns I have with implementing this as a block extension. Block extensions currently are processed in block header validation. While they can have side effects (witnesses updating their version) the impact is well defined (hardforks are always the last thing to occur in a block). With this setup, we know have potentially significant side effects at the beginning of the block before transactions are applied. This may be a good thing, but currently all automatic actions occur after transactions are applied, not before. My gut is that this is a good thing because pending transactions act on known state, not unknown state.

We should decide what our official policy on when automated actions should occur in block processing (whether they are triggered by witnesses or implicit in the blockchain) and choose a method that fits with this policy.

**Comment by Kiwonik** [comment]
My doubts after reading:
1. Choosing actual solution to automatic actions overflow has been postponed to indefinite future when it happens. I think this solution(s) is the most important part of this ticket and should be proposed, and chosen based on detailed description now.
> In the future, if actions start to queue because the block extension is consistently full, the witnesses (or any subset of them) can implement and switch to a different ordering algorithm at any time.
2. There are two kinds of refunds - manual, when ICO can still succeed, though token creator failed to reveal some cap in time (so called delayed launch), and automatic when ICO enters the failed phase. The former should be an operation as you suggested, the latter should be automatic action. Both can (and should) share common code. 
Please see https://github.com/steemit/smt-whitepaper/pull/172 for updated flow diagram with fail phase.

**Comment by vogel76** [comment]
Maybe good solution is to add `prolog` and `epilog` containers holding operations to additionally executed in given block (I assume that this is real purpose of container holding `automatic_actions`). 
Prolog could contain ops to be executed before regular operations held in block, epilog after them.
It also does not conflict to existing extension field.

Such solution can solve 2 kinds of problems:

- store operations automatically taken by the witness because of task scheduling
- store operations now executed as **virtual operations** and make them real blockchain ops, what will allow all 3rd party tools (analysing blockchain contents) to gather all data from it, without a need to execute whole evaluation, required to establish virtual operations right now.  

To make this approach more practical size of such containers shall be limited after filling up the block - otherwise free space not used for regular block contents could be reused for prolog/epilog.

**Comment by theoreticalbts** [comment]
> Maybe good solution is to add `prolog` and `epilog` containers holding operations to additionally executed in given block (I assume that this is real purpose of container holding automatic_actions).  Prolog could contain ops to be executed before regular operations held in block, epilog after them.
It also does not conflict to existing extension field.

Any changes to the block data structure must be backward compatible with binary serialization of old blocks.  Adding new fields is not backward compatible, since it changes the length and breaks serialization.

How to design compatible changes?  It is possible to come up with a variety of clever serialization hacks that involve carefully considering which sequences of bytes are illegal for legacy blocks.  And then re-assigning some of those sequences to have meaning for new blocks.  (For example, consider how I re-worked `asset_symbol_type` binary serialization for SMT symbols.)

However, such clever hacks are not necessary when adding fields to an object where an `extensions` field is present.  The `extensions` field is *specifically designed to address this serialization problem*.  You just add new member types to the `static_variant` which defines the type of the `extensions` field, and the serialization will Just Work.

Having separate containers for prolog and epilog just adds extra complexity and serialization bytes for no purpose.  Because we generally know whether an extension will be processed in the prolog or epilog by its type:  The current extensions (`version`, `hardfork_version_vote`) will be processed before the block.  The `automatic_actions` extension will be processed after the block.  There's no need to have separate containers, you just iterate twice over `extensions`, once before the block, once after the block.

**Comment by vogel76** [comment]
> Any changes to the block data structure must be backward compatible with binary serialization of old blocks. Adding new fields is not backward compatible, since it changes the length and breaks serialization
Such assumption is very dangerous and it is an effect of **bad** design - it blocks software development and leads to using hacks to force things to work (as long as applying such hacks is possible). Same problem appeared in the issue  #1414 where is impossible separation of local storage format from block representation visible at network and also famous asset serialization.
The answer is explicit separation of public data structures and internal ones and obligatory **object versioning** which provide ability to correctly create internal representation over incoming data.

**Comment by mvandeberg** [comment]
@theoreticalbts and I had a discussion over this system and came to the following conclusions.

We are making our best efforts to design a system that can handle the current automatic actions efficiently and elegantly. We may not move those to this framework immediately, but we want to have to option to.

As stated before, all automatic actions have a cost. Some of these costs are handled by the blockchain itself and others by users. Of these, we have two types of automatic actions.

1. Deterministic actions. Savings withdrawals, reward payouts, etc. are examples of deterministic actions. A single op generates a deterministic number of automatic actions. The cost of the automatic actions should be included in the cost of the operation when it is initially included in a block. These automatic actions should be guaranteed to be included as quickly as possible when they occur.

2. Non-deterministic actions. Market Maker pings and SMT Inflation are examples of non-deterministic actions. The number of automatic actions generated is not deterministically determined at the time of the op. An account needs to pay for the actions as they occur. Our solution to this is an operation that states intent to pay bandwidth for some automatic actions. In this way, an account is responsible to pay bandwidth, but they do not need to run any software for such actions to occur. If they cannot pay for an automatic action, the inclusion of it will be delayed until they can.

In order for this to be compatible with bandwidth, blocks will need to be accepted even if they omit certain automatic actions. 

This potentially causes problems. For example, we first need to payout author rewards for content to calculate how much of the rewards pool gets divided between the author and curators. Then curators can be paid. If the first op was skipped and curators were paid, the action would fail. In order to get around this, automatic actions will be able to generate more automatic actions which will be placed at the end of the queue. This behavior also prevents a single burst of automated actions from starving other actions.

For deterministic actions, we want to employ the use of batch actions as much as possible to prevent duplication of data in the blocks. Such examples of batch actions are:

- Payout the next 50 curators for post A
- Expire the next 50 limit orders
- Process the next 50 vesting withdrawals

Such relative batch actions also prevent witness manipulation of state through front running actions.

Actions creating new actions also helps prevent front running. While we cannot prevent witnesses from including actions in a specific order, (doing so would require moving bandwidth back in to consensus) if an action generates another action, it enforces a relative ordering between certain actions that may have ordering dependencies associated with them.
