### ISSUE TITLE
real_price is being returned as 0.00000000000000000 for database_api#get_open_orders

### ISSUE THREAD

**Issue by muksihs** [steemit/steem#2265]
```
{"id":5,"jsonrpc":"2.0","method":"call","params":["database_api","get_open_orders",["muksihs"]]}
```

```
{"jsonrpc":"2.0","result":[{"id":1973339,"created":"2018-03-21T15:27:21","expiration":"1969-12-31T23:59:59","seller":"muksihs","orderid":1521646039,"for_sale":1839,"sell_price":{"base":"1.839 SBD","quote":"2.000 STEEM"},"real_price":"0.00000000000000000","rewarded":false},{"id":1981167,"created":"2018-03-23T21:46:09","expiration":"1969-12-31T23:59:59","seller":"muksihs","orderid":1521841566,"for_sale":1329,"sell_price":{"base":"2.005 SBD","quote":"2.015 STEEM"},"real_price":"0.00000000000000000","rewarded":false}],"id":5}
```

**Comment by mvandeberg** [comment]
That is an intentional change. The real price is a decimal approximation of the price of a limit order. By "real" we mean, real numbers as opposed to integers, not real meaning the opposite of fake.

The reason behind the change is there are limit orders that would trade at the same price in the consensus algorithm but can have different decimal approximations. These discrepancies can imply a fill order that is inconsistent with the actual fill order for the limit orders. Instead, the client should calculate the price for themselves (for display purposes only) and rely on the ordering returned by the API.
