### ISSUE TITLE
 Steem market changes your limit order prices? 

### ISSUE THREAD

**Issue by btctoken** [steemit/steem#234]
Why does steemit market turn your "limit order" into a "market order" ?
https://www.steemimg.com/image/RfQ0x
https://www.steemimg.com/image/RfuaL
https://www.steemimg.com/image/RfyGS
https://www.steemimg.com/image/Rf1il
https://www.steemimg.com/image/RfBuJ
https://www.steemimg.com/image/RfMrT

It also seemed like i was able to sell 0.006 steem that i didnt have at the time to myself? I may be wrong. @cryptohustlin is my steemit username.

**Comment by abitmore** [comment]
UI display issue. See https://github.com/cryptonomex/graphene/issues/460#issuecomment-236355266

**Comment by theoreticalbts** [comment]
Less than one satoshi of an asset (0.001 STEEM or $0.001 SD) cannot be traded.

In the screenshot apparently the user set the STEEM to 0.035 and the price to 2.76.  But if you have 96 SD-satoshis you can only get either 35 STEEM-satoshis (for a price of $2.7429) or 34 STEEM-satoshis (for a price of $2.8235).

The sane/safe behavior is to use the price more favorable to the user, the user might not be filled [1], but if they are then they will get more than they asked for [2].

The UI should warn the user when it has to change the price by $0.005 SD / STEEM.

But this is low priority as it only applies to extremely small orders.

[1] This is OK because it's an implicit risk of participation in the market -- the blockchain can post your offer, but cannot guarantee you will be assigned a counterparty.

[2] Obviously, giving the user more than they asked for is good.

**Comment by theoreticalbts** [comment]
Moving discussion to above ticket as this is a UI issue.
