### ISSUE TITLE
Define requirements for JSON-RPC support for SMT's

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#2359]
The JSON-RPC interface to query SMT information will be the main point of contact with the SMT code for steemit.com and third-party UI's.  However, the SMT whitepaper is currently silent on the subject.

The purpose of this issue is to define the required RPC queries for SMT's.  

Much of the RPC usage of SMT's will occur organically through extension of the existing RPC's.  For example:

- Executing SMT transactions will be done by sign / broadcast, the UI is the same as non-SMT transactions (except SMT asset will be specified in some field(s) ).
- Querying for past SMT transfers or other actions will use the same account history interface (except SMT asset will be returned in some field(s) ).

Some RPC's that need to exist are:

- Query for all SMT's in existence
- For a particular SMT, query for SMT-wide parameters such as current supply, max supply, etc.
- SMT market maker state
- SMT balance(s) for given account

Also I would like to suggest the following requirements and bounds for this issue:

- All queries should be paginated (for example, account balance -- what if an account owns tokens of a million different SMT's?)
- History (e.g. of market maker or automated actions) is out of scope for this issue
- Name-to-SMT mapping is out of scope for `steemd`

**Comment by sneak** [comment]
> Name-to-SMT mapping is out of scope for steemd

I think this is a dangerous product choice, and we should have a product solution in place for this instead of just punting on it.

**Comment by sneak** [comment]
Be advised @pkattera

**Comment by bonustrack** [comment]
It would be great to have an equivalent to the market API methods “get_ticker”, “get_order_book” and “get_recent_trades” for SMTs aswell. These methods are necessary to create a basic trading UI. Without these methods building a trading UI will require an external server to run a matching API, this would higher the barrier of making a trading UI and would not be totally decentralized. 

These methods are working well currently for SBD-STEEM trading, to enable SMTs there could be a new parameter to specify an SMT NAI example:
- `get_ticker({ asset: '@@000012345' })`.
- `get_order_book({ asset: '@@000012345', limit: 10 })`.

Something i noticed is that these methods currently seem to display a rate based on SBD instead of STEEM. I believe the rate should be based on STEEM as the SMTs would be traded with STEEM pair and not SBD.

**Comment by mvandeberg** [comment]
Documenting our discussion and decision:

We are going to implement `list_X` and `find_X` API methods for all database objects added in SMT work. This follows the pattern already implemented in `database_api`.

List calls allow iteration over objects via all sort orders used in consensus. find methods either allow quick lookup of multiple objects by primary key or finds all objects associated with a primary key. Example: find_accounts takes a list of account names and returns a list of all accounts that exist in the database. find_limit_orders takes a single account name and returns all limit orders associated with them.

While these API methods might not take the same structure as those that devs are used to in `condenser_api` they will provide access to all information in the fastest and most consistent manner for the SMT MVP. Other calls can be added later for specific purposes either in steemd or in client libraries.

**Comment by youkaicountry** [comment]
This is now implicit acceptance criteria for all SMT stories.
