### ISSUE TITLE
StatsD metrics spike

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#2401]
The result of this spike should be a number of issues to add support for metrics in our StatsD implementation.

Some possibilities:
- Block Latency
- Op latency
- p2p stats (messages / time, etc)

**Comment by mvandeberg** [comment]
I for sure want timing for `push_block` and `push_transaction`.

Also timing for each API call.

**Comment by mvandeberg** [comment]
We also need to get some timing information on the p2p code. Specifically latency between requests.

**Comment by theoreticalbts** [comment]
## Transaction stats

- For each transaction, how long does it take to push the transaction to the mempool?
- Does each transaction we hear about on the p2p network pass/fail validation?

## Mempool stats

These stats should occur when processing a block and transactions exist in the mempool.

- How long does it take to (a) undo transactions in the mempool, (b) apply the block, (c) redo transactions in the mempool?
- How many transactions are (a) in the mempool and the block, (b) in the mempool only, (c) in the block only?  (Note that `a+b` is always the mempool tx count, and `a+c` is always the block tx count.)
- How many transactions are discarded due to expiry?

## Witness stats

- How long does it take to generate a block?

## p2p stats

- At known places in the p2p code where blocking can occur, how long does it block?

## Fork stats

- When switching forks, record the block ID / parent / timestamp / witness of old fork, new fork, and block ID of most recent common ancestor (i.e. head block ID when you stopped popping and started pushing)

## RPC stats

- For each RPC, log the function name, duration, argument size (bytes) and result size (bytes)

**Comment by youkaicountry** [comment]
Closing and opening issues for proposed metrics.
