### ISSUE TITLE
get_ops_in_block missing vops

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#2413]
```
$ curl -d '{"jsonrpc":"2.0", "method":"condenser_api.get_ops_in_block", "params":[1000000, true], "id":1}' <ahnode-large> | jsonpp

"result": [{"trx_id": "0000000000000000000000000000000000000000" [....] }]

$ curl -d '{"jsonrpc":"2.0", "method":"condenser_api.get_ops_in_block", "params":[1000000, true], "id":1}' <ahnode> | jsonpp

"result": []
```

`ahnode-large` is non-rocksdb while `ahnode` is rocksdb build from ~2 days ago.

**Comment by mvandeberg** [comment]
The problem is a subtle one in the rocksdb implementation.

The implementation of rocksdb account history is designed the mimic existing account history plugin. It uses IDs that are implementation details of Chainbase. A completely new implementation

Object IDs are `int64_t`. The following definition for the key makes sense.

``` c++
typedef std::pair< uint32_t, int64_t > block_op_id_pair;
typedef PrimitiveTypeSlice< block_op_id_pair > op_by_block_num_slice_t;
```

However, we then do this:
```c++
int64_t encoded_id = obj.id;
if( obj.virtual_op > 0 )
{
   encoded_id |= VIRTUAL_OP_FLAG;
}
```

This isn't strictly needed, but it is useful to know if an op is virtual or not without needing to deserialize it. `VIRTUAL_OP_FLAG` is the MSB.

``` c++
#define VIRTUAL_OP_FLAG              0x8000000000000000
```

In `find_operations_by_block` we start at:

```c++
op_by_block_num_slice_t key(block_op_id_pair(blockNum, 0));
```

See the problem? We make all virtual ops negative with `VIRTUAL_OP_FLAG` and then start looking the ops at 0. The solution is to change the slice to uint64_t. This is safe for the same reason that using `VIRTUAL_OP_FLAG` is safe. We are guaranteed not the have a negative operation id.

This will, unfortunately, need a reindex because it changes the sort order of ops.
