### ISSUE TITLE
Transaction polling API

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#2458]
Create an api call which takes: transaction id, expiration time.

It returns one of the following:
- Expiration time in future, transaction not included in block or mempool
- Transaction in mempool
- Transaction has been included in block, block not irreversible
- Transaction has been included in block, block is irreversible
- Transaction has expired, transaction is not irreversible (transaction could be in a fork)
- Transaction has expired, transaction is irreversible (transaction cannot be in a fork)
- Transaction is too old, I don't know about it

If you give it a transaction id but no expiration time, it can only return results indicating whether or not it is aware of the transaction.

**Comment by theoreticalbts** [comment]
This needs to track the time of LIB and the first block in the TaPoS window.

The choices are:

- Add ~8 bytes of non-consensus fields and one `get_block()` call per block to consensus objects to track these times
- Add ~256k of consensus fields to blocks in the TaPoS window to track these times and avoid `get_block()` call
- Implement the API call and extra objects in a plugin (it is then unavailable unless you run the plugin)
- Change the spec of the API call so that it doesn't need these fields
