### ISSUE TITLE
Block all votes below a min rshare threshold

### ISSUE THREAD

**Issue by bytemaster** [steemit/steem#248]
This should prevent spam of meaningless votes.

**Comment by jl777** [comment]
this does increase the cost by requiring each bot to be funded with more, so it filters out bots from unfinanced creators.

However, many bot writers have already made enough they would just fund their bots, so I was thinking of an additonal filter using a minimum threshold of posting awards. The logic being that bot posts tend to not get many upvotes. Probably need to also require having received upvotes from some minimum number of decent reputation score accounts to prevent the bot writer from upvoting his own bots.

This would prevent a person who hasnt posted any decent content from having any voting power also, but maybe that is not a bad thing

**Comment by mvandeberg** [comment]
There are a couple problems with requiring posting history as a threshold for upvoting.

1. The barrier to upvote is already stake. Creating another barrier means that stake is no longer consensus metric for value of an account. The community can essentially preemptively ostracize new members by deciding to not upvote their content, effectively nullifying their stake. This barrier to entry may turn away potential speculators.

2. Having a hard number for a post payout is not an effective barrier against bots. It may actually hurt the platform in the long run. It creates a formula that if an account gets this many votes, it can then vote on other indefinitely. Create the barrier too low, and it does nothing. Create it too high and it excludes real people. Regardless of where it is, bot operators will know the exact amount of rshares needed to enable a new account for voting and be able to farm voting eligible accounts. While not voting on legitimate accounts. It will likely make the bot problem worse as there will be a higher overall percentage of rshares coming from bots rather than people.

Requiring min rshares is the best way to do this. Bots can get around by funding their accounts. But the more the fund, the more they are locked up and the benefits of short term gaming vs long term success of the platform begin to diminish. The goal of the change is not to kill botting, but to reduce blockchain spam.

**Comment by jl777** [comment]
makes sense
so the aim is not a "captcha" but just to reduce spam

**Comment by mvandeberg** [comment]
Correct. There are other measures, such as the super linear reward curve for content, that are designed to minimize the effects of botting. We have known from the very beginning that bots would use Steem, so we have been designing systems to reward human behavior that would be difficult to mimic using bots.

**Comment by bartcant** [comment]
why not use a captcha  for voting ?

**Comment by abitmore** [comment]
@bartcant you can run your own steemit.com server and remove the captcha. Everyone can. https://steemit.com/steemit/@teego/run-steemit-com-server-on-your-computer

**Comment by Auxon** [comment]
If this is in hardfork 13, where's the commit?

**Comment by bytemaster** [comment]
The commit was implemented before in a soft fork.
