### ISSUE TITLE
Minimum Account Usability

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#2488]
#1762 burns the account creation fee instead of powering it up into an account.

We have a couple of options.

1) We give all accounts a non-zero number of resource credits in the new bandwidth system.
2) We give accounts with 0 SP a hard cap of certain ops over time. (E.g. 1 transfer per day, 5 comments per day, 5 votes per day, 1 account update per day, etc.)

**Comment by clayop** [comment]
Brainstorming on those options:

Option 1 would provide more reasonable and manageable bandwidth policy but can hinder user experience when the network is congested as well.
On the other hand, option 2 provides a consistent user experience with predictability. But when bandwidth costs for a certain activity is higher than the preset hardcap, it can be a spam-attacking vector. Also, I think transfer(outbound) and vote are meaningless activities when an account has no SP.

How about combining those two? 1) Give non-zero number of resource credit equivalent to account creation fee, and 2) minimum activity credit of 1 comment. Hence, a user have at least a single-comment-right. If the comment he/she made consumes a part of SP credit so that there is leftover SP, he/she can make another comment or other activities.

**Comment by Gandalf-the-Grey** [comment]
I'm for 2) mostly because 1) can be very confusing for beginners as it strongly depends on external factors at certain point in time and can vary a lot.

**Comment by theoreticalbts** [comment]
The way I imagine this working is as follows:

- (1) For accounts created post-HF20 that burn fees, the bandwidth algorithm "pretends" the burned fee was turned into VESTS when the account was created, giving all post-HF20 accounts a base level of permanent resource credit regen from their (burned) creation fee.

- (2) Implement per-op-type caps as *delegation* restrictions:  If (faucet provider) Alice delegates to (regular end-user) Bob, Alice can place a limit of (at most) X transfers per day.  Any attempted transfers above the limit will not fail if Bob has enough SP on his own, but if Bob would be unable to exceed the limit without "help" from Alice's delegation, the transfers will fail.  Alice has discretion of which op types to restrict (for her delegations), allowing Alice to quickly implement policy changes unilaterally if necessary, and also tailor the restrictions to the particular UX she desires for users from her faucet.  Even though it sounds like this makes Alice a sort of gatekeeper, it's actually perfectly decentralized:  Anyone can delegate (i.e. function in the role of Alice), and Bob doesn't need delegation anyway (he always has the option of buying and powering up Steem, which gives him bandwidth he can use for any transaction he wants, so if Bob has enough SP, he's not "locked out" of any functionality even if no Alice chooses to give him extra free bandwidth).

**Comment by goldibex** [comment]
@mvandeberg @youkaicountry what do you think of @theoreticalbts's option 1? It seems cleanest in terms of both UX and implementation.

**Comment by mvandeberg** [comment]
It is the easiest to implement to get HF 20 done. This is all soft logic and can be fine tuned later.

**Comment by TimCliff** [comment]
One thing to keep in mind is how the implementation will handle the fact that the account creation fee will change over time. Will the blockchain be tracking the account creation fee at the time of each account creation?

**Comment by youkaicountry** [comment]
Work has been broken out into multiple issues. Closing.
