### ISSUE TITLE
double entries on appbase get_account_history

### ISSUE THREAD

**Issue by BhuzOr** [steemit/steem#2496]
Just one example, there are others both for my account and others account 

s = Steem(['https://api.steemitdev.com'])
```
>>> print(json.dumps(s.get_account_history('bhuz',567518,1),indent=4))
[
    [
        567517,
        {
            "trx_id": "0000000000000000000000000000000000000000",
            "block": 22337509,
            "trx_in_block": 4294967295,
            "op_in_trx": 0,
            "virtual_op": 4,
            "timestamp": "2018-05-11T13:19:45",
            "op": [
                "curation_reward",
                {
                    "curator": "bhuz",
                    "reward": "4367.999036 VESTS",
                    "comment_author": "steempostitalia",
                    "comment_permlink": "postit-n-71"
                }
            ]
        }
    ],
    [
        567518,
        {
            "trx_id": "0000000000000000000000000000000000000000",
            "block": 22337509,
            "trx_in_block": 4294967295,
            "op_in_trx": 0,
            "virtual_op": 4,
            "timestamp": "2018-05-11T13:19:45",
            "op": [
                "curation_reward",
                {
                    "curator": "bhuz",
                    "reward": "4367.999036 VESTS",
                    "comment_author": "steempostitalia",
                    "comment_permlink": "postit-n-71"
                }
            ]
        }
    ]
]
```

**Comment by mvandeberg** [comment]
Can you post more examples?

**Comment by mvandeberg** [comment]
I have a theory about what is going on...

First, some observations:

Syncing a local node from scratch does not seem to replicate this behavior.
`steemd.steemitdev.com` has duplicate entries.
`steemd.steemitstage.com` does not have the same duplicate entries (I am assuming it has some, but I've confirmed that some duplicates on dev are not present in staging).

The problem is with how the last irreversible block is updated within the context of the fork db. We think of the LIB as an monotonically increasing value that is independent of the current fork. While it effectively behaves this way because we only switch forks when the other fork existing beyond the LIB, the state to get us there may have a lower LIB, and would apply all signals, vops, etc. on the way there. This is not a problem for Chainbase due to undo states, but it is a problem for RocksDB, which currently only tracks state LIB and older.

Let's say the LIB is 100 and in block 100 Alice transfers 20 STEEM to Bob.
The current head block is 116 and we have a competing block for 116.
LIB for block 115 is 99, so when we apply the competing block 116, the notice for block 100 becoming irreversible is sent again, along with the transient state that existed, causing Alice's transfer in block 100 to be written to RocksDB a second time.

The solution is for RocksDB to track the LIB and only accept new state in history.
