### ISSUE TITLE
StatsD P2P Request Latency

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#2510]
The latency between requests in p2p should be measured.

Acceptance Criteria:
- [x] Time should be measured
- [x] Data should be sent via StatsD plugin

**Comment by mvandeberg** [comment]
The challenge for this issue is that single requests can (and usually) result in multiple responses. Do we want to measure the latency of the first received response for a particular message? This will best capture the actual latency of the response rather than compute time on the peer to create and send multiple messages. Perhaps it is best to record the latency between the first and the last message in a request.
