### ISSUE TITLE
if( !find< dynamic_global_property_object >() ) genesis block creation

### ISSUE THREAD

**Issue by lopugit** [steemit/steem#2525]
I'm having trouble understanding how this line works? https://github.com/steemit/steem/blob/master/libraries/chain/database.cpp#L112

I can't seem to find the `find` function decleration. And the `!find()` seems like it will always return true, what is actually happening here may I ask?

And is it the case that the genesis block is created on this condition?

**Comment by mvandeberg** [comment]
`find` is a method of the parent class `chainbase::database`.

This simply checks if the database has been opened before. `init_genesis` sets pre-genesis state. It creates necessary objects to run the blockchain and the init miner account to produce the first block. Think of `init_genesis` like block 0 or the bootloader for the Steem blockchain. Because `init_genesis` creates the dynamic global property object, we use its existence as a check if we are opening a new or existing database.
