### ISSUE TITLE
Dockerfile includes a git submodule line which breaks building if using git worktrees

### ISSUE THREAD

**Issue by lopugit** [steemit/steem#2576]
So there's the submodule git line in the Dockerfile,

if you're someone like me who uses `git worktree` then when Dockerfile does `ADD . /usr/local/src/steem` it only copies a `.git` file which has a `gitdir: /your/git/dir` line but since you only copied the context directory, you don't actually get the git repo files, so running the submodule line gives a `not a git repo /your/git/dir` error

to get around this I commented the submodule lines in Dockerfile and just installed the submodule before building. 

I tried to add a patch which checked if .git was a file, but you can't `ADD` directories outside the context with Docker so..... doesn't really work

**Comment by lopugit** [comment]
ah ok there's lots more errors in building, to do with the `git_revision.cpp` file, and I'm sure there's more to come, maybe it's just not a good idea to build in a worktree based git repo

**Comment by mvandeberg** [comment]
We've removed submodules entirely in `0.19.10` and have vendored git dependencies.

I'm not sure why using git worktreees in the Dockerfile is so important because it is a completely obfuscated build process. If you want to modify the Dockerfile for your personal use, you are free to do so, but we will not provide support for problems encountered doing so.
