### ISSUE TITLE
Implementation of expiring market orders

### ISSUE THREAD

**Issue by Smittyvb** [steemit/steem#2579]
In a [Steemit Inc. blog post](https://steemit.com/steem/@steemitblog/blockchain-update-3-hardfork-20-and-release-19-4-appbase-statsd-and-rocksdb), they described how orders would expire after 28 days. Order expiration after 28 days can be implemented in several ways.
## Option 1
Softfork to ignore transactions with too long of an expiration time.
- - - -
**Pros:**
- Can be implemented immediately, before HF20
- Witnesses can change the 28 days value
**Cons:**
- Existing orders are kept, as removing them would require a hardfork 
- All 100 witnesses must update (or at least enough to make it so block times for trades with long expirations is unbearable)
## Option 2
*Same as option 1, but a hardfork.* Hardfork to ignore transactions with too long of an expiration time. 
- - - -
**Pros:**
- Witnesses would be updating anyways
- It’s okay if not all witnesses update
**Cons:**
- Existing long-expiring orders are kept
## Option 3
*Same as option 2, but removes old orders.* Upon HF20, hardfork to ignore transactions with too long of an expiration time. Set all orders with an expiration date of more than 28 days after being broadcast to an expiration time of 28 days after broadcast.
**This will mean:**
- An order placed more than 28 days before HF20 will be instantly removed on the first block of HF20
- Orders that are placed between 0-28 days of HF20 that have an effective expiration date of less than 28 days will be untouched 
- Orders that are placed between 0-28 days of HF20 that have an effective expiration of more than 28 days would have their expiration set to 28 days from their broadcast
- Orders that are set to never expire before HF20 (this includes all orders made from Condenser) would have their expiration set to 28 days from their broadcast
- Orders placed after HF20 will have an expiration date of 28 days or less from broadcast time
- - - -
**Pros:**
- Witnesses would be updating anyways
- It’s okay if not all witnesses update
- Removes old orders
**Cons:**
- Force-expiring old orders might surprise people
## Option 4
*Same as option 3, but softfork against old orders, instead of hardfork* Softfork to ignore transactions with too long of an expiration time. Upon HF20, hardfork to set all orders with an expiration date of more than 28 days after being broadcast to an expiration time of 28 days after broadcast. 
- - - -
**Pros:**
- Removal of long-expiring orders can be implemented immediately, before HF20
- Witnesses can change the 28 day value
**Cons:**
- Existing long-expiring orders are kept until HF20
- All 100 witnesses must update for the soft-fork component (or at least enough to make it so block times for trades with long expirations is unbearable)
## Option 5
Something else I haven’t thought of.

Personally, I believe option 3 is the best approach. Getting 100% for softforks is hard, and removing old orders will help a lot with increasing node performance, and market performance

**Comment by mvandeberg** [comment]
What we implemented is a pre-HF 20 hardfork of sorts that does not impact orders until after HF 20.

Based on the compiled in hardfork time, order expirations before the hardfork are clamped to the hardfork time plus 28 days. After the hardfork goes in to effect all new orders will have a max expiration of 28 days.

We chose this method because it is lazy. But that is not a bad thing. In hardfork 17 there was a change in how comment cashout times were calculated. It took a good machine more than the 3 second block interval to process this change, which lead to missed blocks and some minor instability in the blockchain for the next minute after the hardfork took place. If we did any such transformation on limit orders then anyone could create unfillable limit orders (price 0 or infinity) with no expiration that need to be transformed at the time of the hardfork. Limit orders are relatively cheap from a bandwidth perspective and an attack of this form would be relatively simple to pull off. We would like to avoid this. There are database schema changes in `0.20.0` that require reindexing the blockchain. We can put this logic in the reindex and amortize it through the existing reindex time (this doesn't increase replay time by any noticeable amount).
