### ISSUE TITLE
30 day payouts seem to drop consistently over time to very low values

### ISSUE THREAD

**Issue by aaroncox** [steemit/steem#258]
I just wanted to bring the topic up of the 30-day payout periods and potential strangeness around them.

I've been watching a post (one of mine). After the 12-hour payout, within the next 12 hours, it received an upvote bumping the 2nd payout to around ~150 SBD. 

It's now 5 days later, this payout has now dropped to ~80 SBD. At the rate it's decreasing, I wouldn't be surprised if by the time it hits 30 days and does the 2nd payout, that payout will be a small fraction of this, thus rendering the 30 day payouts very ineffective. 

This may be by design, I'd be curious to know. This also may be an unintended side effect of adding the 30 day period - which is why I'm bringing it up for discussion :)

**Comment by mvandeberg** [comment]
This happens to all posts. When an account votes it grants rshares that are a function of the account's Steem Power and current voting power. When a comment is paid out, the payout is calculated based on the comment's rshares compared to the total number of rshares on all posts. If a comment gets a single vote and other comments continue to receive votes, the proportion of the reward pool the original comment would receive decreases slowly over time, even though it has the same number of rshares. I voted on some posts this morning that had a payout of $8 or so, and they are down to $6 now. They still have the same number of rshares, but because other posts have received more, their slice of the rewards is smaller.

Steemit.com always calculates the displayed payout as the pending payout if this comment were to be paid out right now. This is subject to change as votes on other posts can effect the final payout. We are aware of the cognitive dissonance between the underlying rshares mechanism and the displayed Steem Dollars and are constantly thinking through ways of improving Steemit.com.

**Comment by aaroncox** [comment]
Thanks for taking the time to answer! I understand it happens on all posts, and how it works, I was just curious if it was an intended design once we changed to 30 day payouts. I apologize if this post came off related to my personal activity on the site as a user, I simply cited it as an example, and it could have used a number of other pieces of content.

> We are aware of the cognitive dissonance between the underlying rshares mechanism and the displayed Steem Dollars and are constantly thinking through ways of improving Steemit.com.

That's exactly my goal here too, to help improve the experience of users. I think the cognitive dissonance is enhanced by the fact that the 2nd payout window is 30 days. A lot of things happen through that period of time, and I'd argue it may be way too long.

What I'm curious about is why was it changed to 30 days? Was it a performance improvement at the expense of user experience? Is there an economic reason to help distribute funds more evenly to more users? There was a reason behind this change (I hope) and I'm curious to know more behind the reasoning.

Right now there's a small part of the user experience that's somewhat poorly perceived, and I hoped to spark some discussions on how that could be remedied.

**Comment by roadscape** [comment]
Hi @aaroncox, iirc: in the beginning, there were unlimited payouts, and each was 24-hour vote weighed. Then it was determined that unlimited payouts presented certain challenges, so it was limited to 2. But to have the 2nd payout window be so narrow would not give it enough time to pick up votes, so it was widened to 30 days.

As I understand it, posts in their 2nd payout would *not* be losing their share of the reward pool, if voting activity was consistent throughout the 30 days. But in cases like the last 1-2 weeks, there has been an uptick in voting activity.. an "acceleration" of rshares distributed, which dilutes other posts. Likewise, if there a a deceleration in voting, pending payouts would rise. 24-hour payouts are susceptible to the same thing, but it's much more noticeable with the 30 day windows. Perhaps the window could be shorter.. or perhaps this is only an issue in times of rapid growth :)

**Comment by aaroncox** [comment]
Hey @roadscape, I've been meaning to reply to you for a couple days now. Thank you for taking some time to explain a bit of the logic behind it. Like I said, my main goal was to bring up the discussion about whether 30 day actually made sense with the current structure due to it's confusion. It sounds like these discussions have happened already though, so I'll trust in the decisions made.

I'm primarily just trying to get as much background as possible about the directions everything is heading. I'm a curious bastard :)

**Comment by mvandeberg** [comment]
All posts have a minimum payout requirement of $0.02. Under the unlimited payouts over 24 hours most old posts never got above $0.02. We decided to increase the window to 30 days but to freeze the discussion after that time. This would allow a post to accumulate more than $0.02 and receive something. If posts are still not receiving anything then we either did not meet our design goal for the change or the posts simply to not get enough votes to be paid and there is nothing we can do to help them get paid. This particular behavior is not a problem per se; we can't take something from a post that would have had nothing. Even if it gets paid a few cents, it is infinitely more than it would have been paid otherwise.

**Comment by samupaha** [comment]
> If posts are still not receiving anything then we either did not meet our design goal for the change or the posts simply to not get enough votes to be paid and there is nothing we can do to help them get paid.

Both Steem blockchain and Steemit.com have an effect on payouts. The blockchain is the backend that calculates the rewards, but Steemit.com has also quite big effect. It decides what users see, and if users don't see old content, they don't vote for it.

I can't say what is the optimal reward timing system for blockchain and what is the optimal way of showing the content for users, but I encourage developers to keep in mind that there are these two important parts in the puzzle.

If there should be more votes for old content, maybe the best way would be to show a new kind of feed for old content that user would probably like but haven't seen.

**Comment by mvandeberg** [comment]
We are aware of both of these pieces of the puzzle. Steemd already supports a trending30 ranking that is trending but for payouts in their second payout. Due to the fast nature of our development, steemit.com development is not always caught up with the development of steemd, but we are planning on adding that ranking to steemit.com. Additionally, feeds provides a great way of looking at content which you are interested. You can follow authors you like and pull up a feed of just their content. You are free, and encouraged, to vote on their content that has already been paid once.

**Comment by roadscape** [comment]
Posts in their second payout can be seen here: https://steemit.com/trending30/

**Comment by abitmore** [comment]
Because no curation reward for voting on a post after first payout, few people bother voting on them.
