### ISSUE TITLE
Question about SBD

### ISSUE THREAD

**Issue by kirkins** [steemit/steem#2582]
So say steem market cap is $500 million and we print the max $50 million in SBD.

What happens if the market cap goes to $45 million while those SBD are still floating around?

It seems it would be impossible to pay out more STEEM than would be in existence no?

**Comment by kirkins** [comment]
Even if marketcap was higher it could be easy to have a situation where the only way to honor a large SBD conversion would be through increasing the ~9% inflation rate?

**Comment by TimCliff** [comment]
This is explained in the whitepaper:
https://steem.io/SteemWhitePaper.pdf

See the section on sustainable debt to ownership ratios.

**Comment by kirkins** [comment]
Thanks @TimCliff, so this would the relevant bit:

> If the amount of SBD debt ever exceeds
> 10% of the total STEEM market cap, the blockchain will automatically reduce the amount of STEEM
> generated through conversions to a maximum of 10% of the market cap.

Let me know if my interpretation here is right.

We take 10% of the marketcap and divide that by the amount of SBD in circulation.

$100 marketcap
$20 SBD cirulation

Converting 1 SBD to STEEM = (100 * 0.1) / 20 = $0.5

Thus at 20% debat ratio converting an SBD would get you $0.50 worth of STEEM?

Does that sound right?

**Comment by TimCliff** [comment]
Yes

**Comment by kirkins** [comment]
@TimCliff so once conversion starts trending below $1 worth everyone will have the incentive to convert SBD as soon as possible. Since it's better to get $0.95 worth than $0.90.

If everyone converts at once and block producer rewards also create inflation won't the inflation rate be pushed over 9% per year?

**Comment by TimCliff** [comment]
Not necessarily on the first question. Converters may be better off waiting for the STEEM marketcap to increase or other converters to reduce the SBD supply so that conversions go back to $1. It is speculation.

The inflation from block producers is fixed. The inflation from SBD conversions is variable over the short term, but should average out to the projected inflation rate over the long term. If converters are converting when the debt ratio is above 10%, then the black is actually producing _less_ STEEM (than if it were <= 10%) so that would be _better_ for inflation.

**Comment by kirkins** [comment]
@TimCliff thanks for the explanation. I understand now
