### ISSUE TITLE
Automated Action Framework stubs

### ISSUE THREAD

**Issue by mac128k** [steemit/steem#2681]
Create stubs for automated action framework.

Acceptance:
- [x] static_variant
- [x] Block extension

**Comment by theoreticalbts** [comment]
I like having one header per class.  This has several benefits:

- Keep the complexity of a single file low enough to be easily comprehensible
- Make dependencies more explicit
- Speed compilation by including only what you need

This PR combines multiple notification headers into one.

A couple remaining minor issues:

- `post_apply_action_handler` says `"<-transaction"`, should this be `"<-action"`?
- Needs code to reject automated actions on mainnet.  (Also noted in #2683, so it is probably better to fix it in that PR, then rebase this PR.)

**Comment by mvandeberg** [comment]
> I like having one header per class. This has several benefits:
> 
> - Keep the complexity of a single file low enough to be easily comprehensible

I dare anyone to say that the notification header file is not easily comprehensible.

> - Make dependencies more explicit

Anyone needing to use the notifications is going to include `database.hpp` because that is where they register their handlers. `database.hpp` includes all of the individual headers.

> - Speed compilation by including only what you need

Again, anyone compilation unit that would have included any one of the notification headers would have also included `database.hpp`. I am not using this as an excuse to make `database.hpp` larger than it already needs to be. Your first point makes a solid argument for having the notifications in a separate file. We are talking about a 50 line header being too complicated...
