### ISSUE TITLE
Automated Action Validators

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#2720]
Validators for automated actions should be written.

Acceptance Criteria:

- Automated actions should require a validator.

**Comment by mvandeberg** [comment]
The validator interface is stubbed out. It is left to the implementor of each action to create the actual validators.

**Comment by mvandeberg** [comment]
https://github.com/steemit/steem/blob/9b3b9ef22afdeac055ba808667ee29e4744d90a2/libraries/chain/database.cpp#L910-L942

Any action that does not implement `validate` will cause compilation to fail because of templating.

**Comment by mvandeberg** [comment]
`process_optional_actions` also calls validate.

https://github.com/steemit/steem/blob/83d33ce8bbee036670de04d792f9f12b27461bad/libraries/chain/database.cpp#L3454-L3477

It is not needed in `process_required_actions` because all required actions must be contained in local state which means they were validated on push.
