### ISSUE TITLE
Automatically Exclude Witnesses that are Inactive

### ISSUE THREAD

**Issue by bytemaster** [steemit/steem#278]
Any witness who misses a slot and hasn't produced in the last 24 hours will be disabled until they update their block signing key. 

Any witness who does not want to produce blocks can set their block signing key to the null public key and they will no longer be scheduled.

This change should increase the reliability of the network by reducing the number of missed blocks by witnesses that we know are not going to produce or that are extremely unlikely to produce.

A runner up witness who produces at most once per day and misses their slot for any reason will have to automatically update their block signing key.  The witness node should be able to detect that the witness is currently disabled and automatically broadcast a transaction if it is still alive and ready.  This shouldn't impact most users who produce blocks many times per day.

Reducing the number of missed blocks will reduce the false positive rate for reporting network failure on broadcasting transactions.

**Comment by bytemaster** [comment]
Minor update, rather than 24 hours, it would be STEEMIT_BLOCKS_PER_DAY.  This makes it scale with participation rate.  If there is a low participation rate it will take 48+ hours before one of the top 19 would be disabled.  

Having a delay before witnesses are automatically removed from the schedule contributes to blockchain security by making it difficult to produce a longer chain by booting the top witnesses.  In an extreme network event the undo buffer should expire (leaving the blockchain dead) long before an attacker could start producing an alternative chain.

**Comment by abitmore** [comment]
Runner up witness without a good signing key shouldn't be skipped this way ([this code](https://github.com/steemit/steem/blob/408d667c9ab40eeee442e9240b6203eaf88da3e2/libraries/chain/database.cpp#L1145-L1146)), because it will not be put into `processed_witnesses` which then will be processed in [this code block](https://github.com/steemit/steem/blob/408d667c9ab40eeee442e9240b6203eaf88da3e2/libraries/chain/database.cpp#L1158-L1179), so current implementation will probably cause some virtual lap overflow issue. 

Instead, we should put the signing key check into [this code block](https://github.com/steemit/steem/blob/408d667c9ab40eeee442e9240b6203eaf88da3e2/libraries/chain/database.cpp#L1150-L1155).

**Comment by abitmore** [comment]
Pull request submitted: #343 . Still needs testing.

**Comment by abitmore** [comment]
[This code](https://github.com/steemit/steem/blob/408d667c9ab40eeee442e9240b6203eaf88da3e2/libraries/chain/database.cpp#L3065-L3071) updates signing key of miners as well, which imo is not good. Miners should be allowed to miss blocks especially when mining with lots of accounts, otherwise they will probably batch updating signing key of all miner accounts periodically which will lead to trx spamming.

**Comment by theoreticalbts** [comment]
The point of this is that if you miss a block, you're offline, so the network shouldn't expect you to produce until you confirm you're back online, and the way you confirm you're back online is updating your signing key.  It's not tx spam because the tx does serve a purpose, namely, confirming your block producing node is online.

Mining and block signing are really far separated in Steem compared to other cryptos.  You can have one node which only finds and broadcasts PoW's, and a signing node which is what actually creates blocks.  If your signing node goes offline then the network *should* stop accepting your PoW's until the signing node's back up.

Maybe we should create a virtual op when you go offline, and add an `is_online` state flag to the witness object.  Then anyone who notices `is_online` is false should investigate why their signing node is down, and re-enable the node.

**Comment by abitmore** [comment]
With current code, the issue with miner witnesses is: if a miner witness missed a block, its signing key will be nullified, but it's not skipped while scheduling, so it will miss more blocks definitely.

We should either add some skipping logic in [this code block](https://github.com/steemit/steem/blob/f19a72f45246a67bfcfbe7a3e4d2e064e7e389cc/libraries/chain/database.cpp#L1116-L1134), or reject new pow2 transactions submitted by it when it have no valid signing key (as @theoreticalbts mentioned above).

**Comment by abitmore** [comment]
Pull request submitted: #346 . Still needs testing.

**Comment by abitmore** [comment]
For better participation rate, I propose:
* rather than skipping a witness when no production in STEEMIT_BLOCKS_PER_DAY, we can do it after "X block missed in a row". X can be 10-15 for top-19 witnesses or 3-5 for non-top-19 ones.

With this design, we have these advantages:
* it's faster to exclude failed top-19 witnesses and top runner up witnesses, no need to disapprove them which is usually hard to achieve the goal
* it's fairer for runner up witnesses with fewer votes and miners with lower hashing rate, whose interval to produce blocks were more than 24 hours, in case when they occasionally missed a block due to networking issue or fork resolution.

**Comment by mvandeberg** [comment]
This has been merged and is working on the blockchain. While it still needs testing I am going to close this in favor of testing it via our desire to increase our test code coverage.
