### ISSUE TITLE
Account History API returns BAD and RANDOM results

### ISSUE THREAD

**Issue by skzap** [steemit/steem#2825]
`curl --data '{"jsonrpc":"2.0","method":"call","params":["condenser_api","get_account_history",["dtube",-1,0]]}' https://api.steemit.com -s | jq -r`

Run this call, it sometimes returns different output even though there was no new transaction for this account and the last reported operation is the same.

![https://i.imgur.com/pE0WI1T.png](https://i.imgur.com/pE0WI1T.png)

Also, the trx_id is equal to 0000000
And the trx_in_block is absurdly high and therefore wrong

**Comment by theoreticalbts** [comment]
This is actually expected behavior.  What you're seeing is a *virtual op*, it records various "indirect" effects, for example the various types of rewards.  Virtual ops aren't contained in transactions, so `trx_id` and `trx_in_block` are null sentinel values (zero and `2^32-1`).

Post rewards are one of the things that happen in virtual ops.  For a complete, up-to-date list of virtual ops, see [operations.hpp](https://github.com/steemit/steem/blob/develop/libraries/protocol/include/steem/protocol/operations.hpp) where it says "virtual operations below this point."

**Comment by skzap** [comment]
Ok whatever about the `trx_id` and `trx_in_block`, these operations are triggered by the blockchain itself, so I can understand why they are different.

However that doesn't explain the bug with the `transaction_id` returned being different on the same call.
