### ISSUE TITLE
Separate required vs optional automated actions

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#2884]
[PR 2866](https://github.com/steemit/steem/pull/2866) implements required and optional actions with a single object type.  If we implement them as separate object types, we can use each object type's `by_id` index.  This allows us to get rid of the `by_required` index.  Reducing the number of indexes by one should increase performance and decrease memory usage.

Requirements for this issue:

- Discuss whether this is something we should do.  If not, close this.
- If we should do it, implement it.  Preferably this should be done before code that walks or otherwise interfaces with the list of actions.

**Comment by mvandeberg** [comment]
The reason they were made in to the same index was to reduce code repetition while processing the actions. I don't think one implementation or the other is going to have a significant enough impact on performance to make either implementation significantly better than the other. 

However, readability does impact maintainability of the code. It is my opinion that we should use the solution that is easiest to read and understand so long as there are no major impacts on performance for doing so.

At this point I am not sure what all will be involved with the refactor or exactly how it would look. I can do the refactor as part of the work and go with what one feels best. My initial implementation was my gut reaction of what is most readable, but my gut might have been wrong.

**Comment by mvandeberg** [comment]
I was in the process of re-writing the queue into separate required and optional actions and if we go with this change I think it makes sense to have required and optional actions separated in the block as well.

The idea behind having them combined was so that they could be in a single static variant and the same set of visitors could be used for both. However, one of the most common visitors I am using is one to determine if the actions is required or optional. I think it makes more sense to separate required and optional actions at compile time.

**Comment by mvandeberg** [comment]
We have made the decision to separate out required and optional actions to simplify corner cases. Result of this issue is re-opening #2681 to add the additional stub.
