### ISSUE TITLE
get_comment does not return values for  net_rshares, abs_rshares, vote_rshares

### ISSUE THREAD

**Issue by VIM-Arcange** [steemit/steem#2887]
Calling get_comment() return 0 for `net_rshares`, `abs_rshares`, `vote_rshares` for some posts older than 7 days.

ex: `https://api.steemjs.com/get_content?author=arcange&permlink=steemit-statistics-20180902-en`

Surprisingly, get_comment() still return a negative value for net_rshares if the post has flags only 

ex: 
`https://api.steemjs.com/get_content?author=yeahlikes&permlink=supersuitbringssuperplay-wrgyi43hvx`
`https://api.steemjs.com/get_content?author=mundari&permlink=participate-in-the-cleanplanet`

The last one returns:
```
...
  "depth": 0,
  "children": 3,
  "net_rshares": -244642471601,
  "abs_rshares": 0,
  "vote_rshares": 0,
  "children_abs_rshares": 0,
  "cashout_time": "1969-12-31T23:59:59",
...
```

Is this behavior normal?
If yes, is there any way to get the value without parsing `active_votes` and re-doing the computing "manually"?

**Comment by mvandeberg** [comment]
It returns the values that are on the comment in the database. Because the comment was paid out those values are now 0. However, posts with flags still retain the negative rshares. This is behavior carried over from when there were two payout periods.

Having votes in `active_votes` for the API is actually not intentional. There is a build option `CLEAR_VOTES` that when set to `ON` proactively clears old votes on payout. When set to `OFF` votes will be lazily deleted when new ones come in. Depending on how the API node you're connecting to is configured can give you different results.

**Comment by VIM-Arcange** [comment]
I know about the `active_votes` and the `CLEAR_VOTES` build option.

I guess your explanation about the values being reset to is related to the following code:
https://github.com/steemit/steem/blob/d6b72501edbbb5022fb9c9d3ca066869055d2a6a/libraries/chain/database.cpp#L1930

And as this behavior is "by design", I will have to go the hard way and recompute values if needed.
