### ISSUE TITLE
Account claim improperly calculated cost resulting in enormously negative RC balance

### ISSUE THREAD

**Issue by netuoso** [steemit/steem#2963]
```
current_mana	-8,469,615,324,425,045
last_update_time	1,537,993,119
estimated_mana	-8,469,597,894,470,165
estimated_pct	-103933.31%
```

I was able to post when HF20.3 nodes came online. After that, I claimed a few accounts which seemed to be at little to no RC cost. Some time after that, my mana balance dropped well into the negatives making my account unusable.

**Comment by LKNX** [comment]
> After that, I claimed a few accounts which seemed to be at little to no RC cost.

Netuoso: It was not a few accounts, it was a shipload of accounts and your actions were completely selfish and greed based, and now you suffer the consequences for it.  

You just proved yourself  **not worthy** of being a steem witness with your lack of knowledge.

However, There is some good news.
In **0.20.4** it should only take you about **12 years to pay back and regain your credits**, in the meantime, you can peel potatoes or do something else.

This is your own fault, if you had read the code as you are supposed to do as a witness, or even informed yourself beforehand through our github, wiki, steem.chat or steemspeak, you would not be in this situation. I guess informing yourself is the problem here, so let me help you solve that at least;

**You can begin here:**
https://github.com/steemit/steem/wiki/Automatic-Actions-Framework

look at each of these wiki articles as mini steem whitepapers, because that is what you can define them as.

Once you are done reading/understanding the wiki, I expect you and other witnesses to actually publish your standards as we move forward, so it becomes more clear to the public how competent/incompetent witnesses in production are. That way, stakeholders can adjust their witness-voting accordingly.

**Comment by ajayyy** [comment]
710 accounts were claimed

**Comment by Smittyvb** [comment]
Couldn't this be exploited to create unlimited accounts, like so: Do these in the same operation:
- Account claims 2 accounts.
- Account creates 2 accounts

The account you do this on will lose all of **it's** RC, but you get one free account, and another free account which you'll drain the RC from, to continue to cycle.

**Comment by ajayyy** [comment]
How did the RCs come back?
