### ISSUE TITLE
count_resources() does not set result.resource_count[ resource_execution_time]

### ISSUE THREAD

**Issue by holgern** [steemit/steem#2972]
Inside the count_resources() function the array for resource_execution_time is not set.

https://github.com/steemit/steem/blob/master/libraries/plugins/rc/resource_count.cpp#L503

Something like
```
result.resource_count[ resource_execution_time ] += vtor.execution_time_count ;
```
is missing. 

A search https://github.com/steemit/steem/search?q=resource_execution_time&unscoped_q=resource_execution_time
showed that is not set somewhere else.

At the moment the RC costs does not depend on compute time.

The RC system uses two measurements to determine how much an operation should cost in terms of RCs: blockchain size, and state size. 

https://github.com/steemit/steem/blob/master/libraries/plugins/rc/rc_plugin.cpp#L292
`tx_info.usage.resource_count[resource_execution_time]` is always zero.

**Comment by bobinson** [comment]
Just to add to @holgern 's points, 


"Execution time. The amount of time stuff takes to run." is mentioned here https://github.com/steemit/steem/blob/master/doc/devs/2018-08-20-resource-notes.md

- Execution time of what ? ie, since there are no smart contracts right now, what exactly is being done ?
- Is there a plan to bring back the smart contracting feature (WREN or something else) ?
- Will the smart contract language be Turing complete ? Or is it going to be decided by the RC ?
