### ISSUE TITLE
Community - Are the default config values for RC and bandwidth checking correct?

### ISSUE THREAD

**Issue by TimCliff** [steemit/steem#3014]
If I build and launch a fresh instance of steemd, the config.ini file is auto-generated with the following defaults:

```
rc-skip-reject-not-enough-rc = false
witness-skip-enforce-bandwidth = false
```

Is this correct?

**Comment by roadscape** [comment]
Quadruple negatives are confusing, but I think it's meant to read as

`RC: skip "reject not enough RC" = false`
which reduces to
`RC: skip enforcement = false`
thus
`RC: enforce = true`

And

`witness-skip-enforce-bandwidth = false`
I guess means
`Bandwidth: enforce= true`

Which suggests both are enforced if I'm interpreting the names correctly.

**Comment by theoreticalbts** [comment]
Related:  https://github.com/steemit/steem/issues/2703

There's an actual problem here.  There's a known problem where the default `config.ini` generated in an empty `--data-dir` doesn't have a usable flag combination, contrary to what's specified in the code.  I searched, but I can't seem to find the exact issue number, so let's use this issue for that problem.

Upon reading the `boost::program_options` docs, I think the problem is caused by using `bool_switch()` instead of `value<bool>` for config file options.  I've located all places in the code, and changed them appropriately.  This should fix the auto-generated configuration file.

Here's the backstory on the naming:  The internal API for the `database` class has a bunch of flags that can disable parts of normal processing (for example, blocks read from local disk are assumed to be trusted, so no need to cryptographically check signatures -- we assume you checked them when you first downloaded the chain).

The `database` class flags are "skip flags," which have the semantics of:

- `false` -- do the usual, full checking
- `true` -- skip something for performance or other reasons

The flags exposed by the plugins follow the same rule:

- `false` -- do full checking of bandwidth and rejection of transactions that exceed it
- `true` -- skip checking bandwidth for whatever reason

The old bandwidth algorithm is going to be removed from the witness plugin, see #3006, so in some future release, only one of these flags will be relevant.
