### ISSUE TITLE
account_create_with_delegation_operation_exec_time  still needed?

### ISSUE THREAD

**Issue by gadrian78** [steemit/steem#3032]
I've found `account_create_with_delegation_operation_exec_time` in the `operation_exec_info` struct, inside
[libraries/plugins/rc/include/steem/plugins/rc/resource_sizes.hpp](https://github.com/steemit/steem/commit/5a5c67b8302c008353ab6e82951d6b696d0324d8#diff-3c750d6b482ec8ad60137989430cfdcf)
while looking at some merged code.

Is it still necessary, since account creation with delegation was dropped in HF20?

EDIT: I raised this issue thinking there might be additional code related to account creation with delegation that needs to be commented out/removed, not for this particular struct attribute.

**Comment by mvandeberg** [comment]
No, it is not needed, but there is no harm in leaving it there.

Regarding commenting out/removing code related to creating accounts with delegations: We cannot remove the code because steemd needs to be able to evaluate historical operations (including creating accounts with delegation) to arrive at the current state.
