### ISSUE TITLE
Account still able to comment while having a negative RC

### ISSUE THREAD

**Issue by quochuy** [steemit/steem#3073]
Not sure if it's a bug or it's normal but check this account:
https://steemd.com/@ammard

![screen shot 2018-10-16 at 2 43 09 pm](https://user-images.githubusercontent.com/310654/46991463-d4f23780-d151-11e8-9cae-33e6678bbfa2.JPG)

RC current_mana: -936,046,673,186
RC current_pct: -19292.27%

But he can still occasionally post his spammy comments, last one was 14 hours ago (from time of writing this issue).

**Comment by mvandeberg** [comment]
RCs are non-consensus. The way in which we've designed steemd prevents witnesses from producing blocks without adhering to the rules of RC. However, because Steem is open source, we cannot stop witnesses from running modified code. From the account's history it would appear that a time-share witness (not top 20) is allowing these operations in by running modified code.

**Comment by quochuy** [comment]
@mvandeberg 
I checked the blocks and I confirmed one witness was signing all his blocks with a modified v0.20.5 except for his last comment which was signed by a top20 witness running v0.20.6rc1. So I wonder if that top20 witness has also modified his steemd or is it now a bug introduced in v0.20.6.rc1

**Comment by lukestokes** [comment]
@mvandeberg I mentioned this in steemdevs, but maybe it got missed. Is v0.20.6rc1 letting negative RCs through? I've been running it as requested on the release notes, but I just turned it off as this doesn't seem right. Maybe this issue has already been noticed and addressed for a 20.6 release, but if not, should we take down the rc1 release if this is a bug? From my recent logs, here are some the accounts where I see log notices about negative RC (with counts of how often I'm seeing the entries come up):

| Account        | Count  |
| ------------- |:-------------:|
| furie | 160 |
| vegasteem | 116 |
| dingodan | 86 |
| patelincho | 64 |
| sojucaps | 61 |
| jrv1 | 52 |
| mielia | 51 |
| abc | 42 |
| mhsiemaszko | 30 |
| promoteme | 30 |
| anhvu | 22 |
| tantalala | 22 |
| mmckersie | 20 |
| resteemator | 19 |
| mindstabber | 16 |
| esteban | 15 |
| haccolong | 14 |
| balder | 12 |
| francis228 | 12 |
| ibiza | 12 |
| masterbeta | 12 |
| photocurator | 12 |
| teacher | 12 |
| shila | 10 |
| thehermitmonk | 10 |

**Comment by mvandeberg** [comment]
Any time we change the RC system, some of this is going to happen on one side or the other. If we have two competing non-consensus rulesets, A and B, the transactions that get included only have to pass A or B. And some of those transactions will fill for form not A, B. From an A node perspective, it looks wrong. The transaction shouldn't be allowed. When it is permissible by B.

With RCs this gets really tricky because if the new ruleset is more expensive than the other, then transactions allowed in prior are going to cost more retroactively than when they were included. This could lead to a poor user experience if they are suddenly out of RCs, or even negative, if they thought they still had RCs. To prevent this from happening, in 0.20.6, we reset the resource pools to 200% their equilibrium to tank the retroactive prices and prevent users from going negative. What this means is there are users that may be negative in 0.20.5 that aren't in 0.20.6.

To further complicate matters, 0.20.6 is more expensive for some operations and less expensive for others. Looking at the list of accounts, they appear to all have positive RC in 0.20.5. Your node is reporting that 0.20.5 block producers are letting in negative RC transactions.
