### ISSUE TITLE
Platform Independent State Files

### ISSUE THREAD

**Issue by youkaicountry** [steemit/steem#3084]
Write a platform independent state save / load system.

Acceptance Criteria:
- Command-line switch to launch a node into "saving mode" in which node processes to a given block, terminates, and writes state file
- State files are binary with JSON header
- Header contains list of active plugins, and hash of state affecting settings for each plugin
- Loading a state file checks the header against its own plugins / settings and halts if there is a difference
- State file writing code should append only, never seek

**Comment by mvandeberg** [comment]
Instead of having plugins add a hash of their options impacting state, I am having them upload the json of the state. This matches the methodology with the schema checking. It will aid in debugging and will provide a technical error message when state files are rejected.

For the flags, I am implementing the following.

`--stop-replay-at-block` is being renamed to `--stop-at-block` and will be expanded to terminate steemd at a particular block height in all modes of operation (instead of just steemd).

`--to-state` will save state whenever steemd exits (primarily used in conjunction with `--stop-at-block`, but could be used with a monitor script to send SIGINT at a particular block height or when a certain set of conditions are met.

`--replay` can be combined with the previous two in order to reindex to a particular block height and then generate a state file. 

We should add a feature that if the block height is less than the head of the block log, the node will go in to a resumed reindex mode. Some infrastructure is needed to be added to the reindex code so that if SIGINT is send during a reindex, it can cleanly shut down and resume. (#3519)
