### ISSUE TITLE
Reallocate lost rewards due to voting within first 30mn to subsequent voters: proposed solution is weight stake effect by time and not just payout

### ISSUE THREAD

**Issue by talerecursion** [steemit/steem#313]
The current system where lost reward is given to the author creates a race to the bottom because the incentives of voting later are a linear increase whereas the incentive for being first is an exponential increase, so it's almost always more profitable to be the first. Currently there are multiple bots fighting for the first rank on posts from popular authors. This creates a tragedy of the commons situation where most of the reward the post created is already distributed within the first 5mn (out of which more and more is just given away to the author) and people who vote "reasonably" at 30mn only get bread crumbs. This situation can't be reversed due to the lack of coordination between botters, meaning that a botter who decides to stop racing to the bottom will be financially penalized, even though all botters know that as a group, this behavior makes the curation pie shrink. 

From the authors perspective, although they receive more and more of the curation payout as these bots are getting closer to the posting time, it also damages their prospects of doing well on their post since voters motivated by curation rewards just give up trying to vote due to the concentration of stake that gets vote-stacked within the first 5mn. 

To fix this problem, there must be more incentives for waiting before voting, that is to say there needs to be something that compensates the slower growth of the linear time scale over the exponential growth of being the first to vote. One such incentive could be to reallocate the curation payout that users who vote earlier than 30mn forego: instead of giving it to the author and making the effective curation reward pool shrink day after day from 25% to a few %, it would make more sense to keep these foregone curation rewards as curation rewards and reallocate them to later voters. Exact mechanism to be discussed in this thread.

One solution could be to effectively reduce the effect of earlier votes on the whole voting process. Currently a whale who votes at the 6mn mark has her rewards multiplied by 20% but the effect of her vote is still 100%. It's the fact the effect applies fully that depletes subsequent reward opportunities. Instead of applying a timebased multiplier at payout time, it would be more simple and effective to apply the timebased multiplier to the amount of stake used for voting. So 1000M Vests applied at the 6mn would equiv to 200M Vests vote. This impacts negatively the success of the post, but because it also creates much stronger incentive to wait before voting, this should help maintain the economic viability and fairness of the curation activity much more than it impacts the success of posts. Actually, since anyway every post will face the same change of mechanics, this shouldn't really change anything at all for authors. Authors that are artificially kept at the top by bots will be more affected than author which receive organic votes, but that's actually a very good thing.

**Comment by mvandeberg** [comment]
I will leave the more mathematical response to this post to @theoreticalbts because he came up with the curve we are using, but the high level idea is this... Each user, regardless of when they vote gets a guaranteed portion of the rewards proportional to stake and then a chunk of the remaining rewards that varies based on the amount of stake backing the vote and the amount of stake in future votes. Early votes being rewarded more is intentional and desirable. Granted, there is a parameter we can tune that can make the curve favor time or can be fairer. It is possible that we need to favor time a little less to make voting early harsher, but I'm not sure. The lack of coordination of bots and the desire to vote early on content is creating a good race to the bottom on posts that users unanimously agree are worth something. In those cases, very little curation is needed, so why would the blockchain want to pay for trivial curation? Instead of rewarding more people for their trivial work, the blockchain rewards the author for making content that requires little curation. Think of it as a bonus for being a great author. The content that is not obviously good at first glance needs more curation and, more importantly, likely isn't easily curated by bots.

We are currently discussing ways to improve the curation rewards so that more content is curated and rewards are more evenly distributed. Your idea has spurred on a few other ideas for me that I will bring up to the dev team. Thank you for your feedback.

**Comment by abitmore** [comment]
A race to the bottom is still more attractive than zero curation reward for SP holders especially bots.

When bots are piling on articles of a few authors, it actually encourages human voters to look for other better contents, which is good imo. Actually, we should give even more weight to first voter, to discourage the all-pile-on-one behavior, then author reward will be distributed more widely, so better growth.

**Comment by iamsmooth** [comment]
> it also damages their prospects of doing well on their post since voters motivated by curation rewards just give up trying to vote due to the concentration of stake that gets vote-stacked within the first 5mn.

I don't understand this. If there is already a lot of stake there, then the author is already being rewarded.

If the argument is that the total voting on a post by a popular author ends up being smaller because  of the mechanism, that might be an undesirable outcome but it isn't clear why this would occur absent a clearer analysis. (The less early voting that occurs due to the cumulative effect of the penalty, the better the prospects are for later voters.)

On the other hand, if the goal is to spread out rewards, then popular authors getting less might even be desirable.

**Comment by talerecursion** [comment]
> I don't understand this. If there is already a lot of stake there, then the author is already being rewarded

This is seen from a rational agent's (e.g. a bot) perspective. An efficient bot will typically vote on a post at a point in time where it estimates (based on past performance) that future vote stake will greatly outweigh current vote stake. If a very large whale votes very early, this ruins every prospect for bots to get a good return for their vote, and rules out bot votes. If the whale that made the early vote is itself a bot, it won't affect much the result for the author, because anyway there is only that much stake bots will commit anyway as a group because they make reward calculations, and are exclusively motivated by profit. Other whales who vote for considerations other than profits will still vote anyway. It's when it happens the other way round that there is a loss of voting stake for the author. If a whale who votes manually happens to vote very early, for instance in the case of self-voting on posts, bots will typically pass on the post, and if this happens too often will even pass completely on the author. This is the case for @dantheman for instance: see [this post](https://steemd.com/steemit/@dantheman/steem-dollars-have-limits). Although @dantheman has a historical performance that would typically warrant botting, he isn't receiving large stake bot votes because the fact he self-votes makes his post unattractive for bots in terms of profit prospects. This is fine when the author is the one who self-votes, and a better understanding of bot incentives would easily allow authors with large stake to understand that they might be better off voting for themselves after the large bots have already voted. But when the early large vote is coming from a third party, the author stands to actually lose out on total voting staked against her post.

The tricky and unintuitive consequence is that, a whale who votes manually with the purpose of encouraging good content, might in fact end up hurting the overall success of a post by driving away bots if she votes too early whereas that wouldn't have been the case had she voted later.

**Comment by bytemaster** [comment]
An author with a solid rep and lots of followers is a "sure bet", there is no value in curating it and therefore it shouldn't be rewarded.  Race to bottom is desired goal.   

Curation is about discovering *new* content in unexpected places.  Not getting paid to point out the obvious.

Authors have *earned* a solid reputation which is what is being rewarded by the current system.
