### ISSUE TITLE
smt_token_object not failing check_reflect.py

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#3157]
`smt_token_object` is not failing check_reflect.py and it obviously should. Logs from CI says the object is ok. Below are the field and the reflection on `master` (3730a83)

https://github.com/steemit/steem/blob/3730a839d88ead9e28da1642359f7054c479496c/libraries/chain/include/steem/chain/smt_objects/smt_token_object.hpp#L74-L119

https://github.com/steemit/steem/blob/3730a839d88ead9e28da1642359f7054c479496c/libraries/chain/include/steem/chain/smt_objects/smt_token_object.hpp#L261-L281

Missing fields in reflection:

`cashout_window_seconds`
`reverse_auction_window_seconds`
`vote_regeneration_period_seconds`
`votes_per_regeneration_period`
`content_constant`
`percent_curation_rewards`
`percent_content_rewards`
`author_reward_curve`
`curation_reward_curve`

I do not know if this happening in other objects. This is the one I have observed.

**Comment by theoreticalbts** [comment]
I did a little digging.  We need to add `PREDEFINED = STEEM_ENABLE_SMT` to our `Doxyfile`, otherwise Doxygen can't see anything that is conditionally compiled with `#ifdef STEEM_ENABLE_SMT`.

With this enabled, bugs are reported in the following classes:

```
error:
steem::chain::comment_object
steem::chain::dynamic_global_property_object
steem::chain::smt_token_emissions_object
steem::chain::smt_token_object
steem::plugins::market_history::bucket_object
steem::plugins::rc::operation_exec_info
```

Note that the memory-mapped Boost multi-index container doesn't use reflection to persist objects, so you shouldn't have any visible issues even if you are running a `STEEM_ENABLE_SMT` build on mainnet.
