### ISSUE TITLE
0.20.6 Unlinkable Block P2P Issue

### ISSUE THREAD

**Issue by ScottSallinen** [steemit/steem#3180]
Many witnesses have noticed recently a lot of seemingly random missed blocks with little explanation. 

I tracked the issue to an exception that wasn't being caught properly here: 

https://github.com/steemit/steem/blob/75300afff53d850f777f46dab116591d9a1764c5/libraries/plugins/p2p/p2p_plugin.cpp#L216

Instead of catching the correct exception, it throws a generic one. If, due to a latency event, you get block N+2 ahead of block N+1, your client _/should/_ go back and request N+1. However when this exception is caught in a generic way it instead disconnects from that peer, and then one by one cascades to kill all your peers, then proceeds to find new peers to sync. (See this code path: https://github.com/steemit/steem/blob/75300afff53d850f777f46dab116591d9a1764c5/libraries/net/node.cpp#L3573)
This resulting time delay re-syncing is the likely source of these random missed blocks.

For the life of me I can't figure out why the derived exception isn't being caught correctly, but as a 'hack' it seems you can compare the FC code and perform the right action.
You can find a gist of this patch here:
https://gist.github.com/ScottSallinen/7ec83d3fcc4edca650137df875326ced

**Comment by mvandeberg** [comment]
Do you have logs of the error messages in question? There are a few key messages that would confirm this execution path.

**Comment by ScottSallinen** [comment]
I didn't save the logs (oops, part of the "bug fixed, close all tabs" process..), but I can point you to which log messages were produced.
When getting block N+2, the client spits out this message:
https://github.com/steemit/steem/blob/master/libraries/plugins/p2p/p2p_plugin.cpp#L229
Which is caught here:
https://github.com/steemit/steem/blob/master/libraries/net/node.cpp#L3576
And it disconnects the peer here:
https://github.com/steemit/steem/blob/master/libraries/net/node.cpp#L3600

When applying the workaround fix, I added a new elog message, wrapped in the `if (e.code() == 4080000)` which is visible when the event occurs. So it is indeed following the execution path I suggested.

**Comment by mvandeberg** [comment]
I have tracked down what the problem is. `FC_CAPTURE_LOG_AND_RETHROW` strips the exception type and rethrows as an `fc::exception`, but the code is a member of `fc::exception` and persists despite the type stripping. There isn't a good way around this in C++ other than your patch. The better solution would be to stop relying so heavily on exceptions as flow of control, but that would require a larger refactor to the steem codebase.

**Comment by abitmore** [comment]
@mvandeberg if `FC_CAPTURE_LOG_AND_RETHROW` called somewhere in the path would strip the exception type, the `FC_CAPTURE_AND_RETHROW` a few lines below would strip the type as well, then why the patch would work? https://github.com/steemit/steem/blob/0732c443be66f1ddbb118d9fede9de6637db02e2/libraries/plugins/p2p/p2p_plugin.cpp#L246

since the p2p code relies on the type as well: https://github.com/steemit/steem/blob/9b70fb6c89b0a856ab45d8841e62c262ba3927f9/libraries/net/node.cpp#L3569

Actually, I think the type got lost here: https://github.com/steemit/steem/blob/d2eef5725e4f3bb33e54c1ab48fe35c5debbf46f/libraries/plugins/chain/chain_plugin.cpp#L117

When assigning an object derived from `fc::exception` to an `optional<fc::exception>` object, a new plain `fc::exception` object rather than an object in the original type is created although the `code` is kept: https://github.com/steemit/steem/blob/a14abfa9841d5d31aa9240099d7912fe21ae6a9e/libraries/fc/include/fc/optional.hpp#L83

**Comment by yashbhavsar007** [comment]
This patch is not working in my case I got below exception and blockchain stopped after receiving this assertion it says unlinkable block.
`itr->vote_percent != o.weight: Your current vote on this comment is identical to this vote.`
 Please suggest something so i can resolve this issue reply is also not working for me for mode details please see #3413
