### ISSUE TITLE
1% SBD print rate despite the haircut

### ISSUE THREAD

**Issue by economicstudio** [steemit/steem#3184]
Despite the haircut, SBD is still being printed at 1% rate.

I made a detailed post here: https://steemit.com/utopian-io/@blockchainstudio/why-sbd-print-rate-is-still-1-despite-the-haircut-bug-report-explanation-and-suggestions
, where I explained in detail with suggestions.

**Comment by TimCliff** [comment]
It is related to the discussion here: https://github.com/steemit/steem/issues/3176

**Comment by oflyhigh** [comment]
* [Why is median_history_price no longer the median of feed price? My investigation.](https://steemit.com/witness-category/@oflyhigh/why-is-medianhistoryprice-no-longer-the-median-of-feed-price-my-investigation)
*

**Comment by ajayyy** [comment]
SBD from posts cannot end at 10%, it must end earlier or else SBD will continue to be printed FOREVER. SBD printing must revert back to the previous schedule.

**Comment by iamsmooth** [comment]
Reverting back to the previous schedule is certainly not needed. Other than changing the blockchain logic on how the cap is implemented, probably a change to the top of the print phase out range from 10% to 9.9% would be sufficient to stop it.

As it is, this is entirely irrelevant economically, although confusing and messy. A total of about 60-70 SBD per day are currently being printed (due to the bug). This is literally an effect of 0.000065% per day to the debt ratio and will never add up to anything significant, while at the same time, a minimum hundreds and usually many more (tens of thousands) are being destroyed daily by conversions, meaning the SBD supply is still _declining_ despite the extra 60-70 being printed (even when SBD was way over $1 and it made no sense to convert, even mistaken conversions might have been over 60-70 per day).

In no sense is this important enough for an emergency hard fork, if it is even worth fixing at all.

**Comment by economicstudio** [comment]
I agree with smooth most of the part. It's too late to change the current feed schedule back. Also, while this is a very important issue, It's not urgent at all in terms of impact, especially given that the resources that Steemit, Inc. currently have.

But I strongly believe that feed api information should be self-contained, i.e., provide 3 information: base, quote, haircut (or debt) ratio. (not just 2, which is again very inconsistent, current value is haircut, historical value is non-haircut) Then everything will be much clearer including the code.

It can be waited til next HF or any urgent update.  (maybe STEEM price will go up again before that :) So leave as it is rather than fixing it by a temporary measure (e.g., changing cap from 10% to 9.9%). But I think it should be fixed eventually even if it doesn't have big impact. This is unintentional outcome related to fund. If there is one, who can believe there is no other problem we don't know?

**Comment by TimCliff** [comment]
The only solution to this particular issue would involve a hardfork. 

There are other more broad and related issues pertaining to the price feed which are being discussed in https://github.com/steemit/steem/issues/3176.

**Comment by TimCliff** [comment]
I dug into this a bit, and it appears to be due a precision/rounding issue with this calculation:
https://github.com/steemit/steem/blob/9e83f66c85a2c76bef1a07cef7dd302d2c4be572/libraries/chain/database.cpp#L3772
https://github.com/steemit/steem/blob/9e83f66c85a2c76bef1a07cef7dd302d2c4be572/libraries/chain/database.cpp#L3773

Here are the details from head_block_num() `28574400`:

In `update_median_feed`, `gpo.current_sbd_supply` is `12711879941` and `gpo.current_supply` is `287725695797`. 

Based on that, the `min_price` calculation is `{"base":{"amount":"114406919469","precision":3,"nai":"@@000000013"},"quote":{"amount":"287725695797","precision":3,"nai":"@@000000021"}}` which gets saved to `fho.current_median_history`.

When it enters `update_virtual_supply`, the values are:
```
dgp.virtual_supply: {"amount":"319695217552","precision":3,"nai":"@@000000021"}
dgp.current_supply: {"amount":"287725695797","precision":3,"nai":"@@000000021"}
dgp.current_sbd_supply: {"amount":"12711879941","precision":3,"nai":"@@000000013"}
get_feed_history().current_median_history: {"base":{"amount":"114406919469","precision":3,"nai":"@@000000013"},"quote":{"amount":"287725695797","precision":3,"nai":"@@000000$
```

The (simplified) calculation for `percent_sbd` using the formula above is:
```
current_sbd_supply * current_median_history / virtual_supply * STEEM_100_PERCENT
```
which is:
`12711879941 * (287725695797 / 114406919469) / 319695217552 * 10000`

This _should_ result in `percent_sbd = 1000`, but it is resulting in `percent_sbd = 999`.

One potential solution would be to update this line of code:
```
         else if( percent_sbd >= dgp.sbd_stop_percent )
            dgp.sbd_print_rate = 0;
```
with a hardfork check that would start using this after the next hardfork:
```
         else if( percent_sbd >= dgp.sbd_stop_percent - 1 )
            dgp.sbd_print_rate = 0;
```

**Comment by economicstudio** [comment]
Whatever change will be made, please introduce a variable for the real debt ratio (current percent_sbd isn't for that) so that we can easily track down the problem. Also, please publish that too, in feed info, and steemd.com. I think at the steemd UI level, it's very easy job to show even now. Personally I believe it should be shown together under the haircut situation.

**Comment by TimCliff** [comment]
@economicstudio they are good suggestions. This specific issue though is just about the problem where SBD is incorrectly being printed when the debt ratio is >= 10%. The more broad discussion about how to improve the price feed (and other related info) is happening in issue #3176.

**Comment by TimCliff** [comment]
I dug into the precision issue a bit more, and determined that there is a slight loss of precision on this calculation: `dgp.current_sbd_supply * get_feed_history().current_median_history`. 

For block 28747200, the `current_sbd_supply` is `12539347394` and the `current_median_history` is `288615384506 / 112854126546`. The result of `12539347394 * (288615384506 / 112854126546 )` is technically `32068376056.2`, but `32068376056` is the result of the calculation.

When this gets put into `32068376056 / 320683760562 * 10000`, the result is `999.999999994`, which when converted into an integer is `999` (instead of `1000`).

I started going down the path of trying to see if there was a way to do the calculation in a way where the precision is not lost, but I determined that alone would not fix the issue. The reason is because the `virtual_supply` is only calculated once an hour, but the `current_sbd_supply` can change every block. (Even if the precision was fixed in the example above, it would only take a small amount of SBD conversions to put the `current_sbd_supply * current_median_history` value slightly below the `virtual supply`, resulting in a `999.XXX` number.)

I also found cases near the bottom of the price feed hour where enough SBD conversions had been done to push the calculation into `998.XXX`, resulting in a calculated debt ratio of `998` (instead of `1000`).

I propose shaving off `0.05%` from `sbd_stop_percent` when checking to see if it has passed the stop percent limit. This will account for both the rounding/precision loss, as well as a high amount of potential SBD conversions done between the hourly price feed samples.

The new check will basically be:
```
         else if( percent_sbd >= dgp.sbd_stop_percent - 5 )
            dgp.sbd_print_rate = 0;
```

I will submit a PR for this with a HF check.

**Comment by iamsmooth** [comment]
I see this issue as very low impact and do not think it urgently needs to be fixed (and would instead suggest updating the documentation, at least for now). I would only support fixing it in a hard fork if the developer team is very confident that there are sufficient resources for careful review and testing (and in addition that this would not delay or place at risk other changes in the hard fork with far greater benefits), otherwise I do not see the risks of the change being outweighed by the benefits from the change.
