### ISSUE TITLE
Bug in wallet.cpp for main.network chain_id

### ISSUE THREAD

**Issue by prateektiwari7** [steemit/steem#3211]
Hi Steem team 

Please remove the bug in the main.cpp file. It is working only for testnet network. 
Please edit the code for the particular chain_id when user pass it to call and broadcast transaction. 

Suppose I created my chain_id. Steem code is made to pass only chain_id as all zeros. If I need to pass the my chain_id that code must needs to work according to that.

/programs/cli_wallet/main.cpp

**Comment by mvandeberg** [comment]
Being able to set the Chain ID via command line args is purposefully only enabled on a test net build.

There is a good reason for this. Changing the Chain ID is not the only thing that needs to happen to start a new Steem Blockchain. The way in which we handle hardforks has changed. The first few (I believe four) hardforks have hardcoded times whereas later hardforks are all voted on by the witnesses and apply only after a super majority have confirmed the hardfork date.

It is not difficult to start a new blockchain, but tricky and incompatible with the main network. We need the ability to do so for our test nets, which is why that behavior only exists in a test net build. If you're building for source, the CMAKE option is `-DBUILD_STEEM_TESTNET=ON`.

Likewise, setting the wallet's Chain ID is only enabled in a test net build. There are also reasons for this. The core Steem asset symbols (STEEM, SBD, and VESTS) have hardcoded serializations. We use different asset symbols for STEEM and SBD on the test net, TESTS and TBD respectively to help users know they are operating on the test net vs the main net. It would be truly unfortunate for a user to send STEEM on the main net when they thought they were operating on the test net.

**Comment by prateektiwari7** [comment]
Hi @mvandeberg ,

I am not talking about testnet here. I already run my chain (with my chain_id) on the main network.
I created my own blockchain by changing your token name it's easy. I am not creating testnet network. I want to fix the bug there. I already did that in my code. Please make it open for private network when user created its own chain_id in the config.hpp file. 

The steem chain is not Passing the `**Chain_id**` for that developer that wants to create his own private network. I dont want to use `**-DBUILD_STEEM_TESTNET=ON**`. I build it from scratch and found that. To broadcast the transaction you need Chain_id and code is passing all zero by default.

You must need to change the code when a user wants to create his own private network.
