### ISSUE TITLE
remove support for the old standard C++ 

### ISSUE THREAD

**Issue by kotbegemot** [steemit/steem#3224]
The [mira](https://github.com/steemit/steem/tree/mira-steve) has support for C ++ 98.
Let's remove support for the old C++ 98 standard.
Adapting is not difficult, you need to cut a macro family BOOST_NO_CXX11*.
Example : https://github.com/steemit/steem/blob/mira-steve/libraries/mira/include/mira/multi_index_container.hpp

**Comment by mvandeberg** [comment]
Thank you for your interest in the work being done on MIRA. Since you've been following the work, you no doubt realize that we are still very much in the middle of development. Our development process took the open source boost multi index containers as a starting point and changed implementation details to meet our criteria. There is a lot of that code that still needs to be cleaned up or removed, these macros being one of them.

It might not happen in the next few days, but rest assured, it will be cleaned up before release. Steem already makes heavy use of C++14 and we plan on keeping Steem as a modern C++ codebase.
