### ISSUE TITLE
Change voting power equilibrium point

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#329]
As we've discussed, the voting power equilibrium point should be lowered to 5 votes per day. This means that having less than full voting power should be the normal condition for most users most of the time (with the exceptions being accounts that are new, idle, or very light users).

The reason for this change is that bots have an advantage over humans:  They can always use all their voting power without any "spillover". Lowering the equilibrium point increases the number of users the system considers to be fully engaged, and thus gives a stronger voice to light-to-moderate users.

**Comment by clayop** [comment]
Sounds great. What is the current number BTW?

**Comment by theoreticalbts** [comment]
Merged.

**Comment by abitmore** [comment]
This change combined with #254 will probably cause new users hard to keep active in the platform. 

Currently, to cast a vote, at least 50M rshares should be contributed, however, current ratio of STEEM per mVESTS is more than 300, for a new user registered with 3 STEEM, 50M rshares is more than 0.5% of total voting power, so the user is unable to vote on posts already. The witnesses now changed . the default register fee to a bit more than 3 STEEM, so users have better experience. However, after this change took effect, voting power will regenerate more slowly, so new users will hit the limit more frequently, which will probably lead to bad user experience.

**Comment by mvandeberg** [comment]
Current account creation fee is 3.5 STEEM.
Value of VESTS are 309.55 per 1 million.
That means a newly funded account will have about 11306.735583 VESTS.
A full weight vote will create 11306735583 rshares.
In order for a new account to not be able to vote from a lack of power will require them voting with vote power of 11.05% which will take 53 votes without regeneration to get to. I think we are within an acceptable tolerance that if a new user casts that many votes and there is an error because they voted too much, they should understand it.

**Comment by abitmore** [comment]
> Current account creation fee is 3.5 STEEM.

It was 3 STEEM yesterday. And remember,
* lots of (existed) users still have less than or around 10 BB VESTS, although we increased the registration fee.
* The ratio is increasing every day

> A full weight vote will create 11306735583 rshares.

A full weight vote is `100% * 0.5% * 11306M ~= 57M` rshares. After `log(50/57)/log(0.995) = 27` votes the user would be unable to vote again. If voting power regenerates 5 votes per day, and if an average user votes 15 times per day, after 2-3 days she can not use the platform normally.

**Comment by abitmore** [comment]
Just noticed that the max effective weight of a vote is changed from `1/200 = 0.5%` to `1/max_vote_denom = 4%` after hard fork, so a new user with full power can vote `ROUNDUP( log(50/57)/log(0.96) ) = 4` times, then have to wait for regenerating.

**Comment by mvandeberg** [comment]
Simplifying the math because I don't want to do differential equations right now. Assuming a user votes 15 times instantly and then waits 24 hours and does the same over and over again...

Their voting power at the end of voting will be `new_power = start_power * (0.96) ^ 15`
Their voting power at the start of the next day will be `start_power = new_power + 0.20`

The values that reach an equilibrium are `start_power = 0.436` `new_power = 0.236`.

A user voting 15 times a day will have all of their votes fall within the range `[new_power,start_power]`.
