### ISSUE TITLE
adjust_witness_votes recursion issue

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#33]
Test case:

Assume that `STEEMIT_MAX_PROXY_RECURSION_DEPTH` is 2.
Assume there are 5 accounts `a1`~`a5`, all have 1 VESTS.
Assume there is a witness `w`.

* a1 vote for w, delta = 1
 * depth = 0: w.votes = 1
* a2 set proxy a1, delta = 1
 * depth = 0: a1.proxied_vsf_votes = 0+1 = 1
 * depth = 1: w.votes = 1+1 = 2
* a3 set proxy a2, delta = 1
 * depth = 0: a2.proxied_vsf_votes = 0+1 = 1
 * depth = 1: a1.proxied_vsf_votes = 1+1 = 2
 * depth = 2: w.votes = 2+1 = 3
* a4 set proxy a3, delta = 1
 * depth = 0: a3.proxied_vsf_votes = 0+1 = 1
 * depth = 1: a2.proxied_vsf_votes = 1+1 = 2
 * depth = 2: a1.proxied_vsf_votes  = 2+1 = 3
 * depth = 3: w.votes = 3+1 = 4
* a5 set proxy a4, delta = 1
 * depth = 0: a4.proxied_vsf_votes = 0+1 = 1
 * depth = 1: a3.proxied_vsf_votes = 1+1 = 2
 * depth = 2: a2.proxied_vsf_votes  = 2+1 = 3
 * depth = 3: a1.proxied_vsf_votes  = 3+1 = 4
 * recursion end. w.votes remains 4
* a1 vote for nobody, delta = -(4+1) = -5
 * depth = 0: w.votes = 4 + (-5) = -1

Huh?

**Comment by abitmore** [comment]
With HARD_FORK_3, when a1 changed votes, `adjust_witness_vote` will be called instead of `adjust_witness_votes`, but the result is same.

**Comment by mvandeberg** [comment]
I have gone in an cleaned up some of this code as well as writing a simple test case for the retally logic to ensure we have the correct votes. `live_tests/retally_votes`

This is a correct implementation, but I want to take some time to explain how we are representing it. One of the changes that was made in the most recent commit is the renaming of `adjust_witness_votes` to `adjust_proxied_witness_votes`. The internals of the method remain the same. The point of `adjust_proxied_witness_votes` is now much more clear and is to adjust the accounting on the proxy tree from a non-root node up to the root of the tree. At the root, `adjust_witness_vote` is called based on all votes made by the account. We denote the root by setting `account.proxy` to `STEEMIT_PROXY_TO_SELF_ACCOUNT`. This macro resolves to the empty string, which is not a valid account name and acceptable for this use.

Using the prior example as a starting point...

* a1vote for w, delta 1...
 * a1.proxy = ""; a1.proxied_votes = 0; a1.witness_vote_weight = 1 (0 + 1)
 * w.votes = 1
* a2 proxy to a1, delta 1...
 * a1.proxy = ""; a1.proxied_votes = 1; a1.witness_vote_weight = 2 (1 + 1)
 * a2.proxy = a1; a2.proxied_votes = 0; a2.witness_vote_weight = 1 (0 + 1)
 * w.votes = 2; Because a2 has a non empty proxy, its witness votes are not applied.
* a3 proxy to a2, delta 1...
 * a1.proxy = ""; a1.proxied_votes = 2; a1.witness_vote_weight = 3 (2 + 1)
 * a2.proxy = a1; a2.proxied_votes = 1; a2.witness_vote_weight = 2 (1 + 1)
 * a3.proxy = a2; a3.proxied_votes = 0; a3.witness_vote_weight = 1 (0 + 1)
 * w.votes = 3;

The subtotals are kept in the account objects, but they are never applied because their proxy has been set. This matters because we can now remove a proxy without having to walk the tree. The only accounts we need to modify are the account changing their proxy and the previous target of the proxy account (the new one if it is being changed, but this cost exists in all proxy ops)(also the witness object, but this is modified in all proxy ops).

* a2 proxy to self, delta -2...
 * a1.proxy = ""; a1.proxied_votes = 2 - 2 (2 is a2.witness_vote_weight); a1.witness_vote_weight = 1 (0 + 1)
 * a2.proxy = ""; a2.proxied_votes = 1; a2.witness_vote_weight = 2 (1 + 1)
 * a3.proxy = a2; a3.proxied_votes = 0; a3.witness_vote_weight = 1 (0 + 1)
 * w.votes = 3 - 2 (again from a2.witness_vote_weight)

In this we modify a1.proxied_votes which in turn changes a1.witness_vote_weight, which is implemented as a class method, and we modify a2.proxy. Simple constant time algorithm at no cost. We would need the field for root proxy accounts so repurposing it for this makes the calculations quick and easy.

**Comment by abitmore** [comment]
Actually, with the code in master branch, the test case described in OP will pass since there is a check in the evaluator which will prevent one of the operations from executing. However I have another test case which can freeze the live network (tested with debug_node). Anyway I'll review the latest code.
