### ISSUE TITLE
suspect RC error message

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#3351]
Some users report seeing the following:

> "5097234098 RC, needs 2959082668 RC." and "6810631387 RC, needs 2959715915 RC." are Chrome or Steem's error messages using language calculated using math?
What kind of calculator should I use or is that a bug?

Ref: https://github.com/steemit/steem/blob/dc983c5b0eb5b1731ac3e16d25da5e9a54c6ac06/libraries/plugins/rc/rc_plugin.cpp#L269

Since 5,097,234,098 is well above 2,959,082,668, the message is confusing. Is there an error in how it's generated?

**Comment by payingattention** [comment]
Why did you not source by using my full/real name?

You plagarized that from my chat.

**Comment by joticajulian** [comment]
Maybe using use `rca` instead of `rc_account` in this line:

https://github.com/steemit/steem/blob/dc983c5b0eb5b1731ac3e16d25da5e9a54c6ac06/libraries/plugins/rc/rc_plugin.cpp#L269

**Comment by mvandeberg** [comment]
@joticajulian You appear to be right. I believe this problem has popped up due to a subtle change in how MIRA works as opposed to Chainbase.

Modifcations in MIRA happen in a copy that is then written back to the database. Chainbase does in place modification. The use of `rc_account` is undefined and should be changed to `rca` to be correct in every situation. Furthermore, during the development of MIRA, we added a caching layer to preserve the pass by reference semantics from chainbase that should allow in place modification now. That should be changed as well for efficiency.
