### ISSUE TITLE
Prevent duplicate votes (with same %)

### ISSUE THREAD

**Issue by steemchiller** [steemit/steem#3383]
Currently it is still possible to vote several times for the same post. I think the nodes should prevent this (if there is an old vote with the same %) and return a message like 'You already voted this post with X%'. This would also finally prevent auto votes for old, already voted posts, when they are being edited after payout.

**Comment by mvandeberg** [comment]
The chain prevents votes that consume the same amount of voting mana. We allow changing votes with the same weight because between the last vote and the current vote, a user's mana could have increased and they actually want to award more mana. This behavior should be handled by the UI because there are legitimate scenarios to allow this behavior. With SMTs we are going to add a new vote operation that allows the user to spend their mana directly, rather than go through a vote percent system. I think that operation will alleviate the problem and allow UIs to more carefully handled votes.

> This would also finally prevent auto votes for old, already voted posts, when they are being edited after payout.

Auto votes are a UI problem and should be handled by the UI. I have never have Steemit.com have me automatically vote for myself. If the UI you are using does do this, then I would report that behavior to them and have them change it.

**Comment by steemchiller** [comment]
To be more exact, I mean auto voting services and incoming votes from other accounts, when I edit my paid out posts. Of course, it should be handled by the service providers and I thought they would change this behaviour, but that's not the case.

When I edit one of my old posts, I receive lots of votes (may be more than 50) and there are many new transactions being broadcast, which don't have any effect on the post, because those voters already voted, when the post was still active. I assume, in this case the used mana won't change anything.

I'm not sure, how much that will effect replay times for full nodes in future, but I think we should not store more transactions than we need for having the same result.

**Comment by mvandeberg** [comment]
We cannot go back in time and remove the votes from the blockchain. In such a scenario, those votes are immediately treated as no-ops. They are not significantly impacting the reindex time of the chain.

We could change the behavior for future votes, but as I explained, there are legitimate use cases for keeping the existing behavior. If vote bots are voting on your content after it has been paid out, then that is the loss of those bots. The users delegating their Steem Power to those bots should be complaining to the bot operators to not be dumb.

**Comment by steemchiller** [comment]
>We could change the behavior for future votes

Sounds good. 

>but as I explained, there are legitimate use cases for keeping the existing behavior

I'm wondering, if we could change it only for the case when a post has been paid out and a vote with the same percentage/effect (no effect) occurs. Of course, only for future votes.

>The chain prevents votes that consume the same amount of voting mana. We allow changing votes with the same weight because between the last vote and the current vote, a user's mana could have increased and they actually want to award more mana.

This seems to be true only for active posts. One can make 10 times the same vote on a paid out post without affecting the own mana or the rshares of the first vote in any way. I don't know, if this behaviour will be required for SMTs, but if not, I would be glad to have that fixed.

>The users delegating their Steem Power to those bots should be complaining to the bot operators to not be dumb.

That's true, but it's not that easy to accomplish when also the users of those bots don't have any clue...

**Comment by mvandeberg** [comment]
I double checked the current logic and history of this behavior.

As of HF 12, when content is voted on after it has been paid out, the result is a no-op. No voting mana is consumed, no rshares are awarded, nothing.

HF 21 is actually adding the ability for users with no mana to still vote on content using a similar no-op mechanism because many developers requested the behavior and still see value in recording such no-op votes. Changing the behavior in this scenario would be contrary to the direction we are heading and the requests of other developers.

My final question for you is this: What positive impact on the economy of Steem will this have?

I do not see any reason to change this behavior other than a little confusion/annoyance by some and there are plenty of developers that see this as a positive behavior.

**Comment by steemchiller** [comment]
Example:

User A votes Post X (active) for the first time and adds 1000 rshares.
2 weeks later User A votes Post X again without any effect.
3 weeks later User A votes Post X again without any effect.
4 weeks later User A votes Post X again without any effect.

Here are four transactions being stored in the chain, but we only need the first one. I don't want to change the logic in regards to making votes possible after payout in general. That is well as it is now.

I just don't see any good reason for adding transactions to the chain, which don't have any effect and are just being created for changing nothing. To me that looks like trash we could avoid.

Many people use those auto voting services for voting their favourite authors automatically (for example when they sleep and can't be active on steemit.com) and as I said, each editing of a paid out (and from the same voters already voted) post by one of these authors adds many new garbage transactions to the chain. I guess that are already a few thousand per day. In future even more for sure.

I understand that fixing this issue would require at least one additional check for each vote operation and it's hard to estimate for me, how much difference it would make in regards to the nodes performance. You decide. I just want to say that we are currently storing many transactions that we don't need.

**Comment by mvandeberg** [comment]
Users are paying for these transactions with resource credits. The cost is well accounted for. There is an entire class of operation, custom operations, that have no impact on chain state and is one of the reasons Steem has so many dapps being developed on it. There are many many transactions being stored that we "don't need", but those transactions are providing a lot of value to the chain nonetheless.

**Comment by steemchiller** [comment]
Ok, I'm still not convinced that duplicate `vote` operations, which don't change anything and don't have any benefit, should just go through, but I will close this issue for now, because I think there are more important things to do currently.
