### ISSUE TITLE
Reintroduction of Maintenance Interval to allow payouts after x months?

### ISSUE THREAD

**Issue by xeroc** [steemit/steem#339]
From what I understand, the main motivation of limiting payouts to 30 days (max) is because those posts need to be kept in memory due to being part of consensus. Having an unlimited time would cause high memory requirements for full-nodes.

How about we re-introduce maintenance interval? What were the reasons to remove them to begin with?
With a maintenance interval (say every 4 weeks)
- We could still reward posts after several months
- We could allow nested comments with more than 6 levels (by saying that the recursion of depth 6 is considered in real-time, while the rest is considered only in the maintenance interval)

I am probably missing something but I felt the need to clarify that.

**Comment by TheDarkLightX** [comment]
Good idea.

**Comment by liondani** [comment]
Very nice idea indeed!

**Comment by samupaha** [comment]
Another possibility: user could extend the payout period by paying for it.

If it is costly to allow users do something, isn't the easiest solution to make them pay for it?

Payment should be made with steem which will be destroyed. This would be a good way to dampen the inflation. Probably the effect wouldn't be big, but at least it's something. Because the inflation is so high in Steem, I strongly favor all features that will remove steem from circulation.

I suspect that users would like this, too. One additional option for them to earn more money.

**Comment by hazinstore** [comment]
I like xeroc's version of this idea.

**Comment by theoreticalbts** [comment]
Closing, since upcoming architecture changes will make this ticket obsolete.
