### ISSUE TITLE
REST vs JSON RPC

### ISSUE THREAD

**Issue by faddat** [steemit/steem#347]
What do people think of swagger.io?  I'm a fan.    

Before, a few days ago, when I was deluded, I thought I could just whip up a swagger API spec for steemit.  Turns out though, that with the JSON-RPC API, that's not going to be possible.  Swagger does code generation for API clients among other awesome things.  Personally, I think that it would be great to eventually move towards a swagger-compliant API so that extending our ecosystem becomes easier.  

That said, I know there are some architectural and aesthetic reasons to go with a JSON-RPC API, so if I'm taking the wrong tack here please do enlighten me some.  

Finally, I'm more than willing to be the person who writes up the Swagger YAML API description.  I just want to ensure that it would in fact get used if written up.

**Comment by theoreticalbts** [comment]
> What do people think of swagger.io?

I've never heard of it.

> some architectural and aesthetic reasons to go with a JSON-RPC API, so if I'm taking the wrong tack here

Basically the biggest reason to go with JSON-RPC API is that it's what we have, and switching to something else would be disruptive and consume a ton of developer time.

There are other reasons for going with JSON-RPC API:

- Due to some issues in our network layer that we can't track down, new connections take some time to be established, so we want to re-use connections whenever possible.
- We want to have push notifications to clients, and connection-specific state information, which doesn't really fit with the REST architecture.

What we really need is a way to auto-generate a JSON blob of the available API's, methods, and parameters in the API.  If we had that, it wouldn't be hard to make some lightweight middleware that translates REST-style requests to the JSON-RPC backend.

**Comment by faddat** [comment]
Agreed on the disruptive / poor use of dev time point.  Any idea how I can either build this json blob or find the tools to get one built?   

That JSON blob would open the development floodgates, I think.

**Comment by faddat** [comment]
Additionally, since there aren't *that* many calls I don't mind building the middleware.  I'd do it in golang, and I need the practice anyway.  Mostly, I am interested in getting those floodgates wide open.

**Comment by xeroc** [comment]
You can read the general idea behind separating APIs on docs.bitshares.eu/api
and find the prototypes of the available database API calls [here](https://github.com/steemit/steem/blob/master/libraries/app/include/steemit/app/database_api.hpp)

You can play around with the API [here](http://steemroll.io/api-explorer/#method=get_block&params=[%224000%22])

**Comment by faddat** [comment]
Closing this in favor of the more specific #444
