### ISSUE TITLE
Allowing feed_publish with a lesser key than active

### ISSUE THREAD

**Issue by aaroncox** [steemit/steem#352]
Is there anything from preventing us from allowing the signing of a `feed_publish` operation with either the signing key or the posting key of an account? Currently it requires the active key.

Many witnesses right now run automated scripts for the feed_publish operation, which all currently require either the wif active key or a wallet instance (loaded with the active key) running with access via rpc. Both of these practices present a risk to witnesses that could be resolved simply by allowing a lesser key permission to perform the action.

**Comment by iamsmooth** [comment]
Possibly but I see issues with either signing key or posting key. 

Posting key in its expected use via a web site is subject to being compromised more easily, which could then allow an attacker to maliciously manipulate the feed (possibly a minimal risk though given the existing robustness of the feed to temporary bad input).

Signing key seems to imply a use case of running a feed script on a witness node itself. This is not a good practice because it vulnerabilities to the witness node itself. (For example, the target web server being queried by the feed script would learn of the witness node IP address.) Compromise of the witness node or the signing key could allow an attacker to maliciously sign blocks. Ideally systems hosting witness nodes should be highly locked down with minimal other services.

In the case where the signing key is used but the feed script is run elsewhere with the signing key, this adds additional vulnerability to exposure of the signing key. Compromise of the signing key could allow an attacker to maliciously sign blocks

Nevertheless active key is clearly not ideal either. 

I don't see an completely right answer here, but perhaps given the above considerations posting key is best.

**Comment by mvandeberg** [comment]
#1620 will allow publishing a price feed with the block signing key.
