### ISSUE TITLE
Block Button Feature

### ISSUE THREAD

**Issue by KingArbin** [steemit/steem#382]
I suggest adding a Block Button to Steemit to prevent abusive users from flagging the content of users they don't like. It wouldn't remove already obtained flags as people would abuse that as well, but it would prevent someone that is deliberately flagging all content a user writes. Myself, like many others, are experiencing this with a certain user. I am sure your aware of him by now.

 I would just like to block him to stop him from responding to my content, voting on it, seeing it, and most important, flagging it. This would be helpful to many people.

**Block Button**

What it can do: Restrict a users access from seeing another users posts or taking action on them.

What it Can't do: Remove any current action already taken

**Comment by mvandeberg** [comment]
We cannot do this on the blockchain level because it opens up attack vectors. For example, I could block all whale accounts to stop them from voting on my content, and then I can farm my own content without fear of reprisal.

We do have some plans internally on how to implement some of these features on steemit.com so that while there is no way to stop a negative actor from interacting with you on the blockchain, we can protect you from their actions at the UI level.

**Comment by abitmore** [comment]
Although we can set some limitations in GUI (steemit.com), it's still possible for an abuser to flag innocent authors via CLI or even raw transactions. By the way, perhaps this issue can be solved by https://github.com/steemit/steem/issues/323 .
