### ISSUE TITLE
SBD compound interest?

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#431]
Although interest is only paid when SBD balance changes, we can still pay monthly compound interest. Otherwise people will run bots/services to collect compound interest thus generate a bit more transactions into the chain. The ones who don't do that will suffer a loss.

**Comment by matthewniemerg** [comment]
Even better, we should be able to calculate what the compound interest would be for every block and only apply the interest when a balance moves.  This way, someone could, technically, leave a balance for years and the compounding would only ever occur if the trigger happens.

No need to even change it to auto-trigger monthly.

**Comment by abitmore** [comment]
@matthewniemerg: that's exactly what I wanted to propose in OP. Perhaps I didn't make it so clear though.

**Comment by matthewniemerg** [comment]
I thought you were suggesting to perform the compound interest on people's accounts once a month and not when a balance moved. 

Anyway, here's some basic pseudocode to apply the full compound interest.

This assumes that compound interest is applied on every time a balance changes, i.e. transfer of sbd in / out or payments from author rewards, buying off the internal market, or converting some amount of sbd.  I can't think of any other times an sbd balance would change.  

=====

total_blocks = last_block_num_when_interest_applied - last_irreversible_block_num
blocks_in_a_year = 365*1440*60/30
interest_per_block = .1 / blocks_in_a_year + 1
interest_to_apply = exp(interest_per_block, total_blocks)
sbd_balance *= interest_to_apply

=========

And then, this would be some function that would be called every time there is an sbd balance change.

Note that I put in the last_irreversible_block_num instead of current block as I dunno if there's a way to guarantee which block the sbd balance transfer will be in.

That could pose a problem.

**Comment by mvandeberg** [comment]
We have not had SBD interest in some time. If that changes, we may reconsider.
