### ISSUE TITLE
Serialization of UTF-8 characters

### ISSUE THREAD

**Issue by xeroc** [steemit/steem#44]
I am trying to allow UTF-8 encoded posting in `piston`. However I fail
to understand how the serialization in steem/fc works and why it is
encoded that way. Unless I am doing something wrong, the UTF-8 encoding
code by made more efficiency.

Steem does the following (the script `7532303236` comes from a valid
transaction constructed via `cli_wallet`):

    from binascii import hexlify, unhexlify
    >>> unhexlify("7532303236")
    b'u2026'
    >>> print("\u2026")
    '…'

That's *5* bytes for a single UTF-8 character.

The same utf-8 character in python

    >>> "…".encode('ascii', 'backslashreplace')
    b'\\u2026'
    >>> hexlify(b'\\u2026')
    b'5c7532303236'      (note the extra 5c (backslash) at the beginning)

Can be encoded in only *3* bytes:

    >>> hexlify(bytes("…", "utf-8"))
    b'e280a6'
    >>> print(unhexlify("e280a6").decode('utf-8'))
    '…'

If I wanted to get python working with steem and UTF-8 characters, why
is your serialized code missing the escape backslash?

**Comment by xeroc** [comment]
To me it seems as if the steem/graphene-serialization of unicode chars does not use a backslach as escape sequence.. Is that about correct? Where can I find the relevant code?

**Comment by theoreticalbts** [comment]
This is where you go wrong:

    >>> "…".encode('ascii', 'backslashreplace')
    b'\\u2026'

Instead you should be doing this:

    >>> "…".encode("utf-8")
    b'\xe2\x80\xa6'

If you need to go the other way you can reverse it in the obvious way:

    >>> b"\xe2\x80\xa6".decode("utf-8")
    '…'

Encoding / decoding of utf-8 chars is a client-side concern.  At the blockchain level everything's treated as binary, but string-like fields are required to pass `is_utf8()`.  That function is implemented in `libraries/fc/src/utf8.cpp` which is a thin wrapper around a vendorized copy of https://sourceforge.net/projects/utfcpp

FWIW, since Steem's inception I've argued that the blockchain shouldn't even enforce this; if a user agent sees a binary string that doesn't parse as valid UTF-8, then figuring out what to do with it is the UA concern, not a blockchain concern.  This would allow memos, posts, and other blockchain objects to be binary without forcing people to use b64 or some encoding and waste space.

My position hasn't been accepted by the rest of the team -- the consensus of the team (with which I personally disagree) is that it is so hard to deal with non-UTF8 data in the browser that forbidding it at the blockchain level is a better alternative.

Regardless, this isn't really a Steem issue at all, it's a user-agent issue -- the piston UA needs to code UTF-8 as bytes using `s.encode("utf-8")` where `s` is the string that needs to be encoded.  (You may also need to look into the `codecs` package in Python, and test your code with several different Python versions.)

**Comment by xeroc** [comment]
@theoreticalbts I do serialize `…` to `01e280a6` where the leading `01` is the varint-length prefix.
However, the cli-wallet doesn't serialize that way but instead does this: `057532303236` (a length 5 string)
That is why I am asking.

Example:

```{'expiration': '2016-04-06T08:29:27',
 'extensions': [],
 'operations': [['comment',
                 {'author': 'a',
                  'body': '…',
                  'json_metadata': '',
                  'parent_author': '',
                  'parent_permlink': '',
                  'permlink': 'a',
                  'title': '-'}]],
 'ref_block_num': 34294,
 'ref_block_prefix': 3707022213,
 'signatures': ['203522250c7b89aa11db5aa50cbe9ebe68cde487937fbdbbfa62e3a41b3396aa933db0fb59da1e9c21ce7bd29a60b618a26d16e638c8a6d55a83c2b58430f9c5ca']}
```

cli-wallet: `f68585abf4dce7c804570101000001610161012d057532303236000001`
expected: `f68585abf4dce7c804570101000001610161012d01e280a6000001`

**Comment by xeroc** [comment]
fixed it with this patch
https://github.com/xeroc/python-graphenelib/commit/22f2b699eec04cb5786e9873bee97a5ed7e9c766

**Comment by xeroc** [comment]
Figured out it was a completely different thing causing my issues. Sending non-ascii json via RPC required some extra efforts.
