### ISSUE TITLE
How to launch seed node?

### ISSUE THREAD

**Issue by mahnunchik** [steemit/steem#457]
I've just realized that you have built official docker image of steem https://hub.docker.com/r/steemitinc/steem/ It is great!

So I'd like to launch seed node =)

* How to launch seed node? Are there any requirements to host?
* Could the same process be a witness?

**Comment by faddat** [comment]
On my beefy bare-metal server hosted at hetzner.de, I'm able to simply do a 

docker pull steemitinc/steem
docker run -d -P steemitinc/steem

to keep standard port mapping, don't run the second command above, and just do:

docker run -d -p 2001:2001 -p 8090:8090 steemitinc/steem

and finally, to keep standard port mapping and to bind-mount your own configureation file into the container, try this:

docker run -d -p 2001:2001 -p 8090:8090 -v /path/to/config.ini:/etc/steemd steemitinc/steem

So say you have a config.ini file in /foo, here's what you'd do, exactly:

docker run -d -p 2001:2001 -p 8090:8090 -v /foo:/etc/steemd steemitinc/steem

And that will add your folder with the config file to the filesystem on the inside of the container.  In docker, it's always outside:inside.  

If you've got any other questions, just give a shout :).

**Comment by mahnunchik** [comment]
Ups, I've just realised that `steemitinc/steem` is built for testnet in debug mode O_o https://github.com/steemit/steem/blob/develop/Dockerfile#L40-L42
Dockerfile on docker hub: https://hub.docker.com/r/steemitinc/steem/~/dockerfile/

I've one more question: could single process (container) be a witness and seed node together?

**Comment by faddat** [comment]
Wouldn't it be sweet if steemitinc/steem had.... said that?

I was using the official because I thought official = reliable. just 
switched back to good old teego/steem-wallet

**Comment by sneak** [comment]
@mahnunchik See also: https://github.com/steemit/steem/blob/develop/Dockerfile#L54-62

It builds a test build and runs tests.  If they pass, it builds again in release mode.

**Comment by sneak** [comment]
New plan is to do two different builds in the dockerfile and install them to two different locations.  Dockerized steemd is a work in progress and is subject to chaos for the next few weeks.

**Comment by theoreticalbts** [comment]
@sneak is doing a bunch of new infrastructure stuff for us this month.  While this Dockerhub is public, it's currently intended for internal consumption only and subject to change without notice.  If you use it and it works for you, great, but:

- We're not officially supporting this right now.
- It might break, change, or go away without notice.
- We're not going to give any commitment or ETA on whether this will be officially supported in the future.

We haven't really said anything about this because, considering the above, you probably don't want to use it for anything important until things have settled down, we've figured out how it fits into our workflow -- before we encourage outsiders to depend on our binary distribution, we want to be sure it's stable, secure, and sticking around for a while.  We're not there yet.

**Comment by r3lik** [comment]
how do you specify the location of your config file? I can't figure it out for some reason and it's always over-written in the docker container. is there a -conf location flag?
