### ISSUE TITLE
Protocol Library

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#458]
Separate chain/protocol into its own protocol library.

The protocol library should contain code pertaining to the blockchain protocol (blocks, transactions, operations, etc).

The chain library should contain code pertaining to the in memory representation of the chain state (database objects, evaluators, etc).

**Comment by faddat** [comment]
Hot.  When that refactor is done I will use this:

https://cgogen.com/

For ultimate golang binding success.  For the time being, I am going to pull away from github.com/go-steemit/rpc and stick with net/http for steemjson.  How can I help with this, and what is the best dev env setup for hacking on steem directly?

**Comment by sneak** [comment]
We're testing on Ubuntu 16.04 primarily right now.

**Comment by faddat** [comment]
What do you use in terms of an IDE, etc?  Basically I want to mirror your configuration in my env so that I can pickup on the memes more easily.

**Comment by mvandeberg** [comment]
@faddat I think you have misinterpreted the purpose of this ticket. On master there is a folder `libraries/chain/protocol` that contains code pertaining to the blockchain protocol. `libraries/chain` pertains to the in memory representation of the chain state. We are moving `libraries/chain/protocol` to become `libraries/protocol` and ensuring it is its own compilation unit. This is a good litmus test of our encapsulation of different aspects of steemd. Essentially, `libraries/protocol` would need to be replicated almost exactly in order for another binary to be able to understand the steem blockchain, but you could substitute out `libraries/chain` for any other backend representation of the chain state (SQL, for example) and everything would continue to work. When the refactor is done, nothing will have actually changed, except for the internal structure of the source code.

None of us use IDEs. We each use a text editor of our choice and bash. gdb when it is needed.

**Comment by faddat** [comment]
I certainly did misinterpert.  

I really appreciate your taking time to explain the layout.  I've been reading through the source code, and hope to understand it well enough to make some contributions in the future.  My big hope for Steem's economic future is that we are able to expand the developer ecosystem, and grpc/swagger (probably grpc, not swagger ,as from what I've gleaned so far, grpc requires fewer changes to be made to the code base than swagger would) API support would be pretty enormous.  Coding against STEEM in golang has been quite challenging because I just don't know every single possible return.  I've been trying to find a place in the source code where I can find this but haven't yet authoratitively done so.  I did find this:

```go
func (op *VoteOperation) MarshalTransaction(encoder *transaction.Encoder) error {
	enc := transaction.NewRollingEncoder(encoder)
	enc.EncodeUVarint(uint64(TypeVote.Code()))
	enc.Encode(op.Voter)
	enc.Encode(op.Author)
	enc.Encode(op.Permlink)
	enc.Encode(op.Weight)
	return enc.Err()
}

// FC_REFLECT( steemit::chain::custom_operation,
//             (required_auths)
//             (id)
//             (data) )

// FC_REFLECT( steemit::chain::limit_order_create_operation,
//             (owner)
//             (orderid)
//             (amount_to_sell)
//             (min_to_receive)
//             (fill_or_kill)
//             (expiration) )

type LimitOrderCreateOperation struct {
	Owner        string `json:"owner"`
	OrderID      uint32 `json:"orderid"`
	AmountToSell string `json:"amount_to_sell"`
	MinToReceive string `json:"min_to_receive"`
	FillOrKill   bool   `json:"fill_or_kill"`
	Expiration   *Time  `json:"expiration"`
}
```

in github.com/go-steem/rpc but I'm not 100% sure where the author pulled his references from, I think it's the hpp files, but want to double-check with you.

**Comment by mvandeberg** [comment]
This was finished some time ago.
