### ISSUE TITLE
Consecutive blocks missed - based witness shutdown.

### ISSUE THREAD

**Issue by NateBrune** [steemit/steem#467]
In the existing scheme for witness shutdowns, it takes 24 hours for unresponsive witnesses to have their block-production permissions revoked temporarily. In the event this unresponsive witness happens to be a  top 19 witness... the entire network struggles and lags for the whole day. I propose a system that stops block production based on not just time, but also  consecutive blocks missed. In the current implementation, it only takes 5 blocks to nullify a signing key. Please let me know what you think, I'd love to get some feedback.

**Comment by mvandeberg** [comment]
This is a potential security vulnerability because of what witnesses mean to Steem consensus. Let's say we have a new release for an upcoming hardfork that contains a controversial change. The semantics of witnesses voting for hardforks requires that we have a 75% majority to a hardfork to take place. Let's also say that there is a bug in the release that introduced an inadvertent forking change to the consensus logic. A Savvy developer could discover the forking change right before the hardfork time (that isn't going to pass the vote), cause the chain to fork and then get in some runner up witnesses that agree with their point of view and cause the hardfork to go through without the approval of the voted on top 19.

This would be the equivalent of a state representative not showing up for a vote and immediately being replaced by their competitor in the last election. Their competitor does not represent the view of the people or else the would have been elected. On the other hand, if the representative misses every vote, they won't be re-elected but it also takes some years for them to be replaced. The 24 hours is the same as giving the representative a week or a month leniency before taking action against them.

While it is not ideal that the network is lagging, if it is causing enough harm, people will vote out the witness in favor of someone that is ready to produce blocks.

**Comment by arhag** [comment]
@mvandeberg: The scenario you describe seems to suggest that the network would benefit from maintaining the hardfork super-majority vote for a continuous 24 hours prior to allowing a hardfork to go through. A hardfork is a serious change and there should be enough delay to allow humans to respond by voting out witnesses who are making a decision that goes against their will. The current system doesn't allow for that. The top 17 witnesses could all suddenly upgrade to a new hardforking version with a hardfork time set in the past, and within a minute the network would hardfork.

The downside with such a change is that there would be an additional 24 hour delay in hardforks that fix critical security bugs. Perhaps a compromise would be to make the delay instead depend on how long the witness was in the top 19 for. In the new rules, the blockchain would only hardfork if at least 17 out of top 19 active witnesses (excludes the runner-up witnesses and the miners) in the previous round were _qualified_ witnesses voting for that particular hardfork OR if there was a continuous 24 hour period in which some subset of at least 17 of the top 19 witnesses were voting for that particular hardfork. To be a qualified witness, the witness would have to have remained in the top 19 with no gaps for at least the last 24 hours and been voting for the hardfork with no gaps for at least the last 2 hours. So under normal situations, the already trusted top 19 witnesses could push a critical hardfork in as little as 2 hours (unless at least 3 of them were pushed out of the top 19 by voters). But if the normal top 19 were suddenly replaced (maybe because their signing keys were nulled), pushing a new hardfork would require that 24 hour delay which would give voters enough time to respond if necessary.

**Comment by Gandalf-the-Grey** [comment]
Considering above concerns (potential security vulnerability) and current rules, what is recommended failover procedure for top 19 witness?

Case study:

- Primary witness node fails for some reason.
- Watchdog switch public key to match secondary private key.
- Secondary witness node fails before primary or any other stand-by witness node can be used.

Is it then ok for a top 19 witness to change public key to `STM1111111111111111111111111111111114T1Anm` as a last resort?
(Then effectively top 20 is playing role top 19, 100% participation is maintained)
Or should it leave failing key in place until node would be up again, at cost of <100% participation.

**Comment by liondani** [comment]
@Gandalf-the-Grey "obviously" it's better he nullifies his signing key until his node is up again! I think it is a nice approach! Maybe it needs more consideration near a hardfork time(?) but not on a usual day if you ask me.(I think the same approach should be taken at any time, correct me if I am wrong.)

**Comment by liondani** [comment]
You mentioned 5 consecutive block misses... That means about 5 minutes without block producing for a top19 witness! 24 hours is for sure too long to leave the network "lagging" but 5 minutes is also... too short!! I think your idea is very good but I think we could give a little more time before the signing key get's nullified ... what about something like 15-60 minutes (?)
