### ISSUE TITLE
Need API to return Pending Author/Curator Split

### ISSUE THREAD

**Issue by nedsteem** [steemit/steem#491]
Explanation: Users would like to have accurate expectations of the Steem rewards they can expect as far as Author/Curator split.

Further breakdown by SP/Steem/SBD can be down on the UI level

**Comment by mvandeberg** [comment]
The easiest thing to do is to take the pending payout and multiply by 0.75. Estimating the curation payout on a per user basis (which is required to give an accurate payout prediction) is an expensive operation. 0.75 is a lower bound for the author rewards. We can display it as an estimated author payout and then it can be assumed the remaining 0.25 is the estimated curation payout. The author can get more if there are votes within the first 30 minutes. But again, those calculation are expensive and I feel this estimate gets us most of the way to what users want to see without doing heavy computation.

**Comment by roadscape** [comment]
On the current trending page, author curator "bonus" seems to be around 50%, which means if we use the lower bound of 0.75 we would be underestimating author payout by ~17% and overestimating curator payout by up to 50%. This might still be an improvement but marginal imo. 

It's entirely possible to do this calculation on the frontend, but doing it (in JS) on every client machine for every post sounds even less ideal.

**Comment by theoreticalbts** [comment]
> Estimating the curation payout on a per user basis is an expensive operation

This is true.

> [Walking all the voters] is required to give an accurate payout prediction

This is true, but only because we're not tracking enough information.  The 30-minute rule ("reverse auction") is implemented [here](https://github.com/steemit/steem/blob/bc37c755ed0760abbd27c4c43bea7408c750c2fa/libraries/chain/steem_evaluator.cpp#L1172-L1183) by modulating `cv.weight` by a factor which increases from 0 to 1 over 30 minutes, but `total_weight` is incremented by the pre-modulated value of `weight` [here](https://github.com/steemit/steem/blob/bc37c755ed0760abbd27c4c43bea7408c750c2fa/libraries/chain/steem_evaluator.cpp#L1193-L1196).  The "extra" weight will end up in `unclaimed_rewards` in `pay_curators` [here](https://github.com/steemit/steem/blob/bc37c755ed0760abbd27c4c43bea7408c750c2fa/libraries/chain/database.cpp#L1940) which is then returned to `author_tokens` in `cashout_comment_helper` [here](https://github.com/steemit/steem/blob/bc37c755ed0760abbd27c4c43bea7408c750c2fa/libraries/chain/database.cpp#L1964).

Let's keep track of the sum of the modulated weights.  The ratio of the sum of modulated weights to `total_weight` is equal to the fraction of curators' rewards they keep (as opposed to going to the author due to early voting), from which we can calculate an accurate pending reward without iterating over all votes (although it may still be off by a few satoshis due to rounding).

**Comment by mvandeberg** [comment]
We are going to be moving non-consensus comment information into a plugin (title, body, metadata). That plugin could also keep track of this extra information needed for the API. The goal is to only have consensus data in chain and all other data in plugins.

**Comment by theoreticalbts** [comment]
> We are going to be moving non-consensus comment information into a plugin (title, body, metadata)

AFAICT this improvement wasn't in the issue tracker, so I filed #509.

**Comment by mvandeberg** [comment]
The added fields required to track this information is counter to KISS and is non-consensus. This information is much easier to obtain from an SQL database.
