### ISSUE TITLE
Use promoted cost of an article to rank it on /trending pages

### ISSUE THREAD

**Issue by bonustrack** [steemit/steem#497]
The purpose of this change is to allow users/advertisers to get visibility on the trending pages by promoting article and by the way help SBD supply. 

The amount spend by an user promoting a content would be used to rank article like its now being used for classic rewards. If an advertiser promote a low quality content in top of the results the community still can downvote it and unrank it from trending pages.

This way it will incentive users to spend SBD.

**Comment by xeroc** [comment]
I agree with this .. never understood why the promoted posts are separated from the trending page ..

**Comment by sneak** [comment]
It seems obvious to me: users would like advertising segregated from non-advertising.

**Comment by adcpm** [comment]
You mean segregated promoted from not promoted? Because an advertisement is not identifiable on the blockchain. I personally post for my projects, it could be considered as advertisement for others. IMO the trending page should see the most valuable contents, and i dont see a reason for an advertisement to not be valuable, it's just giving the opportunity to other to get higher visibility on the network and reduce SBD supply. If a post or advertisement is not valuable for the community it will be downvoted.

**Comment by faddat** [comment]
Promoted posts aren't necessarily advertising.  I'd like to say though that this seems like something that is better left to the front end in deference to @sneak's thoughts on the matter:  This way, they're not mixed together on-chain, but are visually, and to an API user can still be separated.

**Comment by iamsmooth** [comment]
Regarding whether promoted content should be separated or combined, a presentation layer can still separate/hide/select promoted content as long as it is identified. I would think of this issue is an enhancement request for the API to provide a composite ranking that consumers of the API could choose to use. How a particular presentation layer (including by user request) chooses to view it is a different question.

**Comment by nedsteem** [comment]
current promoted section is a testing ground.  ideally a thriving website feeding value into the ecosystem via sales of steem for attention would be highly targeted and efficient.  let's view the current implementation as proof that these websites are gateways to a new model for crypto currency

**Comment by samupaha** [comment]
Could we give users an option to blend promoted and trending together? When users can choose it, there shouldn't be any complaining about it.

I guess that many would choose to blend those categories together because they know it would help the system by giving better incentive to pay for post promotion.

Another thing that might be worthwhile to think is how much promotion users are getting with SBD and steem. I'm not sure how it works right now... at least with SBD users are buying promotion for posts, but what about steem? Do people get any visibility when they pay with it instead of SBD?

Currently there is too much SBD in the circulation so it's great way to remove it. But maybe in the future when the price goes up there is no need to destroy SBD so it would be better to destroy steem instead.

This could be accomplished by giving users more visibility with SBD when the price is low (and there is too much SBD in the circulation) and more visibility with steem when the price is high (and there is no need to destroy SBD). Destroying steem is always good idea because it will decrease the impact of inflation.

**Comment by iamsmooth** [comment]
@samupaha my understanding is that the current promoted must be paid with SBD

**Comment by Gutalean** [comment]
Just seen this issue. I have question about curation reward distribution for promoted post here: https://steemit.com/steem/@everythink/q-will-my-post-be-shown-in-trending-if-i-promote-it-with-usd1000-do-i-need-any-votes-from-real-people-for-it
