### ISSUE TITLE
steemd memory use

### ISSUE THREAD

**Issue by Crypto2** [steemit/steem#517]
How much RAM should steemd be using? Even after killing it and restarting within 10-15 minutes it's using a whopping 14GB of RAM. I'm running version 0.14.2 on Debian 8 x64.

**Comment by Gandalf-the-Grey** [comment]
Memory usage depends on various factors like type of your node (witness/miner/seed or for web app?)
Full node with all the plugins, bells and whistles require ~16GB of RAM.

**Comment by theoreticalbts** [comment]
This amount of RAM usage is normal.

If you don't have enough RAM, then try adding a swap file or running on a bigger system (you can rent computers with very large amounts of RAM on AWS for example).  We're working on a massive improvement to our database which will keep the database in a file using mmap() instead of keeping everything in memory, but that work is still in progress.

**Comment by Crypto2** [comment]
It is a full node (as per cmake's output) and uses a default config file. I only need the bare minimum to run cli_wallet, but I can't find any information on what that bare minimum would be???

**Comment by Gandalf-the-Grey** [comment]
make sure you use:
`cmake -DCMAKE_BUILD_TYPE=Release -DLOW_MEMORY_NODE=ON -DCLEAR_VOTES=ON -DENABLE_CONTENT_PATCHING=OFF .`

then edit your default `config.ini` file and change line:
`enable-plugin = witness account_history`
to
`enable-plugin = witness`

**Comment by Crypto2** [comment]
Nice, thanks for the help; that is a major improvement.
