### ISSUE TITLE
Witness Version Communication

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#54]
In hardfork 0_5_0 we will be adding some witness meta communication on the blockchain. We envision several uses for such a protocol, but we are going to start with something simple, and useful. Witnesses will begin broadcasting their Steem version on block production. This version is going to be used to enhance the current hardforking logic by triggering a hardfork when a super majority of witnesses have updated their nodes. This will allow us to release hardforks in a more reliable and speedy manner, specifically when we need to push emergency hardforks.

**Comment by mvandeberg** [comment]
This addition will have the side effect of locking us into our version naming scheme. Witnesses will add their current blockchain version in the block header of all blocks they produce (only 32bits, not a large addition), but the logic for encoding and decoding those bits will be set in stone (possible changeable by a hardfork, but because this is going to change hardfork logic, that will be difficult and require multiple hardforks to disable the functionality and enable new logic. For all intense and purposes, it is final).

The version naming scheme we are settling on is a triple dotted decimal form (ex. 0.5.0). In documentation this is interchangeable with an underscore delimited string (ex. 0_5_0). The only reason behind this convention is that dotted decimal is as close to an industry standard as we have for version naming schemes.

The version number will always take the form `major`.`hardfork`.`revision`
- Major versions are determined by the dev team when the blockchain reaches a "significant" milestone.

- Hardfork versions are incremented every time the release schedules an impending hardfork. Some releases have the infrastructure in place for future hardforks, but we intentionally place those times years in to the future and do not qualify for this type of naming.

- Revision versions are any other "bugfix" or updates that do not require a hardfork. We may suggest upgrading revision releases, but our goal is that all releases on the same hardfork number, regardless of revision number are compatible. Shortly after release we had a number of "softforks" that prevented certain operations from being included while producing. These changes added stability to the chain, but did not effect consensus. Revisions are likely to have these types of changes in them.

**Comment by arhag** [comment]
You have 32-bits, you might as well make the revision 16-bits. I can see rare possible situations where we would wish we could have a version X.X.256 so we wouldn't have to do an unnecessary hardfork.

**Comment by mvandeberg** [comment]
Below is a summary of the new rules for hardforks:

- When a witness is running a new version of steemd containing a hardfork that has not been applied the witness automatically votes for the hardfork to be applied at a specific time. This is done using the compile time hardfork constants.

- When there is a super majority of 17 dpos witnesses voting for a hardfork to apply at the same time, the hardfork is set to happen at the next block that satisfies the time constraint.

- The actual application of the hardfork is no different than it is currently.

- In addition, after 0.5.0, when a hardfork is applied witnesses running an old version of steemd will stop block production after the voted on hardfork application time. This will cause an immediate fork from the old fork to the new, preventing incidental forking that can happen after a hardfork.

- Witnesses can downgrade their running version of steemd and their hardfork vote will be removed, effectively preventing the hardfork time from reaching consensus.

**Comment by abitmore** [comment]
Issues found in 0.5.0:
* [this line](https://github.com/steemit/steem/blob/v0.5.0/libraries/chain/database.cpp#L2924) reads from a negative array index if the program is started with a new database, however it's already there for a long time but didn't make trouble so far.
* [this assertion](https://github.com/steemit/steem/blob/v0.5.0/libraries/chain/database.cpp#L2926) will fail when a hard fork is delayed due to insufficient participation rate. It can be get around by starting with `--replay`
* [this line](https://github.com/steemit/steem/blob/v0.5.0/libraries/chain/database.cpp#L773) will cause another `array index out of bound` issue when trying to downgrade from 0.6.x to 0.5.0. In addition in [this line](https://github.com/steemit/steem/blob/v0.5.0/libraries/chain/database.cpp#L771), the condition after `||` is redundant with [this line](https://github.com/steemit/steem/blob/v0.5.0/libraries/chain/database.cpp#L767)
* [this check](https://github.com/steemit/steem/blob/v0.5.0/libraries/chain/database.cpp#L1110) doesn't guarantee 75% participation rate, in case when the miner and the runner up witness and 15 elected witnesses are upgraded, this check will return `true`, but participation rate in next rounds is 15/21=71.4%
