### ISSUE TITLE
move set point for SBD stability supply control to lower market cap

### ISSUE THREAD

**Issue by iamsmooth** [steemit/steem#540]
Currently SBD stability reduces the print rate of SBD between a market cap of 2% to 5%. At 10% SBD will drop off the peg.

The gap between 5% and 10% is too small. Rapid 50% price changes in volatile crypto assets, including specifically STEEM, are frequent, meaning both dropping off the peg despite creation being stopped (when reaching 5% from above) or restarting creation (when reaching 5% from below) despite there remaining a serious threat of dropping off the peg can easily occur and will continue to occur. Furthermore the market cap ratio is calculated using the trailing median, which means by the time 5% is reached the actual market cap ratio may be even higher (recently when 5% was reached, the real-time ratio was closer to 7%).

Finally, the effect of the variable supply at 2-5% will often be to keep the market cap ratio in that range as a consequence of negative feedback. For similar reasons to those described above, this range is too close to the programmed SBD peg failure at 10%

I propose that SBD print rate be reduced between 0.2% and 0.5% of market cap (changed from the current 2-5%). Other ranges such as 0.2%-1% might also be sensible, but the current 2-5% range is not.

If market dynamics change and STEEM becomes somewhat more price-stable this can be reexamined. It could also be a witness parameter, but current market conditions strongly call for making such an adjustment promptly even if adding witness parameters is not yet feasible.

**Comment by matthewniemerg** [comment]
I'd like to add that a nonlinear production rate could be introduced using a logistics curve to represent total SBD supply and treating the chosen percent of market cap as the carrying capacity.  The logistics model is a common approach to modeling dynamics of a population, and, in this case, the SBD supply would represent the population used in the logistics model.

The dynamics of this scheme would cause a slower printing of SBD as the total supply approached (in a limiting fashion) the capacity.  On the downside (or upside?), faster printing of SBD would occur if too far away from the carrying capacity; although, the effects of how quickly and different the curve is are parameters in a population dynamics model.  

Although, normally there is a decay in the population if this is greater than the carrying capacity.  However, since the carrying capacity is dynamic, i.e. more STEEM is printed, then we could ignore this part of the model, as I would not support a forced conversion of SBD to bring supply to the carrying capacity.

**Comment by iamsmooth** [comment]
Further examination of the SBD system over the past two years has suggested that the approach taken in this issue are probably not a useful direction to pursue. Closing.
