### ISSUE TITLE
Update permlink validation logic

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#56]
Exact spec is WIP.

**Comment by revflash** [comment]
From a blockchain perspective, perm-links serve as unique identifiers for posts. They are an ID of sorts. The only requirement the blockchain has is that they are unique.

We are currently reusing the parent_permlink as a means of grouping content together into topics. Grouping is probably best performed by tags rather than categories. 

Moving to a tag-system for grouping/filtering of posts will give us the greatest flexibility.

I hereby move that permlinks can be any valid UTF8 and that it is the responsibility of the websites to convert permlinks to valid URLs, the blockchain should not be enforcing this.
