### ISSUE TITLE
'Declined Payout' posts should not count towards 4 post limit

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#575]
Currently, 'Declined Payout' posts still count towards post bandwidth.

The 4 post limit should not be applied to these posts, or could be removed altogether.

**Comment by sneak** [comment]
So, if I decline payouts, I can spam as many posts as I want?

**Comment by roadscape** [comment]
@sneak you can already spam as many posts as you want, but their reward potential starts to drop after 4 posts

**Comment by abitmore** [comment]
@roadscape this isn't too easy, because `post_bandwidth` is calculated in `comment_operation` but `decline_payout` is set in a following `comment_options_operation`, so basically we need to "undo" some changes made in the previous operation. Related data is `post_bandwidth` field in `account_object`, and perhaps `last_root_post`(the time point). Not impossible though. One idea is to store some extra historical data so the changes can be reverted.

**Comment by bytemaster** [comment]
4 post limit should be removed in an effort to simplify the interface.

**Comment by mvandeberg** [comment]
The 4 post limit is being removed making this issue irrelevant.
