### ISSUE TITLE
cli_wallet build v0.16.0rc3 on  armv7l GNU/Linux 

### ISSUE THREAD

**Issue by iPerky** [steemit/steem#622]
Is equihash required to build only the cli_wallet?
```make cli_wallet ```

 Is it safe to use the cli_wallet after hashing out references to equihash in the following files?

/programs/cli_wallet/CMakeFiles/cli_wallet.dir/build.make
libraries/fc/CMakeLists.txt

**Comment by mvandeberg** [comment]
Equihash is a part of fc.

While Equihash is not a needed component of the cli_wallet, the wallet does need fc. I would advise against removing Equihash from the build process. Is there a specific reason why you would want to do this?

**Comment by theoreticalbts** [comment]
I'm guessing you're doing this because equihash has some x86-isms and won't build on your target architecture.

You will probably experience some build issues because chain is a dependency of wallet, and fc is a dependency of chain.  This is non-trivial dependency to break, because wallet also depends on plugins, and those plugins really do need to link to chain (i.e., to get object definitions).

Resolving this will probably require either extensive build hackery, or commenting out or otherwise disabling the code in libraries/chain which references equihash.

I'm going to close this as wontfix.

**Comment by arhag** [comment]
> probably it would be simpler to just figure out why equihash isn't working for you and get it to work.

The reason equihash doesn't build on ARM is because [this code](https://github.com/steemit/fc/tree/master/vendor/equihash) depends on two x86-specific instructions. 

One is the [`rdtsc`](https://github.com/steemit/fc/blob/master/vendor/equihash/src/pow.cpp#L12) instruction which actually is not really necessary for the functions that steem uses. You could just get rid of the `rdtsc` static function and also [this method](https://github.com/steemit/fc/blob/master/vendor/equihash/src/pow.cpp#L124) and I think everything should still work fine.

But the bigger issue is that implementation of the blake2b cryptographic hash function used in the equihash code in fc depends on [at least SSE2](https://github.com/steemit/fc/blob/master/vendor/equihash/include/equihash/blake2-config.h#L68) which of course ARM doesn't support. ARM has its own set of instructions for SIMD called NEON. The easiest way to get equihash to work on ARM, however, would be to just use the reference [implementation of blake2b aimed at portability and simplicity](https://github.com/BLAKE2/BLAKE2) instead when compiling for architectures [other than 32-bit or 64-bit AMD or Intel processors](https://github.com/steemit/fc/blob/master/vendor/equihash/src/pow.cpp#L16-L27). This means hashing would be really slow on ARM CPUs, but probably good enough for validating pow2 operations (people really shouldn't be mining on ARM processors anyway). It would also allow compiling cli_wallet for ARM without needing to rework build dependencies.
