### ISSUE TITLE
Add ability for witnesses to decline part of their pay

### ISSUE THREAD

**Issue by bytemaster** [steemit/steem#64]
This will allow witnesses to be competitive on price.

**Comment by steemed** [comment]
Is witness pay wrecking the Steem economy? That is the question we should ask. I don't see that happening so far. There has been no real selling pressure to speak of since the effects of Steemit's transfer of 50k STEEM to bittrex wore off.

Additionally, some witnesses have already used some limited divesting to support Steem.

I don't see the point of this change. Logic dictates that it will degrade witness quality.

It would be far better for community pressure to encourage witnesses to allocate some earnings to benefit Steem. So far there hasn't been time to ensure that the price will stabilize. Only in the last few days has the price began to drift upwards.

Until we know what a stable price will be, it's a bad idea to begin a witness race to the bottom with this sort of change.

**Comment by steemed** [comment]
If we are looking for ways to lighten economic burdens on the steem market cap, then put an absolute cap on power down per week.

**Comment by matthewniemerg** [comment]
The question is what you view to be the role of a witness.  If a witness is supposed to provide value to the STEEM network by paying and building services by converting signing rewards from POWER to STEEM and then selling on the market or paying people in STEEM to perform services, then this is a horrible idea.  

Wasn't the inability to fund new features one of the problems Bitshares encountered?  

All this will do is move the direction of witness signing rewards down and the ability to fund development will dry up like a drop of water on an asphalt in the New Mexico sun.

**Comment by bytemaster** [comment]
After talking this over in the morning meeting we have concluded that giving witnesses the option to decline pay would create a race to the bottom. The goal of witnesses is to get the most work possible for a fixed budget, not to get the least work possible to keep the network alive. This means rewards must remain as is and work done must be increased / maximized.

Any measures taken on this front should be toward minimizing incumbent advantage.
