### ISSUE TITLE
Separate MINER QUEUE from WITNESS objects

### ISSUE THREAD

**Issue by bytemaster** [steemit/steem#667]
This would allow someone to enter the queue multiple times from the same account.

**Comment by mvandeberg** [comment]
This is a change in design philosophy for mining.

Due to the fact that Equihash mining is allowed on any reversible block, allowing a miner to enter the queue multiple times would require caching recent pow or else a miner could submit the same pow on subsequent blocks while the mined block is still reversible.

**Comment by matthewniemerg** [comment]
Would it be an issue if you have multiple machines mining as well?

**Comment by mvandeberg** [comment]
The seed you are mining on is `sha256( block_id, miner_account, nonce )`. Mining on multiple machines is the same as mining with more threads, so long as you manage nonces properly. Many people mine with multiple accounts, which is also perfectly acceptable because they are mining with different seeds and so the work is unique.

**Comment by matthewniemerg** [comment]
So, as long as you manage your nonce on each machine, you're good to go? Great!

**Comment by mvandeberg** [comment]
Mining is going away so this issue is no longer relevant.
