### ISSUE TITLE
STEEMIT BUG DEC 6th (TAGS NOT WORKING IF USEING 5 TAGS)

### ISSUE THREAD

**Issue by jacobcards** [steemit/steem#673]
Hey guys I came across a bug today and its happening with many users not just myself. If you post a post with specifically "5 tags". Your post will only show up under the first tags topic. This bug does not apply if you use 4 or less tags. Here is the post on it. Thanks.
https://steemit.com/steemit/@jacobcards/possible-hardfork-bug-tags-not-working

**Comment by arhag** [comment]
The bug is in the tags plugin.

If the post/comment is `safe_for_work`, i.e. [this branch of the if statement](https://github.com/steemit/steem/blob/v0.16.0/libraries/plugins/tags/tags_plugin.cpp#L204-L205) is reached, then the size of `lower_tags` will increase by 1, assuming there were no empty string tags in the `tags` field of the `json_metadata`. (By the way, that is another bug that can allow NSFW content with negative `net_rshares` show up in the default feed. You really should filter out any empty string tags [here](https://github.com/steemit/steem/blob/v0.16.0/libraries/plugins/tags/tags_plugin.cpp#L192).) So if there were 5 unique non-empty tags specified for the post/comment, `lower_tags` would actually have a size of 6 by [this line](https://github.com/steemit/steem/blob/v0.16.0/libraries/plugins/tags/tags_plugin.cpp#L207), which would mean that [this condition](https://github.com/steemit/steem/blob/v0.16.0/libraries/plugins/tags/tags_plugin.cpp#L209) would incorrectly be true, thus causing, via [this line](https://github.com/steemit/steem/blob/v0.16.0/libraries/plugins/tags/tags_plugin.cpp#L212), the post/comment to show up in the default feed and under the tag for its category but no where else.

**Comment by sneak** [comment]
confirmed by @NateBrune

**Comment by theoreticalbts** [comment]
@mvandeberg this patch removes NSFW flagging from the backend, has someone from the frontend team confirmed that the frontend handles this now?

**Comment by RenaudGagne** [comment]
So if I understand properly, nsfw tag won't show up on the public page anymore?

**Comment by theoreticalbts** [comment]
To keep NSFW off frontpage, `||` [here](https://github.com/steemit/steem/commit/62b7a0daa42e26e22acef263b4f700111162a5d4#diff-29ef2d1f0052c3113dbcb2162f9b39b8L200) should be `&&`

**Comment by mvandeberg** [comment]
We are leaving the filtering the web front end with the plan to eventually filter based on user preference.

**Comment by mvandeberg** [comment]
This was merged and released in 0.16.1
