### ISSUE TITLE
cli_wallet can't deal with multiple accounts in authorities

### ISSUE THREAD

**Issue by xeroc** [steemit/steem#68]
The account `streemian` looks like this:

```
  "owner": {
    "weight_threshold": 1,
    "account_auths": [[
        "xeroc",
        1
      ]
    ],
    "key_auths": [[
        "STM7H3YNtDHtGMP5yqA4hGxWDzCnB9TPwb7ocbHzoT2ePLzG6bBpi",
        1
      ]
    ]
  },
```

The other permissions only hold a key.
When I try to transaction from that account, I get:

```
10 assert_exception: Assert Exception
it != approving_account_lut.end(): 
    {}
    th_a  wallet.cpp:598 operator()

    {"ops":[["withdraw_vesting",{"account":"streemian","vesting_shares":"22189715.573908 VESTS"}]],"sigs":[]}
    th_a  transaction.cpp:270 verify_authority
```

**Comment by abitmore** [comment]
I'm afraid that CLI doesn't support "account authorities" so far. There is a TODO in the [code](https://github.com/steemit/steem/blob/v0.4.3/libraries/wallet/wallet.cpp#L577):
```
      /// TODO: recursively check one layer deeper in the authority tree for keys
```
BTW same issue found in BitShares CLI.

**Comment by xeroc** [comment]
With recent events, can we have this fixed please?!

**Comment by xeroc** [comment]
bug seems to be fixed in 
https://github.com/steemit/steem/commit/a6684ce

**Comment by bacchist** [comment]
Not sure whether this is the same issue, or another one... (sorry for the formatting)

'[ERR] HTTP Code: 500, URL: http://127.0.0.1:9080, Content: {"id":1,"error":{"code":1,"message":"10 assert_exception: Assert Exception\nit != approving_account_lut.end(): \n {}\n th_a wallet.cpp:585 operator()\n\n {\"ops\":[[\"vote\",{\"voter\":\"laonie11\",\"author\":\"agapakos\",\"permlink\":\"deep-lucid-dreams-my-hunt-for-perfection-continuous\",\"weight\":3100}]],\"sigs\":[]}\n th_a transaction.cpp:174 verify_authority","data":{"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"wallet.cpp","line":585,"method":"operator()","hostname":"","thread_name":"th_a","timestamp":"2016-10-05T10:03:46"},"format":"it != approving_account_lut.end(): ","data":{}},{"context":{"level":"warn","file":"transaction.cpp","line":174,"method":"verify_authority","hostname":"","thread_name":"th_a","timestamp":"2016-10-05T10:03:46"},"format":"","data":{"ops":[["vote",{"voter":"laonie11","author":"agapakos","permlink":"deep-lucid-dreams-my-hunt-for-perfection-continuous","weight":3100}]],"sigs":[]}}]}}}'

**Comment by xeroc** [comment]
People started complaining they can't use the cli-wallet on accounts that have another *account* in their posting permission:

```
10 assert_exception: Assert Exception
it != approving_account_lut.end():
    {}
    th_a  wallet.cpp:585 operator()

    {"ops":[["vote",{"voter":"steve-walschot","author":"steemychicken1","permlink":"adjusting-your-voting-power-cliwallet-only","weight":10000}]],"sigs":[]}
    th_a  transaction.cpp:174 verify_authority  
```

**Comment by xeroc** [comment]
Can I bump this?
We really need this for some whales to be able to secure their accounts!

**Comment by aaroncox** [comment]
I'm not sure this issue should have been closed - this is still happening in the current build of the cli_wallet.

**Comment by abitmore** [comment]
The fix linked above hasn't been merged into master.

**Comment by develCuy** [comment]
There seems to be a conflict with the "fix", any plans on getting multisig working for cli_wallet?

**Comment by theoreticalbts** [comment]
Status update:  The above code should fix the wallet bug, but needs reviewed / tested.  The new architecture will allow refactoring consensus code.

Short summary:  Normally, your account is controlled by a key.
You can also allow another account to act as a sort of "puppet
master" to control your account instead of, or in addition
to, your key.

The "puppet strings" form a graph, you have to walk along
the strings to find the puppeteer's key in order to sign or
verify transactions signed by the puppeteer but executed by
the puppet.  This walking code is re-implemented in multiple
places, and the signing version used by `cli_wallet` is
missing several important corner cases, so the `cli_wallet`
doesn't recognize when you're a puppeteer attempting to sign
a transaction to use the puppet.

With the old code, there are three, or sometimes four,
[different types of authority](https://github.com/steemit/steem/blob/f0e147d0aec0d0a36a8c899f00d18bd0c856b6bc/libraries/protocol/include/steem/protocol/authority.hpp#L11-L17) which are stored in three, or sometiems four,
parallel
[object members](https://github.com/steemit/steem/blob/f0e147d0aec0d0a36a8c899f00d18bd0c856b6bc/libraries/chain/include/steem/chain/account_object.hpp#L145-L147),
[operation members](https://github.com/steemit/steem/blob/f0e147d0aec0d0a36a8c899f00d18bd0c856b6bc/libraries/protocol/include/steem/protocol/steem_operations.hpp#L17-L19),
[functions](https://github.com/steemit/steem/blob/f0e147d0aec0d0a36a8c899f00d18bd0c856b6bc/libraries/protocol/include/steem/protocol/base.hpp#L13-L16)
and [function arguments](https://github.com/steemit/steem/blob/f0e147d0aec0d0a36a8c899f00d18bd0c856b6bc/libraries/protocol/include/steem/protocol/transaction.hpp#L60-L83).

Why is the old code such a mess?

When writing code to handle `N` things, and you know for
sure that `N = 1`, writing code that can actually handle up to
`N` cases is a waste of time, unnecessary abstraction.  When
writing code to handle `N` things, and you know for sure that
`N = 4`, you probably should create it to actually handle `N`
things, because otherwise you spend all your time copy-pasting
and potentially creating subtle bugs when you don't edit all
`N` instances of the code correctly.

The authority structure gradually evolved over time from `N = 1`
to `N = 4`, and that is why it's such a mess now.

So I created a new architecture which attempts to handle `N`
different types.  Because replacing consensus requires careful
handling, I wrote it only to replace the wallet.  But the goal
was to eventually replace most of the consensus authority handling
as well.

The main new concept introduced is an `authorization` which is
basically [an account, role pair](https://github.com/steemit/steem/blob/1e78f82ed11d1573adbb72beea4b3c015e8c4321/libraries/protocol/include/steemit/protocol/auth_rule.hpp#L59-L69).  Authorizations can
"trigger" other authorizations, for example:

- The concept that
"the owner authority can do anything the active authority can do"
can be phrased as "for any account A, (A, owner) -> (A, active)".

- The concept of "alice's active key is a hierarchical threshold multisig of
bob (weight 1), charlie (weight 1), dave (weight 2), and public key STMxxxxxx (weight 1)
with threshold 3" can be phrased as:

```
DHMS(3, ((bob, active), 1), ((charlie, active), 1), ((dave, active), 2), ((STMxxxxxx, 1))) -> (alice, active)
```

Basically the LHS of a rule is a weighted threshold function of some authorizations and keys,
the RHS is simply an authorization.  This rule data structure is
implemented [here](https://github.com/steemit/steem/blob/1e78f82ed11d1573adbb72beea4b3c015e8c4321/libraries/protocol/include/steemit/protocol/auth_rule.hpp#L71-L153).

Once you have this data structure, we can implement an
[adapter that re-interprets the chain's legacy authority structures as rules]
(https://github.com/steemit/steem/blob/1e78f82ed11d1573adbb72beea4b3c015e8c4321/libraries/protocol/include/steemit/protocol/operation_util_impl.hpp#L77-L167) and function to
[walk backwards from the RHS of a rule to LHS]
(https://github.com/steemit/steem/blob/1e78f82ed11d1573adbb72beea4b3c015e8c4321/libraries/wallet/wallet.cpp#L261-L324)
and puppeteers should be able to use the wallet.

My code doesn't attempt to replace the consensus code for walking
backwards along puppet strings to verify authority.  It's
only actually used in the wallet.  The main blocker for using
it in consensus is that (1) it's not been reviewed or thoroughly
tested, and (2) the search may be deeper or shallower than the
existing consensus code in particular corner cases, so the old
logic needs to remain in the code so we can implement a properly
gated hardfork.

But I was hoping this would eventually be able to replace consensus
code as well.

**Comment by sneak** [comment]
Closing this, as supporting the cli_wallet any further is a non-goal.
