### ISSUE TITLE
get_witness_schedule returns hex string for current_shuffled_witnesses

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#681]
![image](https://cloud.githubusercontent.com/assets/5168676/21019939/68956d18-bd40-11e6-8fb5-069568316b3b.png)

**Comment by roadscape** [comment]
Also noticed these last 2 values don't look correct:

![image](https://cloud.githubusercontent.com/assets/5168676/21019985/95c719d0-bd40-11e6-8369-6589b482263b.png)

As far as I can tell, sbd_interest_rate should be 9% currently and max block size 65kb.

**Comment by theoreticalbts** [comment]
OK, what's going on with your first error is I didn't catch this when evaluating #620 because the `witness_schedule_api_obj` is `typedef`'ed to the actual object.  We need to go in and fix any of these objects which have `fc::array`.

The second error I'll address in a separate ticket because it's something different.

**Comment by mvandeberg** [comment]
We just need to create an API object that converts the `fc::array` into a `vector`. We are having to do a similar approach with other objects.

**Comment by theoreticalbts** [comment]
Checked all the objects, this is the only place where an `fc::array()` can be returned by one of the `typedef`'ed object types.

**Comment by abitmore** [comment]
Please check #657 as well.

**Comment by mvandeberg** [comment]
Fixed in develop
