### ISSUE TITLE
Refactor virtual operations out of protocol

### ISSUE THREAD

**Issue by arhag** [steemit/steem#696]
Steem virtual operations don't belong in the `protocol` directory IMO. For example, I shouldn't have to recreate the `witness_schedule_type` enum in `protocol` in other to identify which type of witness received a block reward in a new block reward virtual operation I am developing. I should just be able to use the existing `witness_schedule_type` in `witness_object` (which is in the `chain` subdirectory).

I think [`operation`](https://github.com/steemit/steem/blob/develop/libraries/protocol/include/steemit/protocol/operations.hpp) should only include real operations in the blockchain. And a different `virtual_operation` static variant is needed in the chain folder where it belongs. This requires refactoring code in various places though.

**Comment by bytemaster** [comment]
The reason virtual ops are part of the same `static_variant` as real ops is so that they can be processed by the same code path and with the same visitor.  This facilitates situations where the state needs to be inspected before and after the virtual op.  

I agree that we need to clean up and refactor this aspect.

**Comment by mvandeberg** [comment]
Closing, obsolete by automated actions.
