### ISSUE TITLE
Equalize Per Block rshare Value

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#771]
In each block where a payout occurs, each comment should receive the same STEEM/rshares such that the comments should be able to be paid out in any order and arrive at the same state.

**Comment by theoreticalbts** [comment]
Basically the fraction `total_reward_fund_steem / total_reward_shares2` needs to be pre-computed.  Since `total_reward_shares2` is much greater than `total_reward_fund_steem` it suffices to divide by a pre-computed fraction `total_rshares2 / rf`.  This fraction needs to be rounded *up* so the reward of each author will effectively be rounded down.

**Comment by theoreticalbts** [comment]
A unit test to ensure these are commutative will entail using one of several clamps [1] to reduce one payout to the point where a significant amount would be awarded to the next cashout, then ensure the payouts remain the same under the new HF rules.

[1] Clamps include `reward_weight`, `max_steem`, `STEEMIT_MIN_PAYOUT_SBD`.

**Comment by theoreticalbts** [comment]
Closing since this is merged.

**Comment by mvandeberg** [comment]
This is not merged. #790 was merged.

**Comment by theoreticalbts** [comment]
> This is not merged.

Saw a merged PR in the ticket and no PR's referencing this feature, so I assumed it had been merged.  Turns out someone didn't create a PR because someone wanted to hold off merging until someone had a unit test for this.  And I guess "someone" is me.  Sorry about that.

It's ready to be merged now though, Rebased and added a unit test.

**Comment by mvandeberg** [comment]
Merged
