### ISSUE TITLE
get_discussions_by_comments sorts by updated, not created

### ISSUE THREAD

**Issue by roadscape** [steemit/steem#783]
The result is that a user's Comments tab has out of order posts.

In addition, the same thing happens on Replies tab. But I did notice that this method is called `get_replies_by_last_update`. Ideally it would be `get_replies_by_created`. I don't think users expect that editing posts should bump them up in these lists.

Ref: https://github.com/steemit/steemit.com/issues/539

**Comment by mvandeberg** [comment]
This index is used in the follow API calls:
`get_discussions_by_comments`
`get_discussions_by_author_before_date`
`get_state` for (@account/posts and @account/comments)

Would it be better for these API calls to sort based on creation time instead of update time?  I would prefer changing the index instead of adding a new one, to minimize the impact to reindex time.

**Comment by roadscape** [comment]
It doesn't appear steemit.com uses `get_discussions_by_author_before_date` anywhere in its codebase, so no worries there. We do use `get_discussions_by_blog`, I'm guessing this replaced it.

For `get_discussions_by_comments` and `get_state` this sounds good.

Where does `get_replies_by_last_update` fit in with this?

**Comment by mvandeberg** [comment]
`get_replies_by_last_update` is called in `get_state` for @account/recent-replies

**Comment by roadscape** [comment]
Let's leave it as-is for now.
