### ISSUE TITLE
`get_ops_in_block` doesn't seem to be working in 0.16.1

### ISSUE THREAD

**Issue by xeroc** [steemit/steem#786]
`get_ops_in_block` doesn't seem to be working. I have a configuration like this:

```
enable-plugin = account_by_key
# enable-plugin = account_history
enable-plugin = follow
# enable-plugin = market_history
enable-plugin = tags

public-api = database_api login_api
public-api = account_by_key_api
public-api = follow_api
#public-api = market_history_api
public-api = tag_api
```

But I only obtain an empty result array:
```
curl --data '{"id": 123, "params": [0, "get_ops_in_block", [8436581, false]], "jsonrpc": "2.0", "method": "call"}' https://this.piston.rocks
{"id":123,"result":[]}%
```

if you ask steemit's API, you get a whole bunch of virtual operations!

@arhag

**Comment by aaroncox** [comment]
I believe it requires the account_history plugin to function properly. I haven't upgraded to 0.16.1 yet, but the patched I've been running for the last few versions I believe required it.

**Comment by xeroc** [comment]
That would explain it.
@devs: any way to remove that dependency? account_history consumes so much memory

**Comment by aaroncox** [comment]
Giving this a bit more thought today - I'm not sure if my previous comment is correct. It does sound like an index of some sort is missing, but I'm not sure if the account_history plugin is missing. 

My local 0.16.1 node on my dev environment just finished replaying this morning, I'll run some tests against it to see if I can provide any more insight, unless someone else definitively knows what's going on with it.

**Comment by arhag** [comment]
You need a full node running the account_history plugin, and set to capture the full history, in order to retrieve all operations (virtual and real) using get_ops_in_block.

@xeroc: There could be ways (with a lot of reworking) to retrieve the real operations from the blockchain directly, but that wouldn't cut it for virtual operations. Currently, only account history plugins records all operations (including virtual). To make get_ops_in_block work, virtual operations would need to be recorded, which would necessarily use up more memory. I used the account_history plugin for this to not duplicate already recorded data, and because it made it easier to implement.

**Comment by theoreticalbts** [comment]
The architecture of virtual ops is going to be seeing some fundamental changes in the near future.  So for now account_history is the way it is, but in the future this situation should improve.  I don't want to make any public statements about exactly what those fundamental changes will look like, because it's a complicated, multi-faceted problem and not even the broadest brush-strokes of the new design are clear yet, never mind the details.

I may come back and update this ticket when more information becomes available.

**Comment by xeroc** [comment]
Thanks for your commens!
