### ISSUE TITLE
Update Trending to use same algorithm as Hot

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#811]
This will allow us to get rid of children_rshares2 #801.

**Comment by roadscape** [comment]
It would still be useful to have an API to return top-level posts by current payout. Comments too.

**Comment by mvandeberg** [comment]
The tags plugin still tracks children_rshares2, which begs the question why have been calculating this in consensus code?

**Comment by mvandeberg** [comment]
The changes being made to the API are as follows.

`get_discussion_by_trending` will use the same algorithm as hot, but with parameters tuned for a single day turnover of posts rather than the one hour used by hot.

`get_discussion_by_payout` now actually returns posts by payout. This sorts both posts and comments.

`get_discussions_by_trending30` will continue to work until the hardfork when the index becomes obsolete.

These changes are being made in such a way that existing applications should be able to continue using them as they currently are and the new sort orders will be returned automatically.

**Comment by mvandeberg** [comment]
Merged
