### ISSUE TITLE
Witness price feed never expire

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#822]
According to the [code](https://github.com/steemit/steem/blob/v0.16.1/libraries/chain/database.cpp#L3151-L3161):
```
   const witness_schedule_object& wso = get_witness_schedule_object();
   vector<price> feeds; feeds.reserve( wso.num_scheduled_witnesses );
   for( int i = 0; i < wso.num_scheduled_witnesses; i++ )
   {
      const auto& wit = get_witness( wso.current_shuffled_witnesses[i] );
      if( wit.last_sbd_exchange_update < now + STEEMIT_MAX_FEED_AGE &&
          !wit.sbd_exchange_rate.is_null() )
      {
         feeds.push_back( wit.sbd_exchange_rate );
      }
   }
```
Once a witness published a price feed, `wit.last_sbd_exchange_update < now + STEEMIT_MAX_FEED_AGE` will always be `true` and `!wit.sbd_exchange_rate.is_null()` will always be `true`, thus the price feed will never expire.

By the way `STEEMIT_MAX_FEED_AGE` is defined as `fc::days(7)` which IMHO is too long (my memory told me it's mentioned somewhere to be 24 hours, but I didn't find where it is).

**Comment by mvandeberg** [comment]
Looks like changing the conditional to `now < wit.last_sbd_exchange_update + STEEMIT_MAX_FEED_AGE` should fix the problem.

Realistically one or two lazy witnesses not updating their price feeds should not have significant impact on the internal price feed, but I do agree that 7 days seems too long. With a 3.5 day conversion delay and feed history window, it means that witnesses can change their feeds slower than the feed is intended to change. Witnesses should be required to update their feeds more often to create a more reactive price feed (although due to the current price being the median of medians, the price feed's reactiveness is intentionally limited).

**Comment by abitmore** [comment]
Need to hard fork.

**Comment by mvandeberg** [comment]
Of course, I thought it was assumed given the nature of the change.

**Comment by abitmore** [comment]
bump

**Comment by mvandeberg** [comment]
Will make this a priority for hf18
