### ISSUE TITLE
Lock Expiration Logging

### ISSUE THREAD

**Issue by mvandeberg** [steemit/steem#829]
Currently, when a read process is usurped by the write process a simple message is displayed in the write process that it had to increment the lock, but this information is not returned to the write process. It is likely that there a couple of API calls that are taking longer than expected to execute. When a read process releases a lock. If the shared lock is not the same one as it released there should be some notification that the lock changed while it was being held.

This should be high priority as a read process that notices this happening may have read incorrect information from the database. Worst case it could even result in a crash.

**Comment by theoreticalbts** [comment]
The read process should effectively `exit(1)` when the lock is incremented.  Because I'm pretty sure the steemit.com production infrastructure is (or could easily be enhanced to) an environment with some kind of service monitoring that restarts aborted read processes, so once the read process knows it is in a possibly corrupt state (but not any details about what exactly is corrupt), the most viable recovery path is to simply fail fast with `exit(1)` and trigger the monitor to launch a new read process.

If this seems drastic, maybe we could gate control of this with a command line option?

**Comment by mvandeberg** [comment]
The problem I see with exiting is that if there is a specific API call that consistently takes too long to execute and if that API call is made by steemit.com, there could be parts of the website that stop working. While it is best to always return accurate data to the user, DOSing our website is not a great design decision.

**Comment by mvandeberg** [comment]
We should instrument wall clock time in FC API websocket layer to log a warning if an API takes longer than 1 sec wall clock time. This will ensure we catch the error even if there isn't a race condition in the locks.

**Comment by mvandeberg** [comment]
Merged
