### ISSUE TITLE
use of submodules causes code review difficulty

### ISSUE THREAD

**Issue by sneak** [steemit/steem#833]
Right now because fc and chainbase don't have their own independent test suites and branch protection, bumping the submodules in this repo causes potentially unreviewed code to end up in steemd.  This is unacceptable for obvious reasons.

We need to standardize on one of two policies:

1) fc and chainbase get moved into this repo, causing all changes to them to undergo the exact same code review procedures as everything else in steemd, or,

2) fc and chainbase get their own independent test suites and branch protection, each repository undergoing the exact same change control as the `steemit/steem` repo.  This is a bit suboptimal though because the submodule ref points to a commit ID and it still could point to a non-reviewed commit in the other repo.  People approving PRs in `steem` would need to *manually verify* that the commit ID for a submodule update matches the tip of `master` on the other repo, each and every PR that updates them.  This is error-prone and would allow a compromised github account to sneak code into the production release of steemd (via a commit on an unprotected branch of chainbase or fc).

I personally think that `fc` and `chainbase` should be subdirectories inside this repository, as they are not consumed by other active projects and should be subject to identical code review as the rest of the code used to build `steemd`.  (Boost notably excepted, as it has its own extensive review/test pipeline due to its widespread use and existing team of maintainers.)

Please advise.   cc @bytemaster @theoreticalbts @mvandeberg

**Comment by theoreticalbts** [comment]
I'm in favor of Option 2.  Too much of Steem is tightly coupled from an architecture standpoint.  We should definitely have branch protection for `FC` and `chainbase`.

> fc and chainbase get their own independent test suites and branch protection

Agreed.  Branch protection is the low-hanging fruit here.  For testing `chainbase`, some of the tests from core could probably be migrated.  @mvandeberg is probably most familiar with exactly what tests should be ported.  FC's makefile has some test targets, but building and running them isn't documented.  The CI maintainer @jredbeard should probably work with the FC maintainer @bytemaster to figure out how to build and run FC's tests in CI.

> People approving PRs in steem would need to manually verify that the commit ID for a submodule update matches the tip of master on the other repo, each and every PR that updates them

I'd be in favor of making it explicit policy to do this.  But I've already been doing that anyway.  Because to me, this is so obviously part of reviewing code that it's automatic, second nature.  And actually, until I read your comment, it did not even occur to me that it might not be such an obvious, second nature reflex for the rest of the backend team.

> This is error-prone

Not any moreso than other code changes, so our existing security measures should suffice (having two people who are supposed to both check it).  Also, Github UI helps, it notes the changed files in submodules.  See for example [this PR](https://github.com/steemit/steem/pull/653).  If you go to the Files Changed tab (which is where I generally start PR code reviews) it lists the files that changed in the submodule.  And you can click on the `N files` part to get a diff view of the submodule.

If we feel really uneasy about it, we can write some CI script which enforces:

- If a commit modifies FC, then it modifies no other files / submodules
- If a commit modifies FC, then FC must be mentioned in the commit message

and require separate PR's into steem for FC.

**Comment by mvandeberg** [comment]
fc has some unit tests. We should run them in the dockerfile. Chainbase is now a part of steem, so that issue is no longer relevant.

**Comment by mvandeberg** [comment]
Did not mean to close. Still need to add fc unit tests in dockerfile.

**Comment by mvandeberg** [comment]
Steem does not have submodules.
