### ISSUE TITLE
Improve last irreversible block processing

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#855]
Plugins or core processing may want to do things with blocks before they become irreversible.  In fact, storing blocks in the block log is part of core processing that essentially has this flow.

To achieve this, we should move last irreversible block discard to *after* all processing, including signals / plugins.

Specifically, we should save the previous irreversible block number in a new `prev_last_irreversible_block` field in DGPO.  Then plugins, or core processing, that wishes to process blocks that are about to become irreversible can do so while still having the blocks in the undo DB.

The particular application of this ticket I have in mind is periodically saving state as it becomes irreversible #854.

I think we want to leave the updating of `last_irreversible_block` to where it currently exists, near the beginning of per-block processing, and split out `block_log` storage and block discarding to the very end of per-block processing.

- Keeping `last_irreversible_block` updating logic in the same place minimizes the chance that other parts of the code that read `last_irreversible_block` will break from this change.
- Having information about how many blocks are about to become irreversible available to later parts of per-block processing may be useful.
- Moving writing / discarding to the end ensures that we can rewind if per-block processing somehow fails.

**Comment by mvandeberg** [comment]
Saving state as it becomes irreversible is a much larger problem than this.

We currently have no way of quickly reading old state from chainbase. We are always reading current, and potentially reversible, state. The simplest way of getting irreversible state is to shutdown a node and restart it. The first thing a new node does is dump reversible state because it has no way of knowing whether it was on a minority fork or not when it shut down. We could add a `--dump-state` option that specifies an output file and have the node dump prior to syncing with the network.

As far are irreversible block processing, we can add a signal for when a block becomes irreversible.

**Comment by mvandeberg** [comment]
This has been implemented.
