### ISSUE TITLE
Provide simple `error` in the API reply

### ISSUE THREAD

**Issue by jcalfee** [steemit/steem#86]
The following is an example of an API error:

```{"id":10,"error":{"code":1,"message":"10 assert_exception: Assert Exception\naccount.vesting_shares > min_vests: Account registered by another account requires 10x account creation fee worth of Steem Power before it can power down\n    {}\n ... ```

Please abstract just the text `Account registered by another account requires 10x account creation fee worth of Steem Power before it can power down` into another variable.  This will allow us to display the text in the UI.

**Comment by abitmore** [comment]
Is it possible to introduce a dictionary based on the error `code`? It would be better for i18n.

**Comment by jcalfee** [comment]
True.  It might sound crazy but some internationalization is done directly on the language now.  With a number system we will often be one short, however, the language we will always have a message.  On the other hand, if we want to react programmatically we need to use a stable number..  So I would say both.

**Comment by jcalfee** [comment]
Can someone point me to the place in the code for this?  I get lots in the API connection code.. Tq..

**Comment by theoreticalbts** [comment]
We tried to do this in BitShares 2.0 / Graphene, but the problem is that nobody wants to take the time to go through the trouble of:

- Thinking up an exception type name
- Defining a new exception of that type
- Placing the new exception in the proper place in the exception type hierarchy
- Changing the macro invocation to use the new type name

I spent a couple days trying to do this on BitShares codebase, and some of that work made it into Steem -- for example in `transaction.cpp` -- the keyword is `STEEMIT_ASSERT`.

But other people kept adding new FC_ASSERT without exception names faster than I could fix existing ones; eventually I gave up.  We'll have to be content with English error messages until our backlog's cleared enough that we can devote a person-week to this very-low-priority task.

**Comment by roadscape** [comment]
This can be accomplished without new exception types. All we need is more easily parseable 'keys' in the error messages.

E.g. `Account registered by another account requires 10x account creation fee worth of Steem Power before it can power down` would just be `error_insufficient_sp_for_power_down`.

Then we would have (per language) mapping `error_insufficient_sp_for_power_down` to human-readable messages. We'd use a regex like /(error_[a-z_]+)/ to detect the error keys.
