### ISSUE TITLE
Suffix UTC dates with 'Z'

### ISSUE THREAD

**Issue by jcalfee** [steemit/steem#87]
"If the time is in UTC, add a Z directly after the time without a space" https://en.wikipedia.org/wiki/ISO_8601

**Comment by mvandeberg** [comment]
The boost ISO8601 serializer does not follow the spec. We would have to reimplement it to fix this. It works so long as there is no time zone specification. Because of no time zone, the times are always interpreted as UTC.

**Comment by jcalfee** [comment]
I guess we should keep patching this (adding a Z only if it is not there).  There are a lot of posts about boot and ISO8601.  Where is the repository?  Is there already a ticket there about this?

**Comment by mvandeberg** [comment]
I looked around briefly and parsing timezones in the ISO 8601 string appears to be a well known limitation of the boost libraries (by design?). A string without a timezone notated (not even a Z notated) parses correctly as a UTC time. If you need to display a time, I would simply offset by the system's local timezone. For sending a time, offset local time by the local timezone and make sure the string representation matches this format. Changing the serialization logic to much could cause problems deserializing past operations on the chain.

**Comment by jcalfee** [comment]
Feel free to close this if you decided not to change it..  Your not going to hurt my feelings .. lol...  I think that is what your saying above.  It may not be the best time to fix this, but that is up to you...

**Comment by jcalfee** [comment]
this is a boost bug...
