### ISSUE TITLE
Feature Request: add build script for Ubuntu like Dockerfile

### ISSUE THREAD

**Issue by bdimych** [steemit/steem#893]
Docker not always can be used, Ubuntu is more universal

**Comment by sneak** [comment]
The Dockerfile is based on Ubuntu 16.04, so if you simply run the commands in the Dockerfile on Ubuntu 16.04, it should work fine.  We don't want to maintain and synchronize two different build scripts, and we use the Dockerfile in production, so that's the one we've standardized on.

If you run into any issues building from the steps given in the Dockerfile, please file a new issue and we will be happy to amend the documentation. :)
