### ISSUE TITLE
0.17.0rc1: Some replies may never be archived

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#902]
According to [this code](https://github.com/steemit/steem/blob/v0.17.0rc1/libraries/chain/database.cpp#L3937-L3944) in `apply_hardfork(...)` of `database.cpp`:
```
            for( auto itr : root_posts )
            {
               modify( *itr, [&]( comment_object& c )
               {
                  c.cashout_time = std::max( c.created + STEEMIT_CASHOUT_WINDOW_SECONDS, c.cashout_time );
                  c.children_rshares2 = 0;
               });
            }
```
If a root post is in `second_payout` period, its `cashout_time` won't change when applying HF17.

According to [this code](https://github.com/steemit/steem/blob/v0.17.0rc1/libraries/chain/database.cpp#L1677-L1680) in `cashout_comment_helper(...)` of `database.cpp`:

```
         if( calculate_discussion_payout_time( c ) == fc::time_point_sec::maximum() )
            c.mode = archived;
         else
            c.mode = second_payout;
```

Even after HF17, when paying a reply, it will check the root post's cashout time. If a reply is created after HF17, it's possible that it will be paid before the root post's next payout, so its `mode` will be changed to `seond_payout`; since there will be only one payout per comment after HF17, the reply will never be `archived`.

However, perhaps it's not a big deal, because a comment's `mode` is only [checked when the comment is being edited](https://github.com/steemit/steem/blob/v0.17.0rc1/libraries/chain/steem_evaluator.cpp#L671), so the effect of this issue will be comments in `second_payout` mode can be edited without restriction.
```
            FC_ASSERT( comment.mode != archived, "The comment is archived." );
```

**Comment by mvandeberg** [comment]
The `mode` field is a derived field. I created it to reduce my chances of making an error in the sections of code that dealt with comment payouts. 

`last_payout_time == time_point_sec() && cashout_time != time_point_sec::maximum() => comment_mode == first_payout`
`last_payout_time > time_point_sec() && cashout_time != time_point_sec::maximum() => comment_mode == seconds_payout`
`cashout_time == time_point_sec::maximum => comment_mode == archived`

In HF17, we only care about if it is has been paid out or not. The logic is much simpler and the risk of error is less.

The comment_mode field should be removed and all references to it in consensus should be replaced with the appropriate condition along with documentation of what "mode" the comment is in.

The bug here is that `calculate_discussion_payout_time` was not updated with reflect the change to payouts in HF17. Since it is used in several places, the method itself should be changed to return the payout of the comment after the hardfork.

**Comment by mvandeberg** [comment]
Merged
