### ISSUE TITLE
0.17.0rc1: `clear_expired_delegations()` should modify `received_vesting_shares` too

### ISSUE THREAD

**Issue by abitmore** [steemit/steem#918]
[Code](https://github.com/steemit/steem/blob/v0.17.0rc1/libraries/chain/database.cpp#L3416-L3433).

**Comment by mvandeberg** [comment]
`received_vesting_shares` is modified the moment the delegation is decreased [here](https://github.com/steemit/steem/blob/master/libraries/chain/steem_evaluator.cpp#L2308-#L2311).

Delegations should be reflected immediately. If the delegatee is misbehaving, the delegation needs to be revoked immediately (decreasing the delegation received in the evaluator). However, to prevent exploitation of Vesting Shares, it cannot be returned to the delegator for 7 days so that a single satoshi of VESTS cannot vote on the same content twice (returned to the delegator in block processing).

**Comment by abitmore** [comment]
OK. I misunderstood the expiring thing.
