### ISSUE TITLE
Implement endian swap when casting fixed_string to/from string

### ISSUE THREAD

**Issue by theoreticalbts** [steemit/steem#951]
Currently, `fixed_string` object used for `account_name_type` uses `memcpy()` to copy from string into memory.  The `operator<` is based on the operation's implementation in the `Storage` type.  The `account_name_type` is `fixed_string<Storage>`.

I propose the following changes:

- Move `fixed_string` implementation from FC to `steemd`
- Restrict `fixed_string` to use 128-bit storage, i.e. don't use templates or attempt to be generic
- Use endian swap so ordering of the `Storage` type is the same as the ordering of the original strings
- Totally get rid of `str_less`

**Comment by mvandeberg** [comment]
I noticed that the tags plugin uses fixed string but with 256 bits of storage and suffers from similar problems.

I agree with all of the proposed changes and want to add one more to make this implementation simpler.

Put a 16 character limit on tag names. Because the plugin in non-consensus, we can add a restriction in Condenser to reject tags with more than 16 characters. If the plugin encounters any, we will truncate. The fixed string implementation (with memcpy) is already designed to truncate long string names. It is tested and works. #463 encountered this behavior.

Long term, the tags plugin behavior will be usurped by communities, which will use account names and are also restricted to 16 characters. I see no problem with that move now.

@roadscape, do you have any objections to this change in the tags plugin?
