### ISSUE TITLE
Force `--reindex` if it is really needed

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/steem#988]
Previously while switching to new version (like `v0.17.0` to `v0.17.1`) startup failed if run without `--reply`:or `--resync`:
```
 ISt13runtime_errorEEEE: content of memory does not match data expected by executable
```
`v0.18.0` allows to run `v0.17.1` state without complain, which might cause troubles with HF18 logic

**Comment by mvandeberg** [comment]
We are working on some of the infrastructure to do this. The primary indicator that a node needs to reindex is if the schemas of the binary does not match the schema in the shared memory file. Theoretical is working on that infrastructure for platform independent state save/load.

This particular case is a little trickier because the schema did not change between `0.17.1` and `0.18.0`. We will probably need another layer to add the client version to the shared memory file and then specify on load what versions are compatible and reindex otherwise.

I eventually want all of the reindex logic to be automated and a user issuing the `--replay` command to be a last ditch effort.

**Comment by abitmore** [comment]
There was a `DB_VERSION` which serves this. When a re-index is required, no matter due to schema change or data/logic change, increase the version.

**Comment by mvandeberg** [comment]
For whatever reason it was removed early in Steem's development. (It was already removed in the initial checkin)

**Comment by Hatchi-San** [comment]
To get around this error on a witness config.ini only enable the database_api

**Comment by mvandeberg** [comment]
We don't want the data dir to ever be deleted without explicit arguments.
