### ISSUE TITLE
Blocks are being made with zero transactions

### ISSUE THREAD

**Issue by l0k1-smirenski** [steemit/steem#998]
From one of my `steemd` instances, I have started noticing entries in the log like this:

954048ms th_a       application.cpp:499           handle_block         ] Got 0 transactions on block 10605908 by charlieshrem -- latency: 48 ms

I don't think that a block should be made with zero transactions? Luck of the draw having none in the air, no block payment, but that above looks like the witness gets paid for doing more or less nothing.

**Comment by mvandeberg** [comment]
The witnesses are not being paid for nothing. They are being paid to confirm the actions of past blocks are legitimate and that nothing happened during their production.

If the protocol produced no blocks when there were 0 transactions, how would we distinguish between a missed block and a block with 0 transactions. The difference is extremely important.

We used to not display received blocks with 0 transactions, but the accurately log when blocks are colliding (due to micro-forks) and when block producers are lagging, we are now displaying them.
